### ISSUE TITLE
Feature request: Matrix.im support

### ISSUE THREAD

**Issue by dreh23** [boothj5/profanity#1001]
Profanity came along way and is still my favourite chat client. Unfortunately matrix[1] chat protocol is not supported. Is there any chance? 

https://matrix.org/blog/home/

**Comment by jubalh** [comment]
To my knowledge profanity aims to be an XMPP client. Not a general purpose chat client supporting multiple protocols.

Instead of putting man power into supporting matrix, I would rather suggest improving XMPP support by supporting more XEPs and encryptions.

**Comment by lifranc** [comment]
With matrix, its possible to bridge other protocols, so one could 'access' it using an xmpp client. The main issue is to interoperate e2e crypto. Omemo and olm are similar, so ideally they would merge. Then we could use profanity to chat through a matrix bridge to everyone else.

**Comment by jubalh** [comment]
I'll close this for now as we clearly have not enough man power for this.
