### ISSUE TITLE
Profanity and Athame

### ISSUE THREAD

**Issue by nemanjan00** [boothj5/profanity#1014]
Hello, 

Since Athame replaces readline, while using profanity, I do not see what I am typing inside command/message field, until I press enter... 

Is there a way to use legacy input instead of readline, and do you plan to take a look into solving this problem?

**Comment by nemanjan00** [comment]
Temporary fix would be to start `profanity` with `ATHAME_ENABLED=0` env variable. 

```bash
ATHAME_ENABLED=0 profanity
```

**Comment by jubalh** [comment]
You are referring to https://github.com/ardagnir/athame ?

`Since Athame replaces readline` sounds like readline would be replaced by athame, but I suppose you mean you want to use athame instead of gnu readline on your system?

No experience with it, you could use gnu readline with vim mode instead of emacs mode.

**Comment by nemanjan00** [comment]
Yes, that is the one... 

Yeah, that works, setting vi mode and disabling ATHAME for profanity :D

But, still there is a bug that stops Athame from working with profanity :D

**Comment by jubalh** [comment]
> But, still there is a bug that stops Athame from working with profanity :D

It seems like it.

**Comment by jubalh** [comment]
@nemanjan00 have you pinged the athame devs to find out whether it maybe is the case that  they have a bug?

Maybe you can debug this issue.

**Comment by nemanjan00** [comment]
Hi, I am not using athame atm, due to some other problems

**Comment by jubalh** [comment]
Then I will just assume that this was athames fault and close this issue ;)
