### ISSUE TITLE
Notification of '@all' mentions

### ISSUE THREAD

**Issue by arthurlogilab** [boothj5/profanity#1027]
In some communications systems considered as alternatives to jabber/xmpp there is a functionality for group chats that is quite useful : notifying a group of users using the `@all` mention.

Is there such a functionality in xmpp/jabber and if not, could we have it in the client ecosystem ? Even as a plugin it would be useful.

**Comment by jubalh** [comment]
How do you specify a group of users?

This is not an issue for profanity I think, it should be defined as a [XEP](https://xmpp.org/extensions/) and then clients can implement it. I'm not aware of such an XEP.

**Comment by arthurlogilab** [comment]
In a groupchat the group of users is the users connected in this group chat. 

If implemented on the client side, it guess it would require the client to generate the same behavious as when seing the login mentioned (which I don't think is in the protocol, am I wrong) ?

**Comment by jubalh** [comment]
So this would basically be a highlight to everybody in the room.

If only profanity parses the `@all` then only profanity users will get highlighted. If some users in that MUC choose to use another client they will not get a highlight.

If in your scenario all your team (for example) uses profanity, this certainly could be implemented via a plugin like you suggested.

**Comment by arthurlogilab** [comment]
Indeed, but I'm trying to see if some jabber clients (at least the ones we use) could implement this, without going through a XEP process. 

Thanks for the pointer to #369 it looks like a interesting way to solve this problem.

**Comment by jubalh** [comment]
> Indeed, but I'm trying to see if some jabber clients (at least the ones we use) could implement this, without going through a XEP process.

If clients support highlighting you guys just need to set your highlights. There is nothing else that needs to be implemented.

**Comment by jubalh** [comment]
@arthurlogilab ping

**Comment by arthurlogilab** [comment]
@jubalh thanks for taking the time to answer my request. I agree that we can close this one and keep track of the issue on #369

**Comment by jubalh** [comment]
Awesome

**Comment by jubalh** [comment]
yy
