### ISSUE TITLE
Unable to install plugins from directory

### ISSUE THREAD

**Issue by philipflohr** [boothj5/profanity#1035]
Pointing /plugins install <path> to a directory results in Not a file: <path> instead of installing all plugins from the directory

**Comment by jubalh** [comment]
Right. Help sais: `install [<path>]      : Install a plugin, or all plugins found in a directory (recursive).`

**Comment by jubalh** [comment]
I just tested:
```
/plugins install /home/michael/src/profanity-plugins/stable

14:54:30 - Installed plugins:
14:54:30 -   /home/michael/src/profanity-plugins/stable/platform-info.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/browser.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/emoticons.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/syscmd.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/whoami.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/presence_notify.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/clients.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/sounds.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/ascii.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/say.py
14:54:30 -
14:54:30 - Failed installs:
14:54:30 -   /home/michael/src/profanity-plugins/stable/wikipedia-prof.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/imgur.py
14:54:30 -   /home/michael/src/profanity-plugins/stable/paste.py
```

Didn't get `Not a file`. What are you doing exactly?

**Comment by philipflohr** [comment]
I did

`/plugins install /home/philip/profanity-plugins/stable`

and this results in

Not a file: /home/philip/profanity-plugins/stable

Tested with 0.5.1 from the ubuntu repos

**Comment by jubalh** [comment]
> Tested with 0.5.1 from the ubuntu repos

I tested with latest master, which has some patches from you about plugins.

**Comment by philipflohr** [comment]
Just tested with the current master branch, works as expected.
Seems i accidentally used the wrong version to test..
