### ISSUE TITLE
release 0.6.0 tar.gz contains generated files

### ISSUE THREAD

**Issue by xsfstuff** [boothj5/profanity#1037]
Release 0.5.1 tar.gz was 384K, while 0.6.0 is 994K.
There are a lot of pre-generated files now, that probably should not be in.
E.g. Makefile, Makefile.in, configure etc.
Some contain local paths starting with `/home/michael/`.

**Comment by jubalh** [comment]
Thanks for pointing me to this. I hoped someone would check the RC1 so this doesn't happen. I also ran `make clean` and removed files by hand. Strange that this still happened. Will look at it later and remove them.

**Comment by jubalh** [comment]
Please check new files at https://github.com/boothj5/profanity/releases/tag/0.6.0
https://github.com/boothj5/www_profanity_im/commit/efc0f8d98b61d71f968a05339eab2875cbf2b3ea will be for the website.

**Comment by pasis** [comment]
@jubalh to generate release tarballs use command `make dist`, `make dist-bzip2`, `make dist-xz` etc. If this command doesn't include required files, the autotools scripts must be fixed.

**Comment by jubalh** [comment]
@pasis that's what I would do, but the https://github.com/boothj5/profanity/blob/master/RELEASE_GUIDE.md by James mentions a different procedure.

`make dist` also doesn't work because of `configure-debug` which should actually not be required for the dist.

**Comment by pasis** [comment]
If you mean that `configure-debug` should be in the tarballs, add it to the `EXTRA_DIST` in `Makefile.am`. This is proper workflow. Or just tell me the list of files that need to be added/removed and I will fix `make dist` command.

**Comment by jubalh** [comment]
What I mean is this:

```
make dist
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/michael/src/proftest/profanity-0.6.0'
make  distdir-am
make[2]: Entering directory '/home/michael/src/proftest/profanity-0.6.0'
make[2]: *** No rule to make target 'configure-debug', needed by 'distdir-am'.  Stop.
make[2]: Leaving directory '/home/michael/src/proftest/profanity-0.6.0'
make[1]: *** [Makefile:2145: distdir] Error 2
make[1]: Leaving directory '/home/michael/src/proftest/profanity-0.6.0'
make: *** [Makefile:2222: dist] Error 2
```

This is what I did at the beginning. Then I thought James didn't plan to have this working and thus has the release guide. So I followed that.

**Comment by pasis** [comment]
I see, I will check it at free time.

**Comment by xsfstuff** [comment]
@jubalh Now it looks much better, but `README.md` is missing. It was in the first (broken) .tar.gz.

**Comment by jubalh** [comment]
@xsfstuff yeah I removed it because actually it doesn't contain much information if shipped in a distro. And because James advised to do so in the release guide.

**Comment by xsfstuff** [comment]
@jubalh OK, fine. I would, however, include the changelog file, at least in the next release. A changelog is useful to end users, too.

**Comment by jubalh** [comment]
> A changelog is useful to end users, too.

Agreed! I'll do it next time :-)

@pasis I will close this issue once the website is updated. I will then create a new one for  you to check `make dist` :-)

**Comment by pasis** [comment]
sure, assign the new issue to me then

**Comment by jubalh** [comment]
Website has been updated.
