### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by whoizit** [boothj5/profanity#1049]
I looked in the documentation and a FAQ but did not find the answers to these questions

![2019-04-11-021656_559x59_scrot](https://user-images.githubusercontent.com/359276/55919818-05e28f00-5c00-11e9-81d9-0574d0e87047.png)
1. how to remove joined/left messages
2. how to configure space btw timestamp and messages?
I wanna get something like this `<timestamp> <nick>: <message>`

![2019-04-11-021739_388x58_scrot](https://user-images.githubusercontent.com/359276/55919817-05e28f00-5c00-11e9-8ac3-238abefb513b.png)
3. how to exclude this messages from console. Tray icon blinking cause this messages.

**Comment by kaffeekanne** [comment]
1. check for `/presence [chat|room|private] [all|online|none]`. Have a look at `/help presence`.
2. i think thats not possible at the moment. However you can set a char for encryption types. Also that char is used to indicate special events with `!`.
3. check for `/console [chat|muc|private] [all|first|none]`. Have a look at `/help console`, too.

**Comment by whoizit** [comment]
thank you
