### ISSUE TITLE
Contacts are marked offline despite being online

### ISSUE THREAD

**Issue by pmaziere** [boothj5/profanity#1050]
Everything was fine with 0.6.0 from debian testing

I removed the debian package, compiled and installed 61df0c8e8513a1aa9912e37019a63778ec3ed06c with OMEMO support to test it.

Now, after connection, contacts are marked offline despite being online as shown by another xmpp client (conversations). 
Some of them are set online when they start chatting, while others stay offline despite being engaged in a chat.
All chats are OMEMO enabled.

I could not find a way to log debugging information, so if you need more, I'll be glad to help given that you provide me with a mean to do so :)

Thanks for this long awaited OMEMO enabled profanity !

**Comment by paulfariello** [comment]
Hi,

Can you dump us logs with `profanity --log=DEBUG`.
Logs can be found in `.local/share/profanity/logs/profanity.log`.

**Comment by jubalh** [comment]
Thanks for your report @pmaziere !

Details about debug info should be at http://profanity.im/issues.html

How does Conversations actually show whether a contact is online/offline? Greying out avatars?

**Comment by pmaziere** [comment]
@jubalh Conversations has an option to enable in order to change the color of the "send msg" arrow according to the contact status

@paulfariello here is the log redacted for privacy: let's hope I did not miss anything :)
user1 is never shown online, while user2 appears offline when profanity is connected, then online after sending its first message.
All other users are shown offline while they are actually online.

[profanity.log](https://github.com/boothj5/profanity/files/3069607/profanity.log)

**Comment by paulfariello** [comment]
Thanks @pmaziere for the logs.

Seems like roster is received (line 123) right after presences (last one is at line 108). In such conditions profanity won't update roster in UI.

@jubalh any idea on how it could be fixed? Storing presence until we get roster could be a way.

PS: @pmaziere  you might want to delete your logs now. We have a pretty clear view of what's happening and there is the sasl exchange in the log and you account name ;)

**Comment by pmaziere** [comment]
@paulfariello I did delete the link in the comment, but how do I delete the file uploaded to github ?

**Comment by kaffeekanne** [comment]
#1063 fixes falsely offline roster entries for me.

**Comment by pmaziere** [comment]
It works fine here too
thanks !
