### ISSUE TITLE
Cannot read MUC OMEMO message sent from same account on other device

### ISSUE THREAD

**Issue by willeponken** [boothj5/profanity#1051]
Hello,

Unsure if this a problem with Conversations or Profanity or both... or me?

If I send a message in a MUC with OMEMO from Profanity, I cannot read that same message on Conversations. Instead, I get the message: `Message was not encrypted for this device.`

Additionally, if I send the other way around I get the following in Profanity:
```
I sent you an OMEMO encrypted message but your client doesn’t seem to support that.
Find more information on https://conversations.im/omemo
```

I suppose it's an issue with users that have multiple OMEMO fingerprints, right? Shouldn't the message be encrypted towards my other devices, too?

**Comment by paulfariello** [comment]
Thanks @willeponken for reporting,

Can you ensure that you trust the fingerprint of your Conversations.
```
/omemo fingerprint
```

On main window will show you all your fingerprints with current state.

If you already trust it, can you give us the logs corresponding to OMEMO failing to encrypt and decrypt messages.

**Comment by willeponken** [comment]
Yep, that was it, I hadn't trusted my other fingerprint. Should have thought about that, so the problem was me after all.

Thanks! :)

**Comment by jubalh** [comment]
@willeponken thanks for testing! :-)
