### ISSUE TITLE
OMEMO chat flagged as unencrypted when started from another client

### ISSUE THREAD

**Issue by pmaziere** [boothj5/profanity#1052]
Debian testing, Profanity master HEAD, XMPP server prosody

I enabled carbon copy on all my XMPP clients
When I start an OMEMO encrypted  chat from my Conversations client, profanity opens a window for this chat , but it is flagged as "unencrypted" instead of "OMEMO" despite each message is prefixed with the OMEMO char.

[profanity.log](https://github.com/boothj5/profanity/files/3072277/profanity.log)

That's not a functional issue, but it is still confusing
Thanks for looking at it

**Comment by jubalh** [comment]
@pmaziere thanks for reporting.

Just for the record, at the time of this writing HEAD points at 61df0c8e8513a1aa9912e37019a63778ec3ed06c
(HEAD is like a variable, you need to mention the hash/revision :-))

**Comment by kaffeekanne** [comment]
@pmaziere i suppose you did not start an OMEMO session with the chat partner from profanity? Maybe that issue can be solved alongside with omemo policy.

**Comment by jubalh** [comment]
@pmaziere did you use `/omemo start`?

**Comment by kaffeekanne** [comment]
That also happens, when you receive an omemo message from someone else. Had that recently with @paulfariello. Initiating a message with `/msg` looks up in `trust.txt` and starts/resumes the omemo session. Externally started conversations do not at the moment.

**Comment by pmaziere** [comment]
@jubalh no I did not, but I trusted the fingerprints before opening the chat
@kaffeekanne that's what I observed: chat window started from another client is not flagged as OMEMO, but messages are still prefixed with the OMEMO char, which is inconsistent. I don't know if the OMEMO indicator should be trusted from the window flag or from the message prefix

**Comment by paulfariello** [comment]
This issue can be fixed alongside #1040

**Comment by paulfariello** [comment]
@pmaziere the OMEMO window flag means that you are going to send OMEMO encrypted messages. The OMEMO char means that message either received or sent were OMEMO encrypted.

**Comment by jubalh** [comment]
@pmaziere please give master a try! :)

**Comment by pmaziere** [comment]
I set policy to always, quit , then restart profanity

case 1:
- starting myself a chat from other client => OMEMO tagged window in profanity

quit and restart

case 2:
- contact starts a chat => unencrypted tagged window in profanity
         reply from other client => window is still tagged unencrypted but message appears prefixed with OMEMO char
         reply from profanity => window is still tagged unencrypted and message appears not prefixed with OMEMO char
         /omemo start contact => window is tagged OMEMO and further messages appears prefixed with OMEMO char

I set policy to automatic, quit, then restart profanity

case 3:
- starting myself a chat from other client =>unencrypted tagged window in profanity

quit and restart

case 4: 
- same as case 2

All contacts are using Conversations as client with OMEMO enabled by default.

Is this what was expected ?
I was expecting, in addition to case 1, that case 2, 3 and 4 would also open an OMEMO tagged window, but this may be another issue.

thanks for this fix !

**Comment by paulfariello** [comment]
@pmaziere thanks for testing this.
I'll check why OMEMO isn't enabled when receiving messages.

**Comment by paulfariello** [comment]
@pmaziere last commit should fix the behavior.
The main idea is to follow OMEMO policy in any way. So if set to `always` you should always have window opened with OMEMO enabled.

**Comment by jubalh** [comment]
@pmaziere can you test https://github.com/boothj5/profanity/pull/1067 and see if it's now what you expect?

**Comment by pmaziere** [comment]
Yes ! it works both in automatic and always policy for carbon copy and direct messages
thanks
