### ISSUE TITLE
Generating OMEMO crypto materials freezes client without notification

### ISSUE THREAD

**Issue by optmzr** [boothj5/profanity#1055]
When issuing `/omemo gen` the client just freezes, without any notification that they are being generated. A message like `Generating OMEMO cryptograhic materials, please wait...` would really help, I checked the CPU usage, which was at ~0 %, and just assumed the client had stopped responding and killed it.

Also, I'm actually not sure if this was a "real" freeze or not, as I went ahead and killed the client twice as I had been waiting for ~1 minute. However, the third time, the generation was done faster (I think? I didn't really measure).

This same issue has been observed on two different machines, on these commits:
7be6158c80af09daf58e9b873263d9e98e36aff9
61df0c8e8513a1aa9912e37019a63778ec3ed06c

Maybe the generation could be done in a separate thread?

Thanks for all your hard work!

**Comment by paulfariello** [comment]
thanks @willeponken for reporting.

Unfortunately it's mostly due to GCrypt trying to get some random from `/dev/random`.
Adding a message before generating cryptograhic materials would be a good workaround.
But real fix should be to stop using `/dev/random`.

**Comment by willeponken** [comment]
Okay! As an alternative "workaround" (not really as `/omemo gen` is only run once, so why bother), one can set Gcrypt to use urandom by adding `only-urandom` to `/etc/gcrypt/random.conf`. Or install haveged (and make sure it starts at boot, as I had forgot). Maybe something like this could be mentioned in the future documentation mentioned in #1048?

**Comment by jubalh** [comment]
> Maybe something like this could be mentioned in the future documentation mentioned in #1048?

Good idea. Can you please mention it in that issue?

Maybe adding a message when `/omemo gen` is run is a good idea anyways, so impatient users don't kill the application :-)
