### ISSUE TITLE
Profanity won't start on Debian Buster

### ISSUE THREAD

**Issue by roranicus** [boothj5/profanity#1057]
I got this error message. 

profanity: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by profanity)

Other than that, no clue. I tried to reinstall it, but that wouldn't fix it. I'd be happy to provide more information, but I'm not even sure what I'm looking at, so I'll need some directions.

**Comment by jubalh** [comment]
I don't use Debian. But did you notice the 4 and the 3 in that message?
Did you google it?

One of the first entries I get suggests to install `libcurl3 libcurl-openssl1.0-dev`.
And https://github.com/boothj5/profanity/wiki/Building-Profanity sais: `apt-get install libssl-dev libexpat1-dev libncursesw5-dev libglib2.0-dev libnotify-dev libcurl3-dev libxss-dev libotr5-dev libgpgme11-dev autoconf-archive expect-dev tcl-dev libtool python-dev libgtk2.0-dev automake autoconf libtool pkg-config`

Where I realize I need to update this with grypt and libsignal dependency :-)

**Comment by jubalh** [comment]
@roranicus please try installing `libcurl3-gnutls`.

**Comment by mdosch** [comment]
It's working for me on Debian Buster:

```cat cat /etc/debian_version 
buster/sid

apt list -a profanity
Listing... Done
profanity/testing,now 0.6.0-1 amd64 [installed]

apt list -a libcurl4 
Listing... Done
libcurl4/testing,now 7.64.0-2 amd64 [installed,automatic]
```

**Comment by jubalh** [comment]
What about `apt list -a libcurl3-gnutls` ?

**Comment by mdosch** [comment]
> libcurl3-gnutls/testing,unstable,now 7.64.0-2 amd64 [installed,automatic]

**Comment by jubalh** [comment]
There you go. Like I said the OP probably just is missing `libcurl3-gnutls`.

**Comment by jubalh** [comment]
@roranicus I'm going to close this. In case you still have this issue feel free to reopen.
If not, you can also comment to confirm that it was the issue.

**Comment by mdosch** [comment]
I just tried compiling master from source on Debian Buster. `apt build-dep profanity` will install `libcurl4-gnutls-dev` but compiling and starting profanity works without any trouble.
