### ISSUE TITLE
Issues with selection of messages

### ISSUE THREAD

**Issue by mdosch** [boothj5/profanity#1060]
I'm using profanity 0.6.0-1 from Debian Buster repos.

When I want to select a message to use it for a quote I have the following issues:

* Single line: A double click selects the whole message including timestamp and nick (I like that behaviour) but also a nick from the participants list (which you usually don't want to quote)
* Multi line: Manually selecting a multi line message also selects one nick from the participants list per complete line.

What I would expect: Selecting messages should not select participant list items although I don't know if this is easily to achieve for a TUI client. Please find screenshots showing the behavior attached.

![2019-04-13-224314_grim](https://user-images.githubusercontent.com/5103003/56089505-29256c80-5e94-11e9-8b2c-bf513ae007d7.png)
![2019-04-13-224249_grim](https://user-images.githubusercontent.com/5103003/56089506-29256c80-5e94-11e9-8665-fa3d83e89bf3.png)

**Comment by jubalh** [comment]
My guess is that this depends on your terminal emulator. I would suggest using tmux for copy pasting.

**Comment by mdosch** [comment]
Just opened profanity in termux. Didn't change the behavior for me.

**Comment by jubalh** [comment]
The bevhaviour doesnt change by using tmux.
My suggestion was to use tmux instead of what you are doing. For this you need to set some keybindings to copy and paste and use them.

**Comment by mdosch** [comment]
Someone told me in the profanity muc that weechat has a copy&paste friendly [raw mode](https://weechat.org/blog/post/2014/02/16/Bare-display) which might also be an option for profanity.

Also I'd like a quote feature `/quote <nick> [n]` which fills your input area with the users n-th last message (n being optional and defaulting to the last message) prefixed with a `>`.

**Comment by kaffeekanne** [comment]
Disabling the `/occupants` gets you pretty close to that behaviour. Escape sequences for colors are probably handled by the terminal emulator upon copy. Either they are copied or not.

**Comment by mdosch** [comment]
Thx, that's a great workaround indeed. :)

**Comment by mdosch** [comment]
I'll close this as there is a workaround that works well (except for long URLs) but maybe you can keep [my suggestions](https://github.com/boothj5/profanity/issues/1060#issuecomment-482937231) in mind for later.

**Comment by kaffeekanne** [comment]
Depending on the Terminal, long URLs can be copied starting with `http;//...` and be put even with two or more lines into clip board. When pasting in a recent browser linebreaks are recognized and should not affect loading of the copied page. I have not encountered a browser in recent years, that was not capable of this. Clearly just a workaround, but i think we have more important things to resolve.

But thanks for testing and reporting!

**Comment by jubalh** [comment]
Maybe we could implement https://weechat.org/blog/post/2014/02/16/Bare-display later
