### ISSUE TITLE
Add readline support

### ISSUE THREAD

**Issue by djeikyb** [boothj5/profanity#216]
I'm used to having readline support in the shells I use. When I try to use profanity, it feels so naturally part of my shell environment that the lack of line editing is jarring. It'd be a huge usability bonus to provide this.

**Comment by boothj5** [comment]
GNU readline is now used for input handling.  The changes are in master.

Standard key bindings should work, and profanity will take note of settings in `~/.inputrc` such as Vi editing mode etc.

Profanity registers itself with the name `profanity` which can be used for conditional binding based on application.
