### ISSUE TITLE
Add support for delivery recipts

### ISSUE THREAD

**Issue by hauleth** [boothj5/profanity#265]
Extension [XEP-0184](http://xmpp.org/extensions/xep-0184.html).

**Comment by boothj5** [comment]
Implemented in master.

`/receipts on|off` - Enable or disable message receipts.

The message line will be coloured differently until the receipt is received. The colour can be changed using the theme setting:

```
[colours]
receipt.sent=
```

Which is `red` by default.

**Comment by boothj5** [comment]
Separate options added for requesting and sending receipts:

`/receipts request on|off` - Request receipts when sending messages
`/receipts send on|off` - Send receipts if sender requested
