### ISSUE TITLE
Segfault when home directory doesn't exist

### ISSUE THREAD

**Issue by globalcitizen** [boothj5/profanity#270]
```
# useradd xmpp
# sudo -u xmpp profanity
#      # wtf?
# sudo -u xmpp bash
$ profanity
Segmentation fault # wtf?
$ strace profanity
(... lots of output including ENODIR stuff about home dir)
$ exit
# mkdir /home/xmpp
# sudo -u xmpp profanity
(runs fine)
```

**Comment by jubalh** [comment]
Fix is good enough.
Landed in 0.6.0 0.6.0.rc1 0.5.1 0.5.0 0.5.0.rc1 0.5.0.patch1 0.4.7 0.4.7.rc2 0.4.7.rc1 0.4.7.patch1 0.4.7.cyg3 0.4.7.cyg2 0.4.7.cyg1 0.4.6 0.4.6.rc1 0.4.5 0.4.5.rc1 0.4.4 0.4.3 0.4.3.rc3 0.4.3.rc2 0.4.3.rc1 0.4.2 0.4.1 0.4.1.rc2 0.4.1.rc1 0.4.0 0.4.0.rc2 0.4.0.rc1
