### ISSUE TITLE
Handle invalid SSL certificates

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#280]
As requested at the mailing list https://groups.google.com/forum/?hl=en#!topic/profanitydev/TkhTwYVFph0

**Comment by shawnanastasio** [comment]
Has any progress on this front been made? Last I checked profanity would still blindly connect to any server, regardless of the SSL certificate, which raises a serious security/trust concern.

**Comment by boothj5** [comment]
No progress on this yet.  However, it will probably be one of the first things I look at after releasing 0.4.7.

**Comment by PMaynard** [comment]
Some things which would be nice to see could be: 

- Certificate pinning.
- Fingerprint checking:
    - Keep a cache of server fingerprints, user action on new (Accept/Reject/Once/Always)
    - Warn on change, force disconnect if not matching.
- Check FQDN matches TLS cert.
- Force TLS on all connection, show warning when in plaintext. 
- Restrictions on TLS versions and ciphers.

Some of these can prevent MITM attacks and/or a miss configured server leaking data.
I'm sure you're aware, the XMPP RFC details starttls [here](https://tools.ietf.org/html/rfc6120#page-69), which is a good start.

**Comment by incertia** [comment]
the openssl library should have the necessary tools for verifying certs against trusted CAs, and then we can prompt the user with a "connect anyway (y/n)?" message or something.

**Comment by boothj5** [comment]
Libstrophe needs to be changed to validate the certificates, and allow applications to supply a callback to handle those which fail verification.

I've created a branch in the library and started work on it.

**Comment by boothj5** [comment]
After some discussions related to [this post](https://groups.google.com/forum/#!topic/profanitydev/a1ywwZrWEQM) at the mailing list, I've decided to fork libstrophe to a simpler library (without Windows support for example).

The fork can be found at [libmesode](https://github.com/boothj5/libmesode).  I've started work on certificate verification (only debugging verification results at the moment) in a branch [tls-verify](https://github.com/boothj5/libmesode/tree/tls-verify) and will keep this issue updated.

**Comment by PMaynard** [comment]
This is some good news, I also agree option two is the best choice. I'm now running libmesode and the TLS branch. Will report issues here, or in libmesode if I find them.

**Comment by boothj5** [comment]
A simple implementation of certificate verification is now in profanity.

1) Build and install the `tls-verify` branch of libmesode
2) Build the `tls-verify` branch of profanity

There's plenty more work to do, but currently:

* Certificate verification is performed during connect
* The verification error is shown
* The user can choose to cancel the connection, allow the connection once, or always allow connections with this certificate.

Currently only the fingerprint of the invalid certificate is stored with the last option.  More information should be added (validity dates etc) to allow showing a list of trusted certificates with `/tls trusted` and allow revoking. 

Also the error is shown for which ever certificate in the chain is invalid, most likely the self signed root certificate, however it'd probably be more useful for the user to receive a message about the end user certificate.

Any thoughts welcome.

**Comment by boothj5** [comment]
Additional commands have been added, and everything is merged into `profanity/master` and `libmesode/master` branches.

You can now set the system path to look for SSL certificates (on my machine for example `/etc/ssl/certs`), and manually accept, list and revoke certificates that your system does not recognise.

I've noticed an issue on OSX, but in the meantime if you want to do any testing:

```
tls
---
Synopsis
/tls allow
/tls always
/tls deny
/tls trusted
/tls revoke <fingerprint>
/tls certpath
/tls certpath set <path>
/tls certpath clear

Description
Handle TLS certificates.

Arguments
allow                : Allow connection to continue with an invalid TLS certificate.
always               : Always allow connections with this invalid TLS certificate.
deny                 : Terminate TLS connection.
trusted              : List manually trusted certificates (with /tls always).
revoke <fingerprint> : Remove a manually trusted certificate.
certpath             : Show the trusted certificate path.
certpath set <path>  : Specify filesystem path containing trusted certificates.
certpath clear       : Clear the trusted certificate path.
```

**Comment by boothj5** [comment]
Should now also work on OSX.

**Comment by boothj5** [comment]
Closing this issue, as the handling of invalid SSL certificates has now been implemented.

Note this requires profanity to be built against [libmesode](https://github.com/boothj5/libmesode).

@PMaynard you mentioned some other improvements which I also think are good ideas so I've added separate issues just to make things a bit easier to manage.

Please create any new issues if you have any problems or other suggestions.
