### ISSUE TITLE
Connection hang with TLS on older versions of Openfire server.

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#291]
This issue has been split from #286.

See http://issues.igniterealtime.org/browse/OF-636

Other clients handle the problem, whereas profanity currently stalls on connect.

**Comment by pasis** [comment]
Check strophe/libstrophe@b04c40d3eadc4db94d9b60e1b016ff6a144dc7f3
It fixes endless loop in some cases and high cpu usage during TLS establishing.

**Comment by boothj5** [comment]
Closing as should be fixed by the libstrophe change, although I haven't been able to test.

If anyone manages to still recreate the problem, please raise another issue.
