### ISSUE TITLE
Switching of windows with other modifier

### ISSUE THREAD

**Issue by klump** [boothj5/profanity#358]
I would like to be able to switch between the windows with another key than ALT. Irssi for instance allows switching windows by pressing ESC followed by the number. The functional keys are not always an option.

My problem is that some window managers (like i3) make heavy use of the ALT key. This makes switching windows in profanity harder than it needs to be.

**Comment by boothj5** [comment]
This should now be fixed in master with the addition of GNU Readline support.

Let me know if you have any issues.
