### ISSUE TITLE
Profanity hangs, pins CPU 100% after `/connect`

### ISSUE THREAD

**Issue by aaronlevin** [boothj5/profanity#378]
I just did a vanilla install. Then I do the following:

    $ ~ profanity
    /connect me@server.com

And if I run top I see profanity hogging 100% CPU and the program is inaccessible (I need to `kill -9` to stop it).

My system:

- Arch LInux (`3.15.4-1-ARCH`)
- Macbook Pro Retina
- Profanity, version 0.4.2 (installed via `pacman`)

**Comment by germanrcuriel** [comment]
It hangs with v0.8.6 of libstrophe. Just tried v0.8.7 and it works. Hope it helps :)

**Comment by devhell** [comment]
I can confirm what @germanrcuriel said. Version 0.8.7 of `libstrophe` seems to solve the problem.

**Comment by boothj5** [comment]
Thanks for posting your findings here, I was at a bit of a loss as to what was causing the hang.

I'll close this issue, but if anyone still has the issue with 0.8.7 of `libstrophe`, please reopen.

**Comment by seamus-45** [comment]
Confirm the problem. With profanity-0.4.5 all is fine, but 0.4.6 hangs (100% CPU, interface almost frozen) and I got a random disconnects.

Server: Openfire 3.9.1
Client: Gentoo 3.18.9
profanity-0.4.5 (libstrophe-0.8.6 & 0.8.7) -- OK
profanity-0.4.6 (libstrophe-0.8.6 & 0.8.7) -- FAIL

profanity.log: https://gist.github.com/seamus-45/92b97b02f9cf53871a87
