### ISSUE TITLE
Can't scroll down in mouse mode

### ISSUE THREAD

**Issue by lightonflux** [boothj5/profanity#401]
With enabled mouse mode i can scroll up but not down. I use the [the recent version](https://github.com/boothj5/profanity/commit/225312802e8c7fbc904403af119207d782b2f840#diff-d41d8cd98f00b204e9800998ecf8427e) version.

Can anybody confirm this problem or does this only affect me?

**Comment by boothj5** [comment]
I can recreate the problem, added another issue to correctly implement mouse handling since the GNU Readline changes #594
