### ISSUE TITLE
Mediated invitation support 

### ISSUE THREAD

**Issue by schnoddelbotz** [boothj5/profanity#407]
I had problems with MUC invites not working with Profanity - but other clients would work.
This affects me with 'members-only' chat rooms - where invites make most sense to me.
By looking at xmpp/stanza.c:stanza_create_invite(), I believe that Profanity currently lacks 
the mediated invitation support as described here:
http://xmpp.org/extensions/xep-0045.html#invite
Seems one would have to check the type of room (members-only or not) and use
mediated invites if it really is members-only...?

**Comment by boothj5** [comment]
Implemented in master.

When joining a room, profanity will check the room settings:

- If the room config is not members only, direct invitations are used.
- if the room config is members only, mediated invitations are used.
- If the room does not respond to the disco info request (which is the case with google talk), mediated invitations are used.
