### ISSUE TITLE
[wishlist] Show chat names instead of window numbers in statusbar

### ISSUE THREAD

**Issue by tdi** [boothj5/profanity#416]
Now we have [1][2][][][][]

It would be great to see chat names (and possible window number)

```
  [1:ewa][2:james][3:dariusz][][][]
```

**Comment by JimPanic** [comment]
:+1: please :)

**Comment by ChrisMcKenzie** [comment]
It would be cool to have the ability to template this and choose what data to display

**Comment by jtdaugherty** [comment]
I would love this feature, too.  It could also be configurable via a format string so that you could get both the chat room names and window numbers (thus maintaining keyboard shortcut friendliness), e.g.,
```
[1:foo] [2:bar] ...
```
It's true that the width could get out of hand but I think trading off in favor of usability matters more.  (Remembering window ordering is brittle if it changes.)

**Comment by boothj5** [comment]
See linked issue regarding making the length of the names configurable too.

**Comment by boothj5** [comment]
Implemented in master.

There are now a number of options for displaying tabs in the status bar:

* Choose maximum number of tabs to display
    * Maximum 10, to match available keyboard shortcuts
    * Setting to 0 hides all tabs.
* Choose whether to show tab number
* Choose whether to show tab name
* Choose what to display as tab name
    * Chat windows: Defaults to nickname, can be overridden to show user name or jid
    * Chat room windows: Room name or jid
* Choose maximum size of tab name
    * Setting to 0 results in no maximum
* Choose what to show in status bar as logged in account
    * User name, bare jid, full jid, or nothing

All the above settings are also available in themes, see an [example](https://github.com/boothj5/profanity/blob/513a80c9505d99f5e9ace702daca13fc505db8a7/themes/boothj5#L145)

Command help:
```
Synopsis
/statusbar show name|number
/statusbar hide name|number
/statusbar maxtabs <value>
/statusbar tablen <value>
/statusbar self user|barejid|fulljid|off
/statusbar chat user|jid
/statusbar room room|jid
/statusbar up
/statusbar down

Description
Manage statusbar display preferences.

Arguments
maxtabs <value>           : Set the maximum number of tabs to display, <value> must be between 0 and 10
tablen <value>            : Set the maximum number of characters to show as the tab name, 0 sets to unlimited.
show|hide name            : Show or hide names in tabs.
show|hide number          : Show or hide numbers in tabs.
self user|barejid|fulljid : Show account user name, barejid, fulljid as status bar title.
self off                  : Disable showing self as status bar title.
chat user|jid             : Show users name, or the fulljid if no nick is present for chat tabs.
room room|jid             : Show room name, or the fulljid for room tabs.
up                        : Move the status bar up the screen.
down                      : Move the status bar down the screen.

Examples
/statusbar maxtabs 8
/statusbar tablen 5
/statusbar self user
/statusbar chat jid
/statusbar hide name
```
