### ISSUE TITLE
Navigate between words and beginning / end of line with keyboard

### ISSUE THREAD

**Issue by pesla** [boothj5/profanity#460]
I might have looked over it, but I seem to be unable to navigate between words and to the beginning or the end of a line with the keyboard (Terminal.app, OS X Yosemite).

For example, I'd expect <kbd>Option</kbd><kbd>←</kbd> and <kbd>Option</kbd><kbd>→</kbd> to move the cursor to the beginning of the previous/next word. Usually <kbd>Ctrl</kbd><kbd>A</kbd> and <kbd>Ctrl</kbd><kbd>E</kbd> are used for line beginning and end respectively.

Would it be possible to support these keybindings?

**Comment by boothj5** [comment]
Closing as I've started work on GNU readline integration and will keep #216 updated with progress.
