### ISSUE TITLE
I keep receiving this error!

### ISSUE THREAD

**Issue by reidcooper** [boothj5/profanity#467]
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/lib/libstrophe.0.dylib
  Reason: image not found
[1]    6567 trace trap  profanity

**Comment by jubalh** [comment]
Seems to me like an issue with OSX. Can we close this or is it still relevant?

**Comment by reidcooper** [comment]
Can close
