### ISSUE TITLE
Wide Unicode characters (including kanji and kana) break character deletion, navigation

### ISSUE THREAD

**Issue by andrewgho** [boothj5/profanity#473]
﻿Profanity does not seem to handle Unicode input correctly for wide characters. Details and steps to reproduce:

### Incorrect cursor placement in input line history ###

Copy and paste this text that includes two wide characters (in this case, Chinese characters) into a Profanity window:

    12三四56

If you entered it at the console, you see: `Unknown command: 12三四56`.

Press the up arrow to show the previous input line from history. The expected behavior is for the cursor to be positioned at the end of the line (to the right of the `6`). The actual observed behavior is that the cursor is incorrectly positioned at the `5`.

### Incorrect behavior when editing input line ###

Copy and paste text with wide characters (in this case, Hiragana) into a Profanity window:

    ひらがな

Press backspace to delete the `な`. The expected behavior is for the input line contents to become `ひらが` and for the cursor to be positioned at the end of the line (to the right of the `が`). The actual behavior is that the cursor moves to highlight the `な`, which is not deleted.

Pressing backspace additional times shows additional unexpected behavior (five backspaces leaves the cursor over the second kana, `ら`, and finally results in the deletion of `な`).

Cursor navigation (pressing left or right arrow to navigate through the line) show similar incorrect behavior.

## Environment

I can reproduce with both the most recent release (0.4.5) as well as against tip of tree. My environment is CentOS 6.5 (Linux 2.6.32-431.5.1.el6.x86_64), built against these library versions:

* curl-7.39.0
* glib-2.43.2
* libstrophe-0.8.7
* libxml2-2.9.2
* ncurses-5.7

My terminal is an OS X iTerminal with `LANG=en_US.UTF-8` and `LC_ALL=en_US.UTF-8`.

**Comment by boothj5** [comment]
I'm working on this now in a branch.  The history (up/down arrow) commands are now working, but there's a bit left to do for editing the input, window resizing etc.

Will keep this issue updated.

**Comment by boothj5** [comment]
Update:  I've managed to get the basics of GNU readline working in a branch which includes solving all command line editing with wide characters.

There is quite a bit more work to do, but the solution should be easier than manually handling input.  As a result I'm going to release 0.4.6 without a fix for this issue, and will focus on Readline for 0.4.7.

**Comment by boothj5** [comment]
The GNU Readline changes are now in master.  I've tested the above cases and seems to be working ok now.

Please reopen or raise another issue if you have any problems.
