### ISSUE TITLE
Input seems to bork on alarmpi

### ISSUE THREAD

**Issue by incertia** [boothj5/profanity#491]
I haven't done any extensive tests, but the input window wasn't responding on my raspberry pi running arch linux (got it in the mail like 40 minutes ago).

**Comment by boothj5** [comment]
Could be related to terminal encoding?

http://www.profanity.im/faq.html#utf8encoding

There's an open issue #248 to detect and fallback to non-wide ncurses for non-utf8 encodings.

**Comment by incertia** [comment]
Thanks. I thought most pre-install images would come with a valid `/etc/locale.conf`, but it seems as if the one I got did not.
