### ISSUE TITLE
Add option for 12-hour timestamp format (AM/PM)

### ISSUE THREAD

**Issue by arselinux** [boothj5/profanity#493]
This is a rather simple feature request, and it would be nice for users to be able to select a 12-hour format for timestamps both in the UI and in logs (something along the line of "hh:mm:ss AM/PM". Mentally converting times is easy enough, but it would be a nice addition for users in countries where the 24-hour format is almost never used (like the US).

**Comment by incertia** [comment]
Here is a suggestion. I'll implement it if you guys want. The timestamp format is given by a preference string that is fed to <code>strftime</code>, so controlling the output is fairly easy. e.g. "%H:%M:%S" for your standard 24 hour clock.

**Comment by boothj5** [comment]
Sounds like a good approach.  The only complexity might be in some of the output functions calculating the length of the time string, but probably not too problematic.

**Comment by incertia** [comment]
Done in #496

**Comment by boothj5** [comment]
Merged the pull request from @incertia into master. As mentioned, any format using the following should work:

https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format

E.g. for a non 12 hour clock time with seconds and AM/PM:

```
/time main "%I:%M:%S %p"
/time statusbar "%I:%M:%S %p"
```

```
10:23:04 AM
06:47:10 PM
```
