### ISSUE TITLE
Keychain access failing on OSX

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#495]
1) Add a password to the Keychain Access tool

2) Use the following value for the account `eval_password` property

```
security find-generic-password -s <Keychain Item Name> -w
```

The login fails due to the result of the above command containing a trailing newline character in the password.

**Comment by incertia** [comment]
why not just <code>echo -n $(security ...)</code>?

**Comment by boothj5** [comment]
As long as `/bin/echo` is used this should work.  But I imagine most people will try the `security` command after reading the man page, and not know why its not working. So getting profanity to strip the newline is just a bit more defensive and will probably avoid bug reports.

However, you have made me think that stripping whitespace is not the right solution since after testing I've noticed the Keychain allows leading trailing whitespace (but obviously not newlines).

I'll change the code to check for the trailing newline and remove it instead of trimming all whitespace, as I believe no password may contain a newline at the end.
