### ISSUE TITLE
install-all.sh breaks with .libs/libstrophe.ver:1: error: unrecognized file type

### ISSUE THREAD

**Issue by temmokan** [boothj5/profanity#499]
When trying to build on Ubuntu 14.04 (64-bit), the helper script fails:

libtool: link: /bin/grep -E -e "^xmpp_" ".libs/libstrophe.exp" > ".libs/libstrophe.expT"
libtool: link: mv -f ".libs/libstrophe.expT" ".libs/libstrophe.exp"
libtool: link: echo "{ global:" > .libs/libstrophe.ver
libtool: link:  cat .libs/libstrophe.exp | sed -e "s/\(.*\)/\1;/" >> .libs/libstrophe.ver
libtool: link:  echo "local: *; };" >> .libs/libstrophe.ver
libtool: link:  cc -shared  -DPIC  src/.libs/libstrophe_la-auth.o src/.libs/libstrophe_la-conn.o src/.libs/libstrophe_la-ctx.o src/.libs/libstrophe_la-event.o src/.libs/libstrophe_la-handler.o src/.libs/libstrophe_la-hash.o src/.libs/libstrophe_la-jid.o src/.libs/libstrophe_la-md5.o src/.libs/libstrophe_la-sasl.o src/.libs/libstrophe_la-scram.o src/.libs/libstrophe_la-sha1.o src/.libs/libstrophe_la-snprintf.o src/.libs/libstrophe_la-sock.o src/.libs/libstrophe_la-stanza.o src/.libs/libstrophe_la-thread.o src/.libs/libstrophe_la-tls_openssl.o src/.libs/libstrophe_la-util.o src/.libs/libstrophe_la-parser_expat.o   -lssl -lcrypto -lexpat -lresolv -lc    -soname libstrophe.so.0 -version-script .libs/libstrophe.ver -o .libs/libstrophe.so.0.0.0
tcc version 0.9.25
-> src/.libs/libstrophe_la-auth.o
-> src/.libs/libstrophe_la-conn.o
-> src/.libs/libstrophe_la-ctx.o
-> src/.libs/libstrophe_la-event.o
-> src/.libs/libstrophe_la-handler.o
-> src/.libs/libstrophe_la-hash.o
-> src/.libs/libstrophe_la-jid.o
-> src/.libs/libstrophe_la-md5.o
-> src/.libs/libstrophe_la-sasl.o
-> src/.libs/libstrophe_la-scram.o
-> src/.libs/libstrophe_la-sha1.o
-> src/.libs/libstrophe_la-snprintf.o
-> src/.libs/libstrophe_la-sock.o
-> src/.libs/libstrophe_la-stanza.o
-> src/.libs/libstrophe_la-thread.o
-> src/.libs/libstrophe_la-tls_openssl.o
-> src/.libs/libstrophe_la-util.o
-> src/.libs/libstrophe_la-parser_expat.o
-> .libs/libstrophe.ver
.libs/libstrophe.ver:1: error: unrecognized file type
make: *** [libstrophe.la] Error 1
Error 2 with command 'make' on line 79. Exiting.

with no obvious means to handle this.

**Comment by boothj5** [comment]
I've managed to install using the script on Ubuntu 14.04 and the latest release 0.4.6.

If you are able to try again using the download (from the website) let me know if you still see the problem.

**Comment by temmokan** [comment]
With latest source tree:

1. ./install-all.sh fails when it can't  find 'make'.

sudo apt-get install make -y

2. ./install-all.sh fails, since libstrophe directory sn't empty

rm -rf libstrophe

3. ./install-all.sh works fine and builds/installs profanity. 

Thanks!

**Comment by boothj5** [comment]
I'll close this issue, and add one to make the install script tidy up on fail.

Thanks.
