### ISSUE TITLE
Customisable keyboard shortcuts

### ISSUE THREAD

**Issue by donnm** [boothj5/profanity#505]
Somtimes you don't have an Alt modifier (e.g., N900) so it would be nice to be able to customise the keyboard shortcuts like irssi, especially those for changing windows. For now I'm getting by with /win 0-9.

**Comment by boothj5** [comment]
I've been working on GNU Readline integration which should make customising keyboard bindings much easier.

The plan is to include it in 0.4.7.

**Comment by boothj5** [comment]
I've merged the GNU Readline changes into master, you should be able to set your own custom keybindings for input editing.

`ESC` followed by a number should switch windows.

If you have any specific requests, feel free to open another issue.
