### ISSUE TITLE
ipv6 & jabber.org failure

### ISSUE THREAD

**Issue by quite** [boothj5/profanity#512]
I have an account on jabber.org. I set it up as usual, but when I try to connect it fails. My system is ipv6 enabled. In the log file I find, unfortunately only one relevant line:

  26/02/2015 23:23:11: xmpp: DBG: sock_connect to hermes2v6.jabber.org:5222 returned -1

I try telnet to said host and port, and that works fine over v6. I try setting the server for my account to "hermes2.jabber.org", and profanity then connects fine.

**Comment by boothj5** [comment]
This also explains #382 , when I use the server property as above, I can connect successfully also.

I believe this will require a change in the underlying XMPP library, so will try to recreate and raise an issue there.

**Comment by boothj5** [comment]
A pull request has been made at libstrophe which will probably solve this issue:

https://github.com/strophe/libstrophe/pull/63

**Comment by pasis** [comment]
Please, look at branch [strophe/libstrophe@ipv6](https://github.com/strophe/libstrophe/tree/ipv6). It has patch from strophe/libstrophe#63. Unfortunately, I can't test the patch with a IPv6-enabled system at the moment.

**Comment by boothj5** [comment]
@quite are you able to test this?  The patch for ipv6 support has been merged to libstrophe.  The changes have also been merged to libmesode if you're linking to it.

**Comment by quite** [comment]
Great, then I'm able to test it right away.

So, I don't remember which system I tried this on in the first place. But trying on one of them now, with the server property left out, and profanity is indeed able to log in my jabber.org account. Though, it chose IPv4. Setting the server property to {hermes2,hermes2v6}.jabber.org respectively also works fine, and the expected internet protocol is used.

I'd say IPv6 support is good to go.

**Comment by quite** [comment]
(I used mesode)

**Comment by boothj5** [comment]
Great, thanks for testing.
