### ISSUE TITLE
Timestamps in chat history are not converted to local time

### ISSUE THREAD

**Issue by Ephphatha** [boothj5/profanity#516]
12:40:38 - user_a: morning guys
 12:44:57 - user_b: Morning
 00:08:05 - user_a: how ya doing b?
 00:08:54 - user_c: morning b
 00:08:55 - user_c: no greeting for a though

My local timezone is UTC+11. The first two lines in that excerpt are from the chat history when I reconnected to the server/rejoined the channel and the last three were sent after I connected. The actual time elapsed between lines 2 and 3 was 57 seconds.

I'm running profanity 0.4.6 in cygwin x64 on Win 7 Pro. The server I am connecting to is hosted somewhere in the US (think it's UTC-7) so it's a bit of a mystery why the history timestamps seem to be some slight negative offset from UTC.

The logs got truncated before I could save the messages from when I joined the room, if necessary I can reconnect and try fix the logrotate settings.

**Comment by IS-smcleod** [comment]
I've run into the same issue by closing and reopening a chat.  The history when the chat is opened is suddenly off by 8 hours (I'm in PST).

This is for 0.4.6 on Arch Linux.

**Comment by boothj5** [comment]
This  should be fixed now in master if anyone is able to test.  Times should be in the current time zone for both MUC history and delayed delivery of 1-to-1 messages.

I've tested for UTC (offset 0) to BST (+1).

**Comment by IS-smcleod** [comment]
I'll play with it today but it looks good so far.

**Comment by boothj5** [comment]
Thanks.

**Comment by IS-smcleod** [comment]
Haven't noticed any issues.
