### ISSUE TITLE
Autojoining MUC's with large numbers of participants takes a long time

### ISSUE THREAD

**Issue by Ephphatha** [boothj5/profanity#517]
23:45:15 - Connecting with account host as ephphatha@host.com/dirac
 23:45:22 - ephphatha@host.com logged in successfully, online (priority 0).
 23:45:47 - Error joining room a@conference.host.com, reason: registration-required
 23:45:48 ! -> Autojoined b@conference.host.com as ephphatha (2).
 23:45:48 ! -> Autojoined c@conference.host.com as ephphatha (3).
 23:45:49 ! -> Autojoined d@conference.host.com as ephphatha (4).
 23:49:18 ! -> Autojoined e@conference.host.com as ephphatha (5).
 23:58:10 ! -> Autojoined f@conference.host.com as ephphatha (6).
 23:58:53 ! -> Autojoined g@conference.host.com as ephphatha (7).
 23:58:53 ! -> Autojoined h@conference.host.com as ephphatha (8).
 23:58:53 - Error joining room i@conference.host.com, reason: registration-required
 23:59:04 ! -> Autojoined j@conference.host.com as ephphatha (9).
 00:02:50 ! -> Autojoined k@conference.host.com as ephphatha (0).
 00:07:21 ! -> Autojoined l@conference.host.com as ephphatha (11).

Rooms b, c, d, h each have ~15 participants, the rest have 100+ participants connected. While watching the logs I can see a whole bunch of "Room presence received from room@conference.host.com/user" messages and once it's gone through the user list it prints the "Autojoined room@conference.host.com as ephphatha" message before starting on the next room. If I change the active window in profanity it will finish connecting to the current room as usual but then will not progress any further with the autojoin list. If I manually tell profanity to connect to a bookmarked room it completes almost instantly.

Unfortunately the log rotation settings appear to be misconfigured on my install so the messages from when I connected to the server and let profanity go through the autojoin list have been overwritten.

I'm running profanity 0.4.6 on cygwin x64 and Win 7 Pro.

**Comment by boothj5** [comment]
The time taken to join a room has been improves significantly (in master), from minutes to milliseconds (a room with ~100 participants) on my machine.  I'll close this issue, but if you still have problems, please raise them.
