### ISSUE TITLE
Chinese characters sometimes cause message to blink

### ISSUE THREAD

**Issue by moorchegue** [boothj5/profanity#523]
Just got an update from 0.4.5-2 to 0.4.6-1 in my Arch and got some messages containing Simplified Chinese characters blink (more accurately message background is blinking) and have some artifacts. Makes them nearly impossible to read.

Example of the message doesn't blink:
22:31:57 - 国外的xarp。

Examples of messages does blink:                                                             
22:31:57 - 国内的风云防火墙、彩影防火墙、360网络防火墙、360安[39;49└                
           ¨卫士里的ARP防火墙。                                                     
00:04:08 - ***@***/mobile: 一根头发、一束头发、一缕头发、一[39;49└at?       
           ®头发、一把头发、一头白发                                                
00:04:08 - ***@***/mobile: 一根头发、一束头发、一缕头发、一[39;49└          
           ®头发、一把头发、一头白发e) is online                                    

Those messages were sent by Android Conversations client and some of them include android Unicode smileys which I can't see in Profanity, but they alone don't cause any blinking.

Let me know if any screenshots or any other details are needed.

P.S. Also entering Chinese is sucky (you see spaces in place of a characters until you send a message), but it's a different story and is not related to this version, I believe.

**Comment by boothj5** [comment]
I can recreate some of this behaviour using 0.4.6.

Changes have been added in master to use GNU Readline, which should remove some issues like the above.

If you are able to build latest, I'd be interested to hear if you still see the problems.

**Comment by moorchegue** [comment]
Yep, I don't see those anymore, awesome!
