### ISSUE TITLE
Fail better on broken connection 

### ISSUE THREAD

**Issue by j6k4m8** [boothj5/profanity#525]
I frequently use profanity for my Facebook chat in airports or on planes (where bandwidth is a big factor), and though *I maintain a connection to the WiFi router*, the session 'times out' or we lose a connection to the towers. 

As far as I can tell, profanity doesn't even notice: The only way I can tell I've irretrievably lost a connection is that my friend conspicuously stops responding.

I'd love to see a big bold red **"Connection lost."** message in the chat rooms — or perhaps this already exists and I'm simply misusing the software...

**Comment by boothj5** [comment]
I've seen a similar thing on networks (including wired) when the connection drops. A dropped network connection doesn't end the XMPP stream.  I also tried handling a SIGPIPE but this didn't help either.

I think perhaps the best solution is to add a user preference timeout to server ping requests, after which if no response is received the connection should be considered broken and inform the user etc.

I'll take a look at this and keep this issue updated.

**Comment by osleg** [comment]
Isn't this what autoping made for?

**Comment by PMaynard** [comment]
I experienced the same issue, I enabled autoping and autoconnect since then everything works flawless.

**Comment by j6k4m8** [comment]
Confirmed — closing :)
