### ISSUE TITLE
Profanity hangs, 100% CPU load after /connect

### ISSUE THREAD

**Issue by seamus-45** [boothj5/profanity#529]
As described in issue #378. With profanity-0.4.5 all is fine, but 0.4.6 hangs (100% CPU, interface almost frozen) and I got a random disconnects.

Software | Version
------------|-----------
Gentoo Linux | 3.18.9
Openfire | 3.9.1
profanity | 0.4.6 
libstrophe | 0.8.7

profanity.log: https://gist.github.com/seamus-45/92b97b02f9cf53871a87

**Comment by boothj5** [comment]
Does the 100% usage eventually go down, or continue until the disconnect?

I notice the connection appears to be successful, then you receive a lot of presence stanzas, if it happens again, you could check to see if the send error is always related to the same contact:

https://gist.github.com/seamus-45/92b97b02f9cf53871a87#file-profanity-log-L296

**Comment by seamus-45** [comment]
I think that disconnects - this is not the cause but the consequence. I ran another test, and this time I recorded a [little video](https://drive.google.com/file/d/0B3Q_TrWZ0ZtWWjI1X0w4MXhhR1k/view?usp=sharing). I hope the picture becomes clearer.

**Comment by devhell** [comment]
@seamus-45 Is this still the case? I cannot replicate this for the life of me.

**Comment by seamus-45** [comment]
With fresh install from git the problem is gone.
