### ISSUE TITLE
Allow configuring message carbons before logging in

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#532]
Currently `You are not currently connected` is shown if not logged in when using:

```
/carbons on|off
```

Allow the preference to be set without logging in first

**Comment by PMaynard** [comment]
I recommend that this issue be closed, as I've been able to enable and disable carbons when not connected to a network. Using Version 0.4.7dev.master.304e08al; Ubuntu 14.04.2 LTS.

**Comment by boothj5** [comment]
Closed, fixed with #545
