### ISSUE TITLE
Error connecting to pvp.net (legacy SSL)

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#536]
Problems have been reported trying to connect to the pvp.net chat network.  The settings are used as below, connecting to the US server using the IP address as the altdomain.

Other clients reportedly connect successfully using the same settings.

The error in the log is as follows:

```
29/03/2015 21:18:44: xmpp: DBG: Connecting via altdomain.
29/03/2015 21:18:44: xmpp: DBG: sock_connect to 192.64.174.69:5223 returned 4
29/03/2015 21:18:44: xmpp: DBG: attempting to connect to 192.64.174.69
29/03/2015 21:18:44: xmpp: DBG: connection successful
29/03/2015 21:18:44: conn: DBG: SENT: <?xml version="1.0"?><stream:stream to="pvp.net" xml:lang="en" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">
29/03/2015 21:18:44: xmpp: DBG: Socket closed by remote host.
29/03/2015 21:18:44: xmpp: DBG: Closing socket.
29/03/2015 21:18:44: prof: DBG: Connection handler: XMPP_CONN_DISCONNECT
29/03/2015 21:18:44: prof: DBG: Connection handler: Login failed
```

![pvp](https://cloud.githubusercontent.com/assets/543885/6927978/e406673e-d7e8-11e4-9343-cc44f565f6f3.png)

**Comment by pasis** [comment]
Any chance to see xml console output from other client that works? If server doesn't accept `stream` stanza this is libstrophe's issue.

**Comment by pasis** [comment]
Try with the latest libstrophe code. Maybe strophe/libstrophe@b2a98fb9b6630b893f414d6d522b12716c9a2a2a fixes the problem. In theory, old code could send first message before tcp connection is established. This is because socket had flag O_NONBLOCK and libstrophe considered that connection is established even when connect() returned EINPROGRESS.

I experienced this problem with gmail account few times when was redirected to a server that answered too slowly.

**Comment by pasis** [comment]
My previous post is wrong, libstrophe handles asynchronous connection in src/event.c. Even with synchronous connection I still have problems with alt1.xmpp.l.google.com (other servers work fine). The problem looks like recv() returns ECONNRESET in short time after sending 1st message to the server. And libstrophe just prints `Socket closed by remote host.`

**Comment by pasis** [comment]
I made it work (auth error is ok, I don't have account):
```
xmpp DEBUG Connecting via altdomain.
xmpp DEBUG sock_connect to chat.euw1.lol.riotgames.com:5223 returned 3
xmpp DEBUG attempting to connect to chat.euw1.lol.riotgames.com
xmpp DEBUG connection successful
xmpp DEBUG TLS success
conn DEBUG SENT: <?xml version="1.0"?><stream:stream to="pvp.net" xml:lang="en" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">
xmpp DEBUG RECV: <stream:stream id='4161038029' from='pvp.net' version='1.0'>
xmpp DEBUG RECV: <features xmlns="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>X-Riot-Vapor</mechanism></mechanisms></features>
conn DEBUG SENT: <auth mechanism="PLAIN" xmlns="urn:ietf:params:xml:ns:xmpp-sasl">AGV4YW1wbGUAZXhhbXBsZQ==</auth>
xmpp DEBUG RECV: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure>
xmpp DEBUG SASL PLAIN auth failed
auth ERROR Cannot authenticate without resource
conn DEBUG SENT: </stream:stream>
xmpp DEBUG RECV: </stream:stream>
xmpp DEBUG Closing socket.
DEBUG: disconnected
event DEBUG Stopping event loop.
event DEBUG Event loop completed.
```
libstrophe needs implementation of the "old-style ssl". I'll work on this.

**Comment by pasis** [comment]
Old style SSL is in master: strophe/libstrophe@36af7afa274cfea438768cafd02d675f64c01237
Current implementation provides new API xmpp_conn_set_old_style_ssl() and needs some modification of profanity (option for forcing old ssl, using new function).

Also you can check if it works in this way:
```
$ ./examples/basic --old-ssl example@pvp.net examplepwd chat.euw1.lol.riotgames.com
```

**Comment by boothj5** [comment]
Closing due to the fix in libstrophe

**Comment by pjriot** [comment]
Hi boothj5 - just wondering if this option is exposed in profanity somehow? I've hardcoded it in master and it works perfectly but I don't see it used other than that.

**Comment by boothj5** [comment]
Not sure why I closed this issue, my mistake.

Reopening, do you have the hard coded example? Might help with adding an option.

Thanks.

**Comment by pjriot** [comment]
Doubtful - its a hack, I'm only using this for one account:

`diff --git a/src/xmpp/connection.c b/src/xmpp/connection.c
index 2c74f1e..8cb5ca7 100644
--- a/src/xmpp/connection.c
+++ b/src/xmpp/connection.c
@@ -148,11 +148,7 @@ connection_connect(const char *const jid, const char *const passwd, const char *
     xmpp_conn_set_jid(conn.xmpp_conn, jid);
     xmpp_conn_set_pass(conn.xmpp_conn, passwd);
 
-    if (!tls_policy || (g_strcmp0(tls_policy, "force") == 0)) {
-        xmpp_conn_set_flags(conn.xmpp_conn, XMPP_CONN_FLAG_MANDATORY_TLS);
-    } else if (g_strcmp0(tls_policy, "disable") == 0) {
-        xmpp_conn_set_flags(conn.xmpp_conn, XMPP_CONN_FLAG_DISABLE_TLS);
-    }
+    xmpp_conn_set_flags(conn.xmpp_conn, XMPP_CONN_FLAG_LEGACY_SSL);
 
 #ifdef HAVE_LIBMESODE
     char *cert_path = prefs_get_tls_certpath();
`

**Comment by boothj5** [comment]
Still helpful thanks, I think I''ll just need to add an account option.

**Comment by pjriot** [comment]
Fantastic! Thanks a lot!

**Comment by mrsdizzie** [comment]
Would also love to see this feature as I need to connect to a server that only supports this type of SSL connection. Happy to test any changes

**Comment by pasis** [comment]
I'll implement `legacy` tls policy, so you will be able to run `/tls legacy`, `/connect ... tls legacy`, etc. But I can't actually check it, because have no account on such a server.

**Comment by pasis** [comment]
@mrsdizzie, I opened pull request for this feature: https://github.com/boothj5/profanity/pull/944.

**Comment by pasis** [comment]
Note, server's certificate issued for `chat.euw1.lol.riotgames.com`:
```
/C=US/ST=California/L=Los Angeles/O=Riot Games, Inc./OU=Production OPS/CN=chat.euw1.lol.riotgames.com
```
Recent libstrophe code started verifying certificates and it performs hostname verification (openssl-1.0.2 and later) using `pvp.net` as hostname. Therefore, tls handshake fails now with recent libstrophe and openssl-1.0.2.

**Comment by pasis** [comment]
After some reading, it looks like the server's fault. [https://tools.ietf.org/html/rfc6120](rfc6120) says (5.4.3.1. and 13.7.2.1.) that server identity is the domain used in opening stream. So, this is `pvp.net` in our case. If you use recent libstrophe and openssl-1.0.2, you will need to trust this certificate in some way in order to connect to the server.

**Comment by pasis** [comment]
Riot Games has blocked 3rd party applications from their chat. See [response on reddit](https://www.reddit.com/r/leagueoflegends/comments/2vojmd/riots_new_stance_on_chat_applications_will_make/cojpi68/). Therefore, Profanity/libstrophe can't access pvp.net servers anymore.
