### ISSUE TITLE
Roster changes not reflected in the roster panel immediately

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#537]
When the roster panel is visible, changing a nickname in the roster with:

```
/roster nick contact new_nick
````

Does not update the panel.

**Comment by longk15t** [comment]
I also got this in 0.4.7, when I try to add a new contact, the roster panel didn't update, but it also didn't update when I /disconnect and reconnect my account again.

**Comment by boothj5** [comment]
Should be fixed now in master.
