### ISSUE TITLE
Readline implementation catches mouseevents?

### ISSUE THREAD

**Issue by demonking** [boothj5/profanity#538]
I don't know if it's only on my FreeBSD 10.1 but since 0.4.7 where readline was
implemented, the input catches all mouse events with 

`/mouse on`

I haven't a linux machine around to test it on a Linux Distro

**Comment by PMaynard** [comment]
I have mouse handling disabled but it allows me to use my mouse wheel to scroll my message history.
Should this be disabled? 

Profanity version 0.4.7dev.master.adae6bb; Ubuntu 14.04.2 LTS;

**Comment by boothj5** [comment]
Agreed, the mouse shouldn't affect the input this way, will look into a fix.

Thanks,

**Comment by boothj5** [comment]
After some effort, I'm struggling to get the mouse integration working well with GNU Readline.

I think for the 0.4.7 release, the /mouse preference will be removed (it was experimental anyway as mentioned in the help, and had some issues).

As for the input window scrolling through history, this seems to be terminal specific, gnome-terminal for example jumps a number of entries depending on the gnome-terminal version, XTerm scrolls the whole terminal up and down.  After going through previous release, this was the same in 0.4.6 and 0.4.5.

I've added an issue to implement mouse handling correctly #594
