### ISSUE TITLE
No input accepted by profanity

### ISSUE THREAD

**Issue by ivucica** [boothj5/profanity#540]
Cheers,

I'm logging into my Debian machine from ChromeOS's SecureSSH. Both inside `tmux` (`TERM=screen`) and running directly (`TERM=xterm-256color`), Profanity is completely unresponsive to any input once started, and I need to kill it with `killall`.

This is with Debian packages in `jessie` and in `sid`: 0.4.4 and 0.4.6, respectively.

I can enter my password if I pass `-a jid@here.now` and it actually logs in -- except keyboard input it still ignored. So I guess it's *just* the keyboard input that's being ignored.

If there's some quick additional information I can produce, or if Debian packaging is old enough that it's worth it to build the program from source, let me know and I'll spend a bit of time trying to do just that.

Thank you for your work!

**Comment by boothj5** [comment]
It's possible related to the encoding: http://www.profanity.im/faq.html#utf8encoding

There's an open issue to support non UTF8 environments #248 , in the meantime I'm going to add the FAQ to the homepage so its a bit easier to find.

Let me know if this solves it.

**Comment by boothj5** [comment]
Assuming this was due to encoding.
