### ISSUE TITLE
Window cannot be resized while password prompt is shown

### ISSUE THREAD

**Issue by 2ion** [boothj5/profanity#544]
In v0.4.6, when initiating a login with
```
/connect $account
```
and resizing the terminal while the subsequent password prompt is on display,

* the login fails;
* the lower status bar disappears when resizing vertically;
* input will not longer be echoed to the input line, the cursor is displaced.

Window here refers to either a X11 terminal emulator's window or a terminal multiplexer's panes/partitions.

**Comment by demonking** [comment]
i have tested it with urxvt as terminal and fish-shell.
With tmux i have resized the window with prefix alt+right(arrow key)

And it's like 2ion is saying

**Comment by boothj5** [comment]
With the move to GNU Readline in master, this problem should now be fixed. I've tested locally, but if you also have time to test, let me know your findings.

**Comment by PMaynard** [comment]
Can confirm the bug and patch works.

**Comment by 2ion** [comment]
Yes, the issue seems to be fixed in the git version. Closing this then.
