### ISSUE TITLE
Key combination [shift]+[backspace] does not backspace

### ISSUE THREAD

**Issue by lordastley** [boothj5/profanity#548]
Expected behaviour: When typing, holding [shift] and pressing [backspace] will backspace over any entered characters.

Actual behaviour: When typing, holding [shift] and pressing [backspace] does not backspace.

Because it might matter, profanity is being executed in screen 4.02.01 (GNU) 28-Apr-14 from a putty window.

I'm on Version 0.4.6, from the the Debian testing repositories.

profanity -v output:

Profanity, version 0.4.6
Copyright (C) 2012 - 2015 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
Desktop notification support: Enabled
OTR support: Enabled

**Comment by lordastley** [comment]
I just built the latest git master, Version 0.4.7dev.master.adae6bb.

The issue is not present in this version, however I built without OTR or desktop notification support.

**Comment by boothj5** [comment]
This will have been fixed by the change to use GNU Readline in master.  I can confirm this with OTR and desktop notifications enabled.

I'll close this issue, but please reopen if you find and issue with the latest source.

**Comment by MarcoPolo-PasTonMolo** [comment]
I have this problem, and backspacing does not work if you have Caps Lock on as well
