### ISSUE TITLE
Autoaway check not working

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#554]
Master branch.

Reportedly, with mode = away, and check = on, running in a tmux environment, using the profanity fallback for detecting autoaway, whilst the autoaway works, the check does not.  Typing does not set the status back to what it was before.

**Comment by quite** [comment]
works in 304e08a9c0bfa27ed84dc1ff0a2e2d32b36529f8

**Comment by boothj5** [comment]
I've tried with latest code in master using:

```
./configure --without-xscreensaver
```

and the following settings:
```
Autoaway (/autoaway mode)            : away
Autoaway minutes (/autoaway time)    : 1 minutes
Autoaway message (/autoaway message) : OFF
Autoaway check (/autoaway check)     : ON
```

And the check seems to work, setting my presence back to `online` after a key press.

Sounds like this is to do with running in a tmux session.  If you can verify this also works for you without tmux, I'll update the title of this issue.

**Comment by quite** [comment]
After a restart of profanity, it now works. Again. What gives? Close-y-o...

**Comment by boothj5** [comment]
Ok, I'll close for now, if you manage to recreate, open the issue again and I'll try to investigate further.
