### ISSUE TITLE
Run Profanity commands from a file

### ISSUE THREAD

**Issue by longk15t** [boothj5/profanity#556]
Can profanity run commands from a file ? I want to save some profanity commands into a file (no idea which format it should be) then I'm able to run those commands by run the file without typing them again.

**Comment by boothj5** [comment]
This feature doesn't exist at the moment, there is an open issue #381 to allow aliasing of a list of commands.  I'll close this issue as it would implement the same functionality, feel free to add any comments/suggestions to #381.

Thanks.

**Comment by boothj5** [comment]
The basics for this have been implemented, see #381
