### ISSUE TITLE
Empty the roster list (delete all contacts)

### ISSUE THREAD

**Issue by longk15t** [boothj5/profanity#559]
Is this possible ? Any commands for that ?

**Comment by longk15t** [comment]
@boothj5  please reply this.

**Comment by boothj5** [comment]
I've just added the extra command (in master):

```
/roster empty
```

**Comment by longk15t** [comment]
thanks for the extra commands :+1:  BTW, when is 0.4.7 released ?

**Comment by boothj5** [comment]
I've reduced the number of issues associated with the 0.4.7 milestone: https://github.com/boothj5/profanity/milestones/0.4.7

The only major feature left is OpenPGP encryption, which is almost finished in a branch. Other than that the remaining issues are smaller bugs/improvements.

I can't guarantee when the release will be out, depends on my free time, but I'm hoping in a month or two.
