### ISSUE TITLE
Password is shown during typing (0.4.7)

### ISSUE THREAD

**Issue by pasis** [boothj5/profanity#564]
When I type password after `/connect` it appears for short time and then disappears. Not reproducible for 0.4.6.

It can be a problem for someone who shares their screen during typing.

**Comment by longk15t** [comment]
The current behavior is partially safe for user, but also make them difficult to know what they typed. 
I think we should show "*" for each password character. No need to handle "Hide" behavior.

@pasis how can you test 0.4.7 btw ?

**Comment by PMaynard** [comment]
Personally I'd be happier to keep the key presses hidden, it stops people knowing the length of your password . Its a long standing practice on command line based applications. 

I'm assuming the current master branch is classed as version 0.4.7.

**Comment by pasis** [comment]
I agree with @PMaynard, interface should be predictable and hiding password is something I used to see in *nix console programs. And yes, under 0.4.7 I meant current master branch.

**Comment by boothj5** [comment]
Whilst some applications use `*`'s to hide password entry, the `sudo` command etc tend to stick with not showing any indicators, so I think profanity should probably stick to the same convention.

However, when its a matter of personal preference, I'm always happy to add a configuration option...

As for the bug itself, I'm having problems recreating consistently, it's obviously related to the GNU Readline changes, and I have seen the password very briefly appear, I'll look into it further.

**Comment by boothj5** [comment]
Made a change which might have fixed this, but can't easily recreate so let me know if it makes a difference for you.

**Comment by pasis** [comment]
It works for me.

Also I found, that _inp_write() is called for every character. Shouldn't it be something like this?
```
diff --git a/src/ui/inputwin.c b/src/ui/inputwin.c
index 2c42a62..12cdacc 100644
--- a/src/ui/inputwin.c
+++ b/src/ui/inputwin.c
@@ -162,7 +162,8 @@ inp_readline(void)
         }
 
         ui_reset_idle_time();
-        _inp_write(rl_line_buffer, rl_point);
+        if (!get_password)
+            _inp_write(rl_line_buffer, rl_point);
         inp_nonblocking(TRUE);
     } else {
         inp_nonblocking(FALSE);
```

**Comment by boothj5** [comment]
Added the above change.
