### ISSUE TITLE
Syntax Error in bootstrap  || configure

### ISSUE THREAD

**Issue by PMaynard** [boothj5/profanity#572]
Fresh clone from master and plugins branch yields the same results. 

*$ ./bootstrap.sh*

	autoreconf: Entering directory `.'
	autoreconf: configure.ac: not using Gettext
	autoreconf: running: aclocal --force 
	aclocal: warning: couldn't open directory 'm4': No such file or directory
	autoreconf: configure.ac: tracing
	autoreconf: configure.ac: creating directory build-aux
	autoreconf: running: libtoolize --copy --force
	libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
	libtoolize: copying file `build-aux/ltmain.sh'
	libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
	libtoolize: copying file `m4/libtool.m4'
	libtoolize: copying file `m4/ltoptions.m4'
	libtoolize: copying file `m4/ltsugar.m4'
	libtoolize: copying file `m4/ltversion.m4'
	libtoolize: copying file `m4/lt~obsolete.m4'
	libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
	autoreconf: running: /usr/bin/autoconf --force
	autoreconf: running: /usr/bin/autoheader --force
	autoreconf: running: automake --add-missing --copy --force-missing
	configure.ac:13: installing 'build-aux/compile'
	configure.ac:14: installing 'build-aux/config.guess'
	configure.ac:14: installing 'build-aux/config.sub'
	configure.ac:9: installing 'build-aux/install-sh'
	configure.ac:9: installing 'build-aux/missing'
	Makefile.am: installing 'build-aux/depcomp'
	parallel-tests: installing 'build-aux/test-driver'
	autoreconf: Leaving directory `.'

*$ ./configure*

	checking for a BSD-compatible install... /usr/bin/install -c
	checking whether build environment is sane... yes
	checking for a thread-safe mkdir -p... /bin/mkdir -p
	checking for gawk... gawk
	checking whether make sets $(MAKE)... yes
	checking whether make supports nested variables... yes
	./configure: line 2951: syntax error near unexpected token `src/prof_config.h,'
	./configure: line 2951: `AX_PREFIX_CONFIG_H(src/prof_config.h, PROF, src/config.h)'

**Comment by pasis** [comment]
Indeed, plugins branch fails because of missing ax_prefix_config_h.m4. But if I download this file manually to m4/ directory ./configure works fine. I found link to the file on this page: http://www.gnu.org/software/autoconf-archive/ax_prefix_config_h.html

Master branch can't produce this error, because there is no AX_PREFIX_CONFIG_H() there.

**Comment by PMaynard** [comment]
Ah okay, I must have mixed up my directory with some code from the plugin branch. 

*/me gets out git's man page*

**Comment by lordastley** [comment]
As of commit https://github.com/boothj5/profanity/commit/41fe8c22b1f8c1cf666d42052cd73d59e40a2ed2, this issue is present on the master branch

**Comment by boothj5** [comment]
Two additional dependencies are needed:

```
libtool
autoconf-archive
```

The second should fix the issue.
