### ISSUE TITLE
PGP One way encryption when missing JID

### ISSUE THREAD

**Issue by PMaynard** [boothj5/profanity#578]
When the user signs their presence, but does not have a matching JID to GPG ID. Profanity does not encrypt messages to the user or warn the operator that the chat is only encrypted one direction.

In this example the user another_user@matrix.ac is using mcabber and has set a public key for osaka@matrix.

Received a signed presence:

        11:50 - RECV:
        11:50 - <presence id="133274631" to="osaka@matrix.ac/work" from="another_user@matrix.ac/computer"> <show>away</show>
                 <status/>
                 <c hash="sha-1" xmlns="http://jabber.org/protocol/caps" node="http://mcabber.com/caps" 
                ver="LpRr3y+w/XIIA9xtFb+oWORX0YA="/>
                 <x xmlns="jabber:x:signed">iQEcBAABCAAGBQJViot5AAoJELauSSYXlOfHUwUIAMeAF/jVp1bECu4nmP5aCk8U
                QZxi+cxIMrC8cOK9yZyo/ngO+e99pJ/3oKRsEoYx4DgUcJC5MiS3ZzvjK8+BkxVL
                tSF4CUsPiCgzJQNO6eWRPT4hN6u90aBXtV7v36cUIwEdf62q6NwrWyCSYjqmo0Xy
                Wm7G53sKD6EYbNRuZ2f/iCkeCt1/R0t6+tEBVjr+BgooNnEBC4V11W7h0QHIY0ll
                ir0u+TNgY4fNUKze44MfWgi9S/JlTV3lewodKESdp53yoPqmXXBIsNHOUtJUzpTL
                PZ2YpvMXPTyaaXUr0Rz7TAgDg7mNghVz1KwhscMMyr+q1++LdQBXJfirLCuoHHY=
                =e+RQ</x>
                </presence>

And we can receive PGP encrypted messages: 

        11:51 - RECV:
        11:51 - <message id="133511466246" type="chat" to="osaka@matrix.ac" from="another_user@matrix.ac/computer"> <body>This message 
                is PGP-encrypted.</body>
                 <x xmlns="jabber:x:encrypted">hQEMA0GLCMsBcN+NAQf9EMA4OeiH9a2+f1+Vy32ecjVDNjkd2kAShFSiKaX4jshz
                HI2hppszbUdd9NMEeK64YDFOkMyVfwqok3jSQ37DtguRYq1IlqiIL7FGhA6D9hrV
                XAmjwxrXin7cEh/JUfyGg3xUq77zFulVmJjLJrQAi0dyuPeOxv0MgmndL8eE0NiZ
                15RfrGMbenhd7ZbqYm7WwK7DNtn2Fq7k5TQHzUv/b+REkJb42PBz3Um3mBZrrP0K
                RGw2vqrwImgbOWhI3SJxiAoTcQkbZbD+dU0cIGm7KExAQOdZLGU8xwSI+tNs/YBq
                wOTqhmfR9+hVw7fWYiIleu4N1k6lYjo5TAEBSEAOgNJRAdhDQR2nkn3xUqPf9UC9
                KOE2PZ+3tGLsGLIYq+1CfBC4qdaOg5/IXn8amWqsvo8egmV7vGw17Tcd4mlPZjEu
                1TiyYs0OHRdeUyGgZ37ASn0g
                =5i9Q</x>
                </message>

But any message to this client is in plain text.

Sent with PGP disabled:

        <message id="prof_msg_41" to="another_user@matrix.ac/computer" type="chat"><body>hello plaintext</body></message>

Sent with PGP enabled and the titlebar shows [PGP]:

        <message id="prof_msg_42" to="another_user@matrix.ac/computer" type="chat"><body>hello PGP</body><private 
        xmlns="urn:xmpp:carbons:2"/></message>

A PGP Fingerprint is recorded and checked with ```/pgp fps```.

Profanity, version 0.4.7dev.master.815ca16

**Comment by PMaynard** [comment]
The key was not found in my keyring. Not a bug. 

Maybe there could be a warning to the user if the message not able to be encrypted.

**Comment by boothj5** [comment]
When attempting to send a PGP message, you should see the following if you don't have a PGP key set up for your account:

```
You must specify a PGP key ID for this account to start PGP encryption.
```

If you have a key but no key associated with the contact, the following should appear:

```
No PGP key found for <contact>.
```

I'll close this issue, but let me know if you have any problems.
