### ISSUE TITLE
Cannot run Profanity (0.4.7) on Cygwin Terminal

### ISSUE THREAD

**Issue by longk15t** [boothj5/profanity#579]
After install Profanity 0.4.7 (downloaded profanity-master.zip) by Cygwin terminal on Windows 8.1, I saw something on last lines in terminal 
![c3662bbc-1a51-11e5-86ad-b933e839f87e](https://cloud.githubusercontent.com/assets/6722910/8329390/5090c0be-1aa3-11e5-9a0d-83c3b2ad1010.png)

Then I try to type 'profanity', it show "-bash: profanity: command not found"

**Comment by boothj5** [comment]
I think the issue is when you download a zip rather than cloning the repository.

Development builds require the git repository to be present so they can show the build number.

A quick hack might be to change "development" to "release" here https://github.com/boothj5/profanity/blob/master/configure.ac#L26 and try again.

**Comment by longk15t** [comment]
Thanks, bro. Now I can use profanity 0.4.7, I'm ready to test its checklist ! Would you mind to close this issue ? Sorry for annoying.
(Actually, if you don't mind, can you explain me how to clone the repository ? I can't clone a repository without create a fork. Did I miss something ? If you don't want me mess up anything here, we can discuss via gmail)

**Comment by boothj5** [comment]
No need to apologise, your testing is very helpful. Also I'm happy for you to ask questions here.

You can clone the repo directly directly to your machine using:

```
git clone https://github.com/boothj5/profanity.git
```

This is fine for testing etc, and whenever changes are made, you can get latest with:

```
git pull
```

You'll only need to fork on github if you want to make changes and submit a pull request.
