### ISSUE TITLE
Export roster list to txt/csv file

### ISSUE THREAD

**Issue by longk15t** [boothj5/profanity#585]
@boothj5 could we do this on 0.4.7 ? I'm very appreciate about it.

**Comment by incertia** [comment]
what sorts of fields are you looking for in the file? it shouldn't be too hard to export a list of emails with some extra data.

**Comment by longk15t** [comment]
just emails, no need other information. I really need this feature.

**Comment by boothj5** [comment]
Added in #680 from @incertia
