### ISSUE TITLE
Timestamp says "minutes" not the actual time.

### ISSUE THREAD

**Issue by PMaynard** [boothj5/profanity#588]
![prof-bug](https://cloud.githubusercontent.com/assets/1450006/8473581/ad6f7fe6-20a2-11e5-8959-818b6e2c6d75.png)

Had to run ```/time main set %H:%M``` to fix.

This was compiled from a make clean, version 0.4.7dev.master.84a8da7

**Comment by boothj5** [comment]
This is due to a recent change.  It wont affect new users, but I'll add a fix to migrate the old settings format on startup for existing users.

**Comment by boothj5** [comment]
Should be fixed now in master.

When starting profanity with config using the old values: `minutes` will be converted to `%H:%M`, `seconds` to `%H:%M:%S` and `off` to empty string.
