### ISSUE TITLE
installation through brew (osx) does not work

### ISSUE THREAD

**Issue by kotyamba** [boothj5/profanity#602]
brew install profanity
==> Installing dependencies for profanity: check, libstrophe, gettext, libtasn1, gmp, nettle, gnutls, libgpg-error, libgcrypt, libotr
==> Installing profanity dependency: check
==> Downloading https://downloads.sourceforge.net/project/check/check/0.9.14/check-0.9.14.tar.gz
Already downloaded: /Library/Caches/Homebrew/check-0.9.14.tar.gz
Error: SHA256 mismatch
Expected: c272624645b1b738cf57fd5d81a3e4d9b722b99d6133ee3f3c4007d4d279840a
Actual: 9954a5d14686244d61f292b9ed4d20cdc4e837f56dc27c19229a109b582aa36a
Archive: /Library/Caches/Homebrew/check-0.9.14.tar.gz

**Comment by boothj5** [comment]
This looks more like a problem with the brew `check` package. It looks like you already have `check` installed but the hash doesn't match what is expected:

```
Already downloaded: /Library/Caches/Homebrew/check-0.9.14.tar.gz
Error: SHA256 mismatch
```

I'm no brew expert, is it possible to force a download of `check`, perhaps removing and reinstalling it? If not I think this issue should probably be raised at homebrew.

**Comment by kotyamba** [comment]
I found the cause. It was because I have not access to sourceforge.net. VPN helped me.
