### ISSUE TITLE
Profanity fails to run on Arch

### ISSUE THREAD

**Issue by nerd** [boothj5/profanity#603]
Error messages:
`(profanity:15765): GLib-CRITICAL **: interval_offset: assertion 'tz->t_info != NULL' failed`
`(profanity:28216): GLib-CRITICAL **: init_zone_from_iana_info: assertion 'size >= sizeof (struct tzhead) && memcmp (header, "TZif", 4) == 0' failed`
My console gets spammed with this and does not respond. I end up having to kill the process.

Installed from the source tarball, the git version from AUR, and the official repository. All yield the same result.

**Comment by demonking** [comment]
Which Version do you use?

**Comment by incertia** [comment]
profanity works for me on kernel 3.18.6-1 (x86_64). it was also working a week ago on the latest kernel.

are your libraries up to date?

**Comment by knobody** [comment]
@incertia it says on the install page that the ./configure script won't run if it can't find minimum dependencies, and it never failed when I manually installed profanity.

**Comment by demonking** [comment]
@knobody if your unsure , copy the content of 
`uname -a`

I'm installing a arch box and will test, if i could reproduce the error

**Comment by incertia** [comment]
i did a bit of searching, and it seems like you might have not properly configured a timezone. can you check if `/etc/localtime` is properly linked to a file in `/usr/share/zoneinfo/`?

the problem may have something to do with [this line](https://github.com/boothj5/profanity/blob/master/src/log.c#L148).

**Comment by nerd** [comment]
@incertia Thank you very much. The time always showed up right, but it was UTC instead of EST.
