### ISSUE TITLE
"new" chats not appearing

### ISSUE THREAD

**Issue by kjelderg** [boothj5/profanity#605]
People are sending jabber messages to me.  They are not resulting in a new chat window or showing in existing chat windows, as appropriate.  If I send a message to that user, all responses are received appropriately for some time.

I had this behaviour both on the release version from FreeBSD ports and from a recent git version.

**Comment by boothj5** [comment]
Could you attach logs, after running in debug mode and recreating the problem?

There's a guide here:http://www.profanity.im/issues.html#proflogs

And take out any personal information.

Thanks,

**Comment by kjelderg** [comment]
I have not been able to reproduce this since I reported the issue.  Perhaps it was a fluke?  I will reopen if I can get a debug log while it is exhibiting the problem.
