### ISSUE TITLE
Doesn't compile if libgpgme is not available

### ISSUE THREAD

**Issue by User0815** [boothj5/profanity#606]
I just noticed it after pulling the latest version. It then compiled after removing my local copy and cloning it again, but I think lines 488-495 in `src/command/commands.c` need to be inside a `#ifdef HAVE_LIBGPGME` block.

**Comment by mudrd8mz** [comment]
Same here. The compilation fails with

    src/command/commands.c: In function ‘cmd_account’:
    src/command/commands.c:489:21: error: implicit declaration of function ‘p_gpg_valid_key’ [-Werror=implicit-function-declaration]
            if (!p_gpg_valid_key(value)) {

Putting the code into the ifdef block worked for me.

**Comment by boothj5** [comment]
Should be fixed now.

Thanks.
