### ISSUE TITLE
segmantation fault while connecting to slack.com xmpp gateway

### ISSUE THREAD

**Issue by ricky-ticky** [boothj5/profanity#607]
just type /connect myuser@mycompany.xmpp.slack.com, paste password and got segmentation fault:  profanity[10835]: segfault at 0 ip 0000000000443be1 sp 00007ffc96da6de0 error 4 in profanity[400000+6b000]

**Comment by boothj5** [comment]
I assume you're using version 0.4.6?

If so this is probably related to #599 which has been fixed.  You could try building the latest from source, otherwise 0.4.7 will be out soon (code finished, just completing docs etc).

**Comment by ricky-ticky** [comment]
Yes, it was 0.4.6. Thank you.
