### ISSUE TITLE
End OTR session when contact goes offline.

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#611]
See: #558

According to comments in this issue, if a contact goes offline, but doesn't explicitly end an OTR session, profanity does not end the session, the user has to do it manually.

Make sure if a contact goes offline, that profanity ends any current OTR session with that contact, and informs the user.

**Comment by devhell** [comment]
Good idea. :+1:

**Comment by PMaynard** [comment]
Would also be a good idea to end OTR when the connection to the server is lost.
As when I connect to my VPN there is a lag (n seconds for autoreconnect + n server ping) and I think oh good I'm connected and end up sending over plaintext.

**Comment by boothj5** [comment]
Fixed in master.

If the contact goes offline, the OTR session is ended.
Also your connection is lost, any OTR sessions are ended.
