### ISSUE TITLE
Indicator of encryption method per message

### ISSUE THREAD

**Issue by PMaynard** [boothj5/profanity#613]
It would be good to have an option to indicate how the message was sent, e.g.

	13:54 ~ a_user@matrix.ac: This is a plaintext message
	13:54 ~ me: My plaintext reply
	13:54 ~ O a_user@matrix.ac: This is an OTR message
	13:54 ~ O me: My OTR reply
	13:59 ~ P a_user@matrix.ac: This is a PGP messsage
	13:54 ~ P me: My PGP reply

So in this example O is OTR and P is PGP, and nothing for plaintext - Could also be a warning if in plaintext, depends on the situation. Would also be nice to have the indicator configurable, or even theme-able. 

This will help in reassuring the user that it has actually been transmitted using an encryption method. It may also help with debugging.

Thoughts?

**Comment by boothj5** [comment]
Good news, I've already implemented this in master and it'll be in 0.4.7.

`/otr char <c>` - Set the character to show for OTR messages
`/pgp char <c>` - Set the character to show for PGP messages

In your example:

```
/otr char O
/pgp char P
```

Plaintext messages are shown with a `-`.
The OTR and PGP characters both default to `~` if not set.

Both values may be also included in themes:

```
[ui]
otr.char=O
pgp.char=P
```

I'll close this issue, but do open another one if there's any other behavior you'd like.
