### ISSUE TITLE
theme list

### ISSUE THREAD

**Issue by jubalh** [boothj5/profanity#639]
I am running /theme list in profanity which returns:
```
07:28:20 - Available themes:                                                                                                                                                   
07:28:20 - complex  
```

But the directory looks like this:
```
ls /usr/share/profanity/themes 
aqua  batman  boothj5  complex  forest  hacker  headache  joker  mono  orange  original  original_bright  shade  simple  spawn  whiteness
```

However if I use: `/theme load aqua` it works fine.

**Comment by boothj5** [comment]
I can't recreate this. How did you install profanity? Also are there any themes in `/usr/local/share/profanity/themes`?

**Comment by jubalh** [comment]
Nope, it's all in `/usr/share/profanity`, should this be changed to `/usr/loca/share/profanity`?

**Comment by boothj5** [comment]
Nope its ok, just wanted to check it had not previously installed to `/user/local`.

**Comment by jubalh** [comment]
Actually now it works too o_O
The only thing I did was change to some different themes in between. This is strange.
