### ISSUE TITLE
can't connect to google talk

### ISSUE THREAD

**Issue by thorus90** [boothj5/profanity#649]
Hi,

Whenever I try to connect to my gmail account it seems that profanity does nothing(I guess its trying to connect in the background but running in an timeout at some point).

Thats my account:

12:53:15 - Account thorus90@googlemail.com:
12:53:15 - enabled           : TRUE
12:53:15 - jid               : thorus90@gmail.com
12:53:15 - password          : [redacted]
12:53:15 - resource          : profanity
12:53:15 - server            : talk.google.com
12:53:15 - muc service       : conference.gmail.com
12:53:15 - muc nick          : thorus90
12:53:15 - Last presence     : online
12:53:15 - Login presence    : online
12:53:15 - Priority          : chat:0, online:0, away:0, xa:0, dnd:0

When I try:

/connect thorus90@googlemail.com

I get:

12:54:10 - You are either connected already, or a login is in process.

**Comment by boothj5** [comment]
If this is a regular gmail account, you can remove the server property of the account (the default `gmail.com` works for me.

```
/account clear thorus90@googlemail.com server
```

Also, if you want to use groupchat, the `muc service` property should be `groupchat.google.com`, although this shouldn't affect the connection.

```
/account set thorus90@googlemail.com muc groupchat.google.com
```

If you are using a Google Apps account, then your server setting looks correct, but from the email address it looks as though you are using standard gmail.

Some details are here:

http://www.profanity.im/faq.html#gtalk
http://www.profanity.im/faq.html#gtalkrooms

**Comment by thorus90** [comment]
I just added the server for testing, I remove it.

I was not aware that there is a difference between an googlemail account and google apps.

I already allowed less secure apps for my account (the setting was already correct).

Does this mean it doesn't work with an standard gmail account just with an Google Apps Account?

**Comment by boothj5** [comment]
I can connect with my standard Gmail account, so it should work for you with the server property removed.  If you've tried without the server property and it still doesn't work, I'll have to look deeper, but there's always a possibility something has changed at the Google end for some accounts.

**Comment by thorus90** [comment]
If you want me to send you something, or test sth pls let me know, I'm glad to help this issue.

**Comment by pasis** [comment]
@thorus90, logs can show where exactly login process fails or stuck. To get logs just run profanity with `-l DEBUG` option
```
profanity -l DEBUG
```
and look at the end of file ~/.local/share/profanity/logs/profanity.log. You need to find lines starting with something like:
```
21/10/2015 10:28:54: xmpp: DBG: sock_connect to server.com:5222 returned 7
21/10/2015 10:28:54: xmpp: DBG: attempting to connect to server.com
21/10/2015 10:28:55: xmpp: DBG: connection successful
21/10/2015 10:28:55: conn: DBG: SENT: <?xml version="1.0"?><stream:stream to="server.com" xml:lang="en" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">
```
and end with:
```
21/10/2015 10:28:55: xmpp: DBG: Session establishment successful.
21/10/2015 10:28:55: prof: DBG: Connection handler: XMPP_CONN_CONNECT
21/10/2015 10:28:55: prof: DBG: Connection handler: logged in with account name: name@server.com
```
If you post your logs somewhere be sure you remove your password (!). It will look like
```
12/12/2014 14:22:01: conn: DBG: SENT: <auth mechanism="PLAIN" xmlns="urn:ietf:params:xml:ns:xmpp-sasl">AG9saXZlci5tdWVoc2FtAE5oYTEyMDhnIw==(<-- this contains password)</auth>
```
Also good practice is to remove all your contacts and your address information from logs, because they can be used by spammers.

For more information see http://profanity.im/issues.html#proflogs

**Comment by thorus90** [comment]
Hi,

sry for the late answer but I was on business travel.

Here are the logs:

23/10/2015 07:50:19: conn: DBG: SENT: <?xml version="1.0"?><stream:stream to="gmail.com" xml:lang="en" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">
23/10/2015 07:50:19: xmpp: DBG: RECV: <stream:stream from='gmail.com' id='DCB32C0E883C8EC9' version='1.0'>
23/10/2015 07:50:19: xmpp: DBG: RECV: <features xmlns="http://etherx.jabber.org/streams"><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms></features>
23/10/2015 07:50:19: conn: DBG: SENT: <auth mechanism="PLAIN" xmlns="urn:ietf:params:xml:ns:xmpp-sasl">AHRob3J1czkwAHdlcm9kZXJ3YXM=</auth>
23/10/2015 07:50:20: xmpp: DBG: RECV: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure>
23/10/2015 07:50:20: xmpp: DBG: SASL PLAIN auth failed
23/10/2015 07:50:20: conn: DBG: SENT: <iq id="_xmpp_auth1" type="set"><query xmlns="jabber:iq:auth"><username>thorus90</username><password>XXXX</password><resource>profanity</resource></query></iq>
23/10/2015 07:50:20: xmpp: DBG: RECV: </stream:stream>
23/10/2015 07:50:20: xmpp: DBG: Closing socket.
23/10/2015 07:50:20: prof: DBG: Connection handler: XMPP_CONN_DISCONNECT
23/10/2015 07:50:20: prof: DBG: Connection handler: Login failed
23/10/2015 07:50:20: prof: DBG: Connection handler: No reconnect timer
23/10/2015 07:50:20: prof: INF: Login failed

Interessting is that now I get an instant login failed from profanity, before I got no response.

Now I don't know if it is because of the "pause" of 2 days or enabling debug (after disabling debug again I still get an instant response).

From the look of the log I would say the password is wrong, but it is definitly correct (I can login with it on the website).

Thanks!

**Comment by pasis** [comment]
I can reproduce this only with wrong password (or login). Could you try to build latest libstrophe (https://github.com/strophe/libstrophe) and run command:
```
./examples/basic name@gmail.com password
```
This program logins and disconnects immediately. Just say whether you get the same "not-authorized" error or successful connect.

**Comment by thorus90** [comment]
With libstrophe I also get xmpp DEBUG SASL PLAIN auth failed, but I got an email from google that they blocked an unknown device and that someone is knowing my password bla bla.

I authorized this "unknown device" but still getting the SASL PLAIN auth failed.

Perhaps sth is wrong with my gmail account?

Just to clarify that the option "allow less secure apps" ist still on, so thats not the problem, and I did try the password again in an incognito tab, its definitely correct!

**Comment by pasis** [comment]
About the password, I'd suggest to change it, because you posted it above. After you confirm that you changed, I'll show where it is.

I just tried to login to my gmail account, but with `@googlemail.com` instead of `@gmail.com`. Connection with xmpp server is established, but authorization fails in this case. I see from your logs that you use domain gmail.com, so this is probably not the problem.

According to your logs there is no problem with protocol, server just rejects login/password. So if login/password are correct only server side remains (maybe gmail account setting). I can't point to possible misconfiguration since you enabled "less secure apps".

**Comment by thorus90** [comment]
Ok, I changed it(used it for too long anyway), and now it works! So either way the password was too old (last changed 2009) or too simple (as you should know if I really posted it xD)

but only with @gmail.com not with @googlemail.com, but good enough for me.

Thanks for the great support guys!

**Comment by pasis** [comment]
Old or simple password doesn't look as the problem, since gmail accepts it. Anyway, happy to help.

And returning to passwords: I warned to remove content from the following line :)
```
23/10/2015 07:50:19: conn: DBG: SENT: <auth mechanism="PLAIN" xmlns="urn:ietf:params:xml:ns:xmpp-sasl">(!)You should never post text from this tag(!)</auth>
```
If you run the next command you'll get login/password in plain text:
```
echo text_from_auth_tag | base64 -d

$ ./examples/basic name@gmail.com password
conn DEBUG SENT: <auth mechanism="PLAIN" xmlns="urn:ietf:params:xml:ns:xmpp-sasl">AG5hbWUAcGFzc3dvcmQ=</auth>

$ echo AG5hbWUAcGFzc3dvcmQ= | base64 -d
namepassword
```

So edit your post with logs and remove encoded password.

**Comment by pasis** [comment]
Profanity supports only 1 running account. If you want to connect with 2 accounts you should run 2 copies of profanity in 2 terminals. Or disconnect from the 1st account before connection to the 2nd.

There is a feature request for multi account support. See #207.

**Comment by thorus90** [comment]
Ah ok, thx!
