### ISSUE TITLE
*** stack smashing detected ***: profanity terminated Segmentation fault

### ISSUE THREAD

**Issue by axelsimon** [boothj5/profanity#662]
Hi,
After update to Profanity 0.4.7-1 (from 0.4.4-2) on Debian Jessie (8.2), I get the following error when entering my XMPP account's password:
>*** stack smashing detected ***: profanity terminated
>Segmentation fault

Any password, even an empty one, leads to this crash.

It was working fin on 0.4.4-2 and downgrading back to 0.4.4-2 confirms this.

Here's the full debug log:
```
29/10/2015 15:51:43: prof: INF: Starting Profanity (0.4.7)...
29/10/2015 15:51:43: prof: INF: Initialising chat logs
29/10/2015 15:51:43: prof: INF: Initialising groupchat logs
29/10/2015 15:51:43: prof: INF: Loading accounts
29/10/2015 15:51:43: prof: INF: Initialising UI
29/10/2015 15:51:43: prof: INF: Initialising XMPP
29/10/2015 15:51:43: prof: INF: Loading capabilities cache
29/10/2015 15:51:43: prof: INF: Initialising commands
29/10/2015 15:51:43: prof: INF: Initialising contact list
29/10/2015 15:51:43: prof: INF: Initialising OTR
29/10/2015 15:51:43: prof: DBG: GPG: Found gpgme version: 1.5.1
29/10/2015 15:51:43: prof: DBG: Input received: /connect home_as
29/10/2015 15:51:44: prof: INF: Connecting using account: home_as
29/10/2015 15:51:44: prof: INF: Connecting as account@example.net/profanity
29/10/2015 15:51:44: xmpp: DBG: sock_connect to xmpp.example.net:5222 returned 8
29/10/2015 15:51:44: xmpp: DBG: attempting to connect to xmpp.example.net
29/10/2015 15:51:44: prof: INF: Starting main event loop
29/10/2015 15:51:44: xmpp: DBG: connection successful
29/10/2015 15:51:44: conn: DBG: SENT: <?xml version="1.0"?><stream:stream to="example.net" xml:lang="en" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">
29/10/2015 15:51:44: xmpp: DBG: RECV: <stream:stream xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='example.net' id='a9e026de-0bd0-4734-9c23-bde97a1da8aa' xml:lang='en' xmlns='jabber:client'>
29/10/2015 15:51:44: xmpp: DBG: RECV: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required/></starttls></stream:features>
```

I can't see anything relevant when trying to strace the process as I don't have enough knoweldge here :)

Cheers

axel

**Comment by boothj5** [comment]
I'm not overly familiar with how packages are supported across different Debian releases, but since Jessie only includes Profanity 0.4.4-2 perhaps 0.4.7 isn't supported?

https://packages.debian.org/search?keywords=profanity

I have tested with 0.4.7 in Sid and I can connect no problems.

Out of interest how did you install 0.4.7 on Jessie? Did you have to add another repository?

**Comment by Nomad145** [comment]
This seems to be a similar to #404.  By looking, I can't tell if its the exact issue but it seems to be related to the SSL connection.

**Comment by tdi** [comment]
@axelsimon Hi, Profanity Debian Maintainer here. Profanity 0.4.7 is not in Debian jessie (stable). Therefore we can't (in Debian) guarantee that the package from testing/sid will work in stable. 

Also mind that in testing and unstable, the libstrophe version in 0.8.8, whereas in stable it is 0.8.6, so you run profanity 0.4.7 against the old libstrophe version. Is it the case here?

**Comment by pasis** [comment]
As @Nomad145 said, this issue can be related to SHA1 naming issue in libstrophe. It was resolved shared library, but still happens when profanity links with libstrophe statically. SHA1 functions are renamed in latest libstrophe code, so this issue will be fixed in the next release.

**Comment by boothj5** [comment]
Closing as this should be fixed as per the comments above.
