### ISSUE TITLE
/otr myfp or /otr theirfp crashes Profanit

### ISSUE THREAD

**Issue by peckeltw** [boothj5/profanity#673]
Hi,

in a conversation "/otr start" does nothing. "/otr myfp" or "/otr theirfp" crashes profanity:

otr myfp[1]    38388 segmentation fault  profanity -l DEBUG

I am running profanity 0.4.7 installed via Brew on Mac OS X 10.11.1. OTR support is enabled. But I did not generate a new key, but imported the one I created in Adium. Anyone any ideas? Thanks.

**Comment by boothj5** [comment]
Sounds like the import from Adium didn't work.

The required files in profanity (using an example JID "person@server.org") are:

1) A folder `~/.local/share/profanity/otr/person_at_server.org`
2) In this folder a file called `keys.txt` containing the following:
```
(privkeys
 (account
(name "person@server.org")
(protocol xmpp)
(private-key 
 (dsa 
  (p #<removed>#)
  (q #<removed>#)
  (g #<removed>#)
  (y #<removed>#)
  (x #<removed>#)
  )
 )
 )
)
```
3) Also in this folder if you imported any known fingerprints, a file called `fingerprints.txt`. Example contents:
```
friend@server.org	person@server.org	xmpp	<removed>	smp
```

I will do some testing and try to make sure that profanity behaves better if the required files cannot be found or parsed.

**Comment by boothj5** [comment]
Also, if you have time to compile with debug enabled and supply relevant logs and a backtrace, it might help to find exactly what failed: http://www.profanity.im/issues.html

**Comment by peckeltw** [comment]
Adium uses an integer ("1") instead of the account name "person@server.org" and "ibpurple-jabber-gtalk" instead of "xmpp" for the protocol in both files. I left "verified" instead of "smp" that you proposed and it works too. 

So checking that there is no integer might be helpful.

Happy to have OTR in Terminal, thanks for your work.

**Comment by boothj5** [comment]
Thanks.

I believe the `verified`, `smp` is the mechanism by which the fingerprint was trusted, so that makes sense.

I'll leave this issue open until I've recreated and fixed the crash you experienced.

**Comment by boothj5** [comment]
Fixed in master.

When a key cannot be loaded, a message should now appear with the expected `account` and `protocol` values, and OTR functionality is disabled at this point.
