### ISSUE TITLE
Theme colours

### ISSUE THREAD

**Issue by gldtn** [boothj5/profanity#674]
Not sure if this should be posted here.. but how can I add additional colors other than the supported ones:

It would be nice if we can add by HEX (i.e FFFFFF) or RGB! I'm trying to make a theme that looks like the last screenshot on the front page of the Profanity website, but from what I understand it's not possible.

Thanks!

**Comment by incertia** [comment]
most terminal emulators don't support true color. if you want nearest approximation, that would require reading the palette off the controlling emulator and i'm not sure the palette is under the same resource names in .Xresources

**Comment by boothj5** [comment]
The screenshot is an example of where the terminal colour settings have been changed, as well as profanity colours.

There is another issue to support more colours (#593) so closing this one for now.
