### ISSUE TITLE
segfault 11 on osx with slack xmpp gateway

### ISSUE THREAD

**Issue by hanskuhn** [boothj5/profanity#675]
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.9.5
BuildVersion:   13F1134

$ brew info profanity
profanity: stable 0.4.7 (bottled), HEAD

Steps to re-create:

1) $ profanity
2) /connect user@group.xmpp.slack.com
3) <password>

This returns: Segmentation fault: 11

~/.config/profanity/profrc is empty.

I'm attaching the logs from ~/.local/share/profanity/logs/.

[profanity.log.sanitized.txt](https://github.com/boothj5/profanity/files/39483/profanity.log.sanitized.txt)

**Comment by boothj5** [comment]
This is a bug in libstrophe (see #599), the XMPP library used by Profanity.

It has been fixed, but I notice that the 0.4.7 version of Profanity in homebrew depends on version 0.8.6 of libstrophe which does not include the fix.

You could build and install the latest libstrophe, or perhaps raise an issue at the homebrew repository to use the latest version 0.8.8?

**Comment by hanskuhn** [comment]
I'll raise the issue with homebrew. Thanks @boothj5 !

**Comment by hanskuhn** [comment]
Pull request submitted to homebrew project: https://github.com/Homebrew/homebrew/pull/46995

**Comment by boothj5** [comment]
Nice one, thank you.

**Comment by hanskuhn** [comment]
Pull request has been accepted.
