### ISSUE TITLE
Screen is corrupted with some readline settings in tmux

### ISSUE THREAD

**Issue by seamus-45** [boothj5/profanity#681]
These settings is:
**set show-all-if-ambiguous on**
**set show-all-if-unmodified on**
```These will make completions appear immediately after pressing TAB once, instead of the default behavior which is to show them after pressing twice. I think you'll find this saves you many unnecessary keystrokes, but the potential downside is that it could take up the space of terminal backlog you were intending on keeping visible.```
*From* [man](http://linux.die.net/man/3/readline)

When they are mentioned in .inputrc it causes screen corrupting, as you can see on image:
![20151127-16 12 45](https://cloud.githubusercontent.com/assets/2586286/11440146/f4291c8c-9521-11e5-9bed-dcbe16b36f29.png)

## Steps to reproduce:
* `echo -e "set show-all-if-ambiguous on\nset show-all-if-unmodified on" >> ~/.inputrc`
* run tmux
* run profanity inside tmux
* press any of alt+{F1..F12} keys

**Comment by boothj5** [comment]
Thanks for the info, I managed to recreate, with slightly different key presses.

Should be fixed in master. Readline completion is now disabled by profanity since it uses it's own implementation.

Let me know if this fixes the issue for you.

**Comment by seamus-45** [comment]
Unfortunately I can not compile from the git:
```
gcc -DHAVE_CONFIG_H -I. -I./src  -I/usr/include/ncursesw  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -DTHEMES_PATH="\"/usr/local/share/profanity/themes\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g -O2 -I/usr/include/libxml2  -MT src/ui/mucconfwin.o -MD -MP -MF $depbase.Tpo -c -o src/ui/mucconfwin.o src/ui/mucconfwin.c &&\
mv -f $depbase.Tpo $depbase.Po
src/ui/mucconfwin.c: In function 'mucconfwin_get_string':
src/ui/mucconfwin.c:341:5: error: implicit declaration of function 'free' [-Werror=implicit-function-declaration]
     free(title);
     ^
src/ui/mucconfwin.c:341:5: error: incompatible implicit declaration of built-in function 'free' [-Werror]
cc1: all warnings being treated as errors
Makefile:1581: recipe for target 'src/ui/mucconfwin.o' failed
make[1]: *** [src/ui/mucconfwin.o] Error 1
```

**Comment by boothj5** [comment]
This is due to some missing `#include`'s. Unfortunately the the compiler on my machine is not so strict so I'm not getting the errors.

Will take a look and see if there are some compiler options I can use to make sure I get the same errors.

**Comment by boothj5** [comment]
Pulled #683 from @kiethandi which should fix the compile.

I'm still trying to find a way to check for these missing includes (it only appears to be standard library headers that need to be added, others are found transitively) but in the mean time hopefully you can test now.

**Comment by seamus-45** [comment]
Finally, successfuly compiled and issue is gone.

**Comment by seamus-45** [comment]
I do not know if it has value, but the same thing happens with these settings in inputrc:
```
 Control-j: menu-complete
 Control-k: menu-complete-backward
```
if you press the above keys

**Comment by boothj5** [comment]
I think I've found a solution to avoid any custom settings in `~/.inputrc` corrupting the output in profanity.

The change is in master, if you have time, let me know your findings.

**Comment by seamus-45** [comment]
This solved my problem
