### ISSUE TITLE
Fails to accept this password

### ISSUE THREAD

**Issue by PMaynard** [boothj5/profanity#686]
8trPRm/wG/u(R^k,AG+sDdue@^i,Nr5Ftg5oarojos4pGwDpmSKVv2d?*]+WBk[fb>C:'%A]>m,!m"(<)u%4V~(r`=QDX?a(gszd5rcdRB$*n&wa},moJ/q:c^{^+>amrR@>Dqv8;5bu?vSim<2(Uz

Copied and pasted into the password prompt from /connect <jid>
tls request pops up, but Fails to connect. Tested account using mcabber.

**Comment by boothj5** [comment]
There appears to be an issue in libstrophe with passwords larger than 127 bytes. I've raised an issue: https://github.com/strophe/libstrophe/issues/77 and will see if I can find a solution.

**Comment by boothj5** [comment]
A fix has been applied by @pasis to libstrophe, which has also been merged to libmesode.

If you rebuild the latest libstrophe (or libmesode) the password should now be accepted.

**Comment by boothj5** [comment]
Closing as this is fixed in the tests I've run.

Please reopen if you still have the issue.
