### ISSUE TITLE
account settings

### ISSUE THREAD

**Issue by Kaffiend** [boothj5/profanity#716]
Im having an odd issue when i set the same settings up in account they dont work for auto login, but when i issue them with /connect it works.

**Comment by boothj5** [comment]
If you run `/autoconnect` you should see the account name used for autoconnecting.

Running `/account list` shows all account names, so `/autoconnect` should match one in the list.

You can see the settings for an account by running `/account show <account-name>`.

Note, the "account name" and the "Jabber ID" are different properties (account name defaults to the Jabber ID and can be changed with `/account rename`).  

`/autoconnect` uses the account name not the Jabber ID.

It's working locally for me, which settings are not working for you?

**Comment by Kaffiend** [comment]
thanks, all is good.
