### ISSUE TITLE
profanity.im defaced

### ISSUE THREAD

**Issue by murinicanor** [boothj5/profanity#726]
i'm under the impression that the profanity.im website got defaced. 
Screenshot from the bottom of the page:
![screenshot from 2016-01-25 19-50-34](https://cloud.githubusercontent.com/assets/6024601/12560858/3ab131fe-c39d-11e5-93e2-63dfbdf47220.png)

**Comment by boothj5** [comment]
Thanks very much for reporting this.

The site had indeed been hacked by spammers, I'm still not exactly sure how they got in, but it looks similar to the following post:

https://groups.google.com/forum/#!topic/wordpress-austin/oeSpEV9JYXA

I've restored the content, and been through the settings at the hosting provider, upgrading all software and changing all ftp passwords.

If anyone knows anything more about how to stop these kinds of spam hacks, I'd be grateful for any help, in the meantime I'll keep an eye on things.

**Comment by incertia** [comment]
you should get a network/packet log from the hosting provider and have a specialist examine it
