### ISSUE TITLE
no way to specify nick when not in muc rooms?

### ISSUE THREAD

**Issue by tsukurimashou** [boothj5/profanity#740]
I'm trying to find a way to change my display name because all my contacts are seeing me as "nick@server", while I can see them and /msg them with their nick instead of jid. I tried /account set account nick mynick but it says "update muc nick", I can't to change the nick my contacts sees in roster / when having a 1 - 1 conversation with me.

**Comment by boothj5** [comment]
The roster nickname your contact will see has to be set by them, not by you.

Please reopen if I've misunderstood the issue.
