### ISSUE TITLE
TLS Self Signed Cert Error when Trusted

### ISSUE THREAD

**Issue by basilosaurus** [boothj5/profanity#741]
Can't seem to connect to my server with a self signed cert. Haven't tried connecting with any other invalid cert, but I don't think that's the problem here. 

Built on Manjaro Linux using AUR libmesode-git and profanity-git using #280 instructions

Log from Profanity(scrubbed for identifying info):
```
19/02/2016 11:06:08: prof: DBG: Input received: /connect acc
19/02/2016 11:06:12: prof: INF: Connecting using account: acc
19/02/2016 11:06:12: prof: INF: Connecting as user@server.com/profanity
19/02/2016 11:06:12: xmpp: DBG: Connecting via altdomain.
19/02/2016 11:06:12: xmpp: DBG: sock_connect to im.server.com:5222 returned 8
19/02/2016 11:06:12: xmpp: DBG: attempting to connect to im.server.com
19/02/2016 11:06:12: xmpp: DBG: connection successful
19/02/2016 11:06:12: conn: DBG: SENT: <?xml version="1.0"?><stream:stream to="server.com" xml:lang="en" version="1.0" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams">
19/02/2016 11:06:12: xmpp: DBG: RECV: <stream:stream from='server.com' id='5cb6e03' lang='en' version='1.0'>
19/02/2016 11:06:12: xmpp: DBG: RECV: <features xmlns="http://etherx.jabber.org/streams"><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required/></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism></mechanisms></features>
19/02/2016 11:06:12: conn: DBG: SENT: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
19/02/2016 11:06:12: xmpp: DBG: RECV: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
19/02/2016 11:06:12: xmpp: DBG: handle proceedtls called for proceed
19/02/2016 11:06:12: xmpp: DBG: proceeding with TLS
19/02/2016 11:06:12: TLS: DBG: STACK
19/02/2016 11:06:12: TLS: DBG: SUBJECT : /CN=server.com
19/02/2016 11:06:12: TLS: DBG: ISSUER  : /CN=server.com
19/02/2016 11:06:12: TLS: DBG: ENDSTACK
19/02/2016 11:06:12: TLS: DBG: ERROR: self signed certificate
19/02/2016 11:06:18: TLS: DBG: STACK
19/02/2016 11:06:18: TLS: DBG: SUBJECT : /CN=server.com
19/02/2016 11:06:18: TLS: DBG: ISSUER  : /CN=server.com
19/02/2016 11:06:18: TLS: DBG: ENDSTACK
19/02/2016 11:06:18: conn: DBG: Couldn't start TLS! error 1
19/02/2016 11:06:18: conn: DBG: SENT: </stream:stream>
19/02/2016 11:06:18: xmpp: DBG: Send error occured, disconnecting.
19/02/2016 11:06:18: xmpp: DBG: Closing socket.
19/02/2016 11:06:18: prof: DBG: Connection handler: XMPP_CONN_DISCONNECT
19/02/2016 11:06:18: prof: DBG: Connection handler: Login failed
19/02/2016 11:06:18: prof: DBG: Connection handler: No reconnect timer
```

**Comment by boothj5** [comment]
I've tried to recreate using the commit IDs from libmesode-git and profanity-git (on Ubuntu) but can't seem to get the issue.

When a self signed certificate is used, I get presented with the option to continue or abort as expected:

It looks as though either there is no callback (wrong version of profanity) or the callback is not getting called, I'm not sure how the latter could happen.

What's the output of `profanity -v`?

**Comment by basilosaurus** [comment]
Sadly, I won't be able to do anything relating to this until I get back to work on Monday. Do you have a self signed server I could test against in the mean time? I built it on Manjaro originally and I'm in the process of spinning up a Manjaro vm.

**Comment by boothj5** [comment]
No problem.  I don't have a public server available, but I test against a local install of ejabberd with a self signed certificate.

I'll also take a look at adding Arch to the test installs at: https://github.com/boothj5/profanity-vms

**Comment by basilosaurus** [comment]
You have any documentation I can run off to ensure I'm doing the same thing with ejabberd? I can try my hand at it. The server with the self signed cert is openfire at my job afaik.

**Comment by boothj5** [comment]
I've had it setup for a while, I just installed the ejabberd package for my distribution and created a test account with the Admin API (http://localhost:5280/admin). I also have a local Openfire and Prosody for testing.

The server shouldn't make a difference to this issue (I think) as long as a self signed certificate is used, so testing with your work account should be ok.

**Comment by basilosaurus** [comment]
Won't be able to use my work account. The whole thing is NAT'ed and not accessible from the outside. I'd have to wait otherwise.

**Comment by basilosaurus** [comment]
I'm going to chalk this up to compilation error and blame the AUR. Don't worry about fixing this unless other people run into it.
