### ISSUE TITLE
Website User Guide property values are incorrect

### ISSUE THREAD

**Issue by RyanTG** [boothj5/profanity#753]
Just something I noticed today:

On http://profanity.im/themes.html

The values in this section: "The following properties are available in the [ui] section:"

are "true/false" when they should be "on/off"

I didn't go through all of them.

**Comment by boothj5** [comment]
The "true/false" values are used in the theme file (which uses the [Glib key value file parser](https://developer.gnome.org/glib/2.26/glib-Key-value-file-parser.html) implementation).  The commands usually use "on/off" to enable or disable the settings.

I've added a note and changed the table header to emphasise this as I guess it can be a little confusing.
