### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by Dav1d23** [boothj5/profanity#755]
Hello, 

I was trying to build from latest sources, and I end up with this error.

```
checking whether make supports nested variables... yes
./configure: line 2935: syntax error near unexpected token `src/prof_config.h,'
./configure: line 2935: `AX_PREFIX_CONFIG_H(src/prof_config.h, PROF, src/config.h)'
Error 2 with command './configure' on line 98. Exiting.
```

**Comment by kiethandi** [comment]
I had this issue too, James had mentioned this was because of new dependencies for the plugin stuff.

Need to insatall lib-tool and autoconf-archive, then build - resolved the issue for me.

**Comment by boothj5** [comment]
As @kiethandi points out this is due to the new dependencies in master (https://github.com/boothj5/profanity/issues/572#issuecomment-190954336), these will be added to the install script and distro packages for release.
