### ISSUE TITLE
external command at notification

### ISSUE THREAD

**Issue by clementino** [boothj5/profanity#759]
I'm looking for a way to have an external command run when a notification is triggered.
That is because I run profanity over ssh and I have my own "remote" notifier which I would like to use, but I think it would be generally useful because it would allow to play sounds and such.

One solution could be to have a configurable command to run the same way "terminal-notifier" is run on the mac, with the message as the last argument which I could grep to distinguish between different kind of notifications.

Alternatively profanity could look for a predefined executable, say $CONFIG_HOME/notifier, and run it with the message as argument if found.

I could try to write something if you find one of these ideas reasonable.
Thanks.

**Comment by boothj5** [comment]
Sounds like a good use case for a plugins.

The master branch now supports writing plugins in Python (and C).  There are many hooks (chat messages, room messages etc) available to plugins. Until the documentation written for the release, the test plugins are a good guide for available hooks.

The readme has some information on writing/installing plugins: https://github.com/boothj5/profanity-plugins

If there's any additional hooks/api calls you would like, let me know.

**Comment by clementino** [comment]
I think this would address issue https://github.com/boothj5/profanity/issues/334 too, and vice versa (I didn't find it on the first search).

Pidgin allow you to configure a sound file for each event type and also to configure an external command which is run and gets the sound file as argument.

I used that mechanism to do other things than play sounds because the passed filename can be used by the external command to infer the event type and you don't need to actually play the sound.

I think it would be better if profanity doesn't concern itself with sound files and just passes information about the event and let the external command decide what to do (a la mcabber).

Thanks for the introduction about plugins, it doesn't look too hard, I'll give it a try!

**Comment by clementino** [comment]
I succeeded in making a very simple python plugin that runs my own notifier in the prof_post_*_message_display functions, which solves most of my problems, thanks!

It would be nice if I could do the same thing in the event of change of contact presence, is it possible with the current api? (I'm looking for something like f(jid, old_presence, new_presence)).

If someone want to write for example a sound notification plugin he would want to catch more events, like the ones for which you can activate desktop notifications with the /notify command.

Sorry if I missed such functionality, my understanding is still limited.

**Comment by boothj5** [comment]
Apologies, I missed your last comment.

I've added an issue #777 for a plugin presence hook and will implement it shortly,

**Comment by boothj5** [comment]
@clementino, I've added a couple of hooks for presence events, see #777
