### ISSUE TITLE
Reinstall using brew fails when trying with --HEAD

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#760]
I get the following error message on OSX El Capitan:

==> Reinstalling profanity with --with-terminal-notifier
==> Cloning https://github.com/boothj5/profanity.git
Updating /Library/Caches/Homebrew/profanity--git
==> Checking out branch master
==> ./bootstrap.sh
Last 15 lines from /Users/rcalles/Library/Logs/Homebrew/profanity/01.bootstrap.sh:
2016-03-14 11:11:46 +0100

./bootstrap.sh

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: glibtoolize --copy --force
Can't exec "glibtoolize": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN2> line 7.
autoreconf: failed to run glibtoolize: No such file or directory
autoreconf: glibtoolize is needed because this package uses Libtool

READ THIS: https://git.io/brew-troubleshooting

**Comment by boothj5** [comment]
See https://github.com/boothj5/profanity/issues/572#issuecomment-190954336
