### ISSUE TITLE
Manual Installation fails on OSX

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#761]
Also the manual install currently fails on OSX:

[master][] ➜ ./bootstrap.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
glibtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:13: installing 'build-aux/compile'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
autoreconf: Leaving directory `.'

---------------------------------------------------------------------------------------------------------------------------

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
./configure: line 2944: syntax error near unexpected token `src/prof_config.h,'
./configure: line 2944: `AX_PREFIX_CONFIG_H(src/prof_config.h, PROF, src/config.h)'

**Comment by boothj5** [comment]
Same as #760

**Comment by ReneVolution** [comment]
Could manage to fix this issue following #572 but now i am running into another problem:

src/xmpp/connection.c:365:12: error: implicit declaration of function 'xmpp_uuid_gen' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return xmpp_uuid_gen(jabber_conn.ctx);
           ^
src/xmpp/connection.c:365:12: error: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *' [-Werror,-Wint-conversion]
    return xmpp_uuid_gen(jabber_conn.ctx);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/xmpp/connection.c:477:16: error: implicit declaration of function 'xmpp_conn_is_secured' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        return xmpp_conn_is_secured(jabber_conn.conn) == 0 ? FALSE : TRUE;
               ^
src/xmpp/connection.c:477:16: note: did you mean 'jabber_conn_is_secured'?
src/xmpp/connection.c:474:1: note: 'jabber_conn_is_secured' declared here
jabber_conn_is_secured(void)
^
src/xmpp/connection.c:531:9: error: implicit declaration of function 'xmpp_conn_set_flags' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        xmpp_conn_set_flags(jabber_conn.conn, XMPP_CONN_FLAG_MANDATORY_TLS);
        ^
src/xmpp/connection.c:531:9: note: did you mean 'xmpp_conn_set_pass'?
/usr/local/Cellar/libstrophe/0.8.8/include/strophe.h:215:6: note: 'xmpp_conn_set_pass' declared here
void xmpp_conn_set_pass(xmpp_conn_t * const conn, const char * const pass);
     ^
src/xmpp/connection.c:531:47: error: use of undeclared identifier 'XMPP_CONN_FLAG_MANDATORY_TLS'
        xmpp_conn_set_flags(jabber_conn.conn, XMPP_CONN_FLAG_MANDATORY_TLS);
                                              ^
src/xmpp/connection.c:533:47: error: use of undeclared identifier 'XMPP_CONN_FLAG_DISABLE_TLS'
        xmpp_conn_set_flags(jabber_conn.conn, XMPP_CONN_FLAG_DISABLE_TLS);
                                              ^
6 errors generated.
make[1]: *** [src/xmpp/connection.o] Error 1
make: *** [all] Error 2

**Comment by boothj5** [comment]
These are new functions in the XMPP library used by Profanity.

Building and installing from the master branch of [libstrophe](https://github.com/strophe/libstrophe) (or [libmesode](https://github.com/boothj5/libmesode) to get SSL certificate support) should fix the issue.
