### ISSUE TITLE
Add plugins management options

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#764]
It would be great to manage plugins without the need of restarting and adjusting profrc manually. Instead we should provide some commands to help here as:

/plugins reload [optional-plugin-name or ALL]
/plugins install <path-to-plugin>
/plugins load <plugin-name> to load an unloaded but installed plugin
/plugins unload <plugin-name> to unload/disable a plugin

Any other hint for a useful command is appreciated.

**Comment by boothj5** [comment]
Added `/plugins load <plugin>` in master, should autocomplete the name of any plugins found in the plugins directory not currently loaded.

The unload/reload commands will take a bit more work since currently there is no link between a plugin and the command/timed handlers it registers, but I'm looking into it.

**Comment by boothj5** [comment]
As part of the `load` command, I've also added two additional args to the `prof_init` hook: `account_name` and `fulljid`.  

If the user is currently connected when the plugin is loaded they will contain the relevant details (similar to `prof_on_connect`), if the user is not connected they will be `None` (Python) or `NULL` (C).

**Comment by boothj5** [comment]
Added `/plugin unload` command.

**Comment by boothj5** [comment]
Added `/plugin reload` command, passing no argument reloads all plugins.

**Comment by boothj5** [comment]
Added `/plugins install` command.  Copies the plugin to the plugins directory and loads it. If the plugin is already loaded, it will be reloaded after copying.
