### ISSUE TITLE
Troubleshooting random disconnects. Unrecoverable TLS error 1

### ISSUE THREAD

**Issue by cvervais** [boothj5/profanity#770]
I'm trying to track down what's causing what appears in the client as random disconnects due to TLS errors. Likely it's the network or the server but, with the little information I've got there's much finger pointing going on.

I'm certain it's not the client because it happens with iMessage and Adium on OS X, both of which use the OS X networking framework and it also happens on Pidgin on Ubuntu using Mozilla NSS and also with profanity on Ubuntu using OpenSSL.

But, profanity is getting me the closest to figuring it out by spitting out the most useful debug message (of the various clients I've been using) to date which is....

23/03/2016 12:41:08: prof: INF: Capabilities response handler fired for id prof_caps_339
23/03/2016 12:41:08: prof: WRN: No node attribute found
23/03/2016 12:41:10: xmpp: DBG: Unrecoverable TLS error, 1.

This is happening at random and well after the client is connected. Is there anything further I can enable in profanity to be able to get closer to what's blowing up the connections?

**Comment by boothj5** [comment]
The node attribute warning isn't related to the connection problem. It looks as though the TLS connection has just been killed at the other end as you say, but I can't give much more information.

I wrote a quick hack to find out what the error code means, but its not returning anything useful.

**Comment by cvervais** [comment]
Yeah, I figured that about the node warning, I just included it for completeness' sake and to show that there was activity prior to the disconnect.

The strange thing is, the other side sees the client as closing the connection. Hence the finger pointing. 

I suspect the SSL framework on the client (secureTransport, Mozilla NSS, OpenSSL, etc) is detecting something 'wrong' and determining that the connection is broken and then killing it. 

It's looking like i'm going to have to resort to ssldump/wireshark to try and figure out what's blowing it up. 

Thanks for trying to whip something up but, I'm pretty convinced that what I'm facing is happening underneath you and it's openSSL that would have to be turned to debug to be able to do figure out why it's determining that the connection has gone bad. 

Unless you've got any other ideas that is :)

**Comment by boothj5** [comment]
The error code I got with the hack returns `DH lib` as the reason.  Which is not too helpful, something to do with with Diffie-Hellman key exchange.

The only other thing I can think of is that somewhere along the journey from client to server another node in the network is killing the connection, so both ends receive the error, but this is just speculation.

**Comment by cvervais** [comment]
No worries on the speculating, I've come up with some wild ones.

I think at this point I'm going to close this and not eat up more of your time since it's CLEARLY not profanity. I've gotten further with debugging this and have zero'd in on the condition being a bad_record_mac error which gives me something to go on. 

Thanks again for the responsiveness. +1 beers for you.

**Comment by pasis** [comment]
Description of the error code:
```
SSL_ERROR_SSL

    A failure in the SSL library occurred, usually a protocol error.
    The OpenSSL error queue contains more information on the error.
```
I don't know if the "error queue" contains any useful information, but you can easily recover it by modifying libstrophe. Of course you need to find openssl api function to get info from the error queue.

**Comment by boothj5** [comment]
I was using `ERR_error_string` but as @pasis says, the following is probably more useful as is shows the whole error queue:

https://www.openssl.org/docs/manmaster/crypto/ERR_print_errors.html

**Comment by pasis** [comment]
So patch to libstrophe would look like:
```
diff --git a/src/tls_openssl.c b/src/tls_openssl.c
index 2351275..0c67866 100644
--- a/src/tls_openssl.c
+++ b/src/tls_openssl.c
@@ -13,6 +13,7 @@
  *  TLS implementation with OpenSSL.
  */
 
+#include <stdio.h>
 #include <string.h>
 
 #ifndef _WIN32
@@ -48,6 +49,8 @@ void tls_shutdown(void)
 
 int tls_error(tls_t *tls)
 {
+    if (tls->lasterror != 0)
+        ERR_print_errors_fp(stderr);
     return tls->lasterror;
 }
 
```

**Comment by cvervais** [comment]
Ok, I've modified libstrophe as you've detailed, recompiled it and also profanity. Now just waiting for a screwed up packet.

**Comment by cvervais** [comment]
So, I'm still waiting for it to happen again. Can you point me at any documentation to control the debug log file rotation? I'm in what can best be described as a high traffic XMPP environment and the default rotation causes it to rotate pretty quickly.

**Comment by boothj5** [comment]
You can turn off rotation with `/log rotate off`, or change the size before rotation with `/log maxsize <bytes>`

See `/log help` for all settings, running just `/log` will show the current settings.

**Comment by cvervais** [comment]
Awesome, thanks! FWIW, since making the change to lib strophe the problem isn't happening. But, I think that's a function of folks taking today off and the load on the XMPP service is lower than usual. There's no way the change could affect how it handles the issue. And, I've verified in the debug logs that I am using TLS when I connect. Fingers crossed it happens again soon.

**Comment by cvervais** [comment]
Progress, the change worked and I got the exact error:

25/03/2016 13:02:36: stderr: ERR: 140468903839632:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:s3_pkt.c:486:

So, now I'm suspecting that the server is sending down unencrypted data over the ssl connection. This was a great help!
