### ISSUE TITLE
Plugins: Stanza handling

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#772]
Allow plugins to:

* Send stanzas
* Implement a hook for when a stanza is sent
* Implement a hook for when a stanza is received

This should help #658

**Comment by boothj5** [comment]
Sending of stanzas is in master, as the prof_send_stanza API call.

**Comment by ReneVolution** [comment]
Wow ... awesome. Thanks so far :)

**Comment by boothj5** [comment]
Also, break the hooks down by stanza type:
* `iq`
* `presence`
* `message`

The stanza hooks should allow the plugin to manipulate the stanza before sending.  A `prof_before_message_stanza_send()` hook for example can return a stanza that will be sent instead of the original, if no stanza is returned from the hook, then the original will be sent.

**Comment by boothj5** [comment]
Added the following hooks in master.

```
prof_on_message_stanza_send(stanza)
prof_on_presence_stanza_send(stanza)
prof_on_iq_stanza_send(stanza)
```

If the plugin returns a string, it is used instead of the original stanza, if it return nothing, the original is used, examples in [python-test.py](https://github.com/boothj5/profanity-plugins/blob/master/tests/python-test.py) as usual.

I'll look into stanza receive hooks next.

**Comment by boothj5** [comment]
Added the receive hooks in master.

```
prof_on_message_stanza_receive(stanza)
prof_on_presence_stanza_receive(stanza)
prof_on_iq_stanza_receive(stanza)
```

If the hook returns `True`, then Profanity will continue to process the stanza, if it returns `False` then Profanity will stop processing the stanza.
