### ISSUE TITLE
Plugins: Allow plugins to store settings

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#773]
Similar to how plugins can access their own themes, allow them to have settings and access them via functions like:

```
prof.get_string_setting(group, key)
prof.get_boolean_setting(group, key)
prof.get_number_setting(group, key)
prof.get_string_list_setting(group, key)

prof.set_string_setting(group, key, value)
prof.set_boolean_setting(group, key, value)
prof.set_number_setting(group, key, value)
prof.set_string_list_setting(group, key, value)
```
etc.

This should also help with #658

**Comment by ReneVolution** [comment]
I guess this incorporates the setting of settings as well :)

Anyway, we also need something like a setting per window/muc/jid basis to for example store that we are in a specific mode e.g. OMEMO similar to OTR. What do you think?

**Comment by boothj5** [comment]
Setting properties will also be added, I'm working on it at the moment.

I think this kind of per MUC/JID state can be handled by the plugin.  When any message is received the relevant hooks will be called with the room/user JID as an argument, so the plugin can keep its own data structure representing any state associated with the room/user and process it as needed.

The connect/disconnect hooks will also allow the plugin to clear down any state it has associated with a connection.

Might need to add some more hooks, but as a general pattern I'd like keep state associated with the plugin in the plugins themselves.

Also in terms of getting the OMEMO plugin working, I was thinking we could hack together a quick prototype which mimics the events of the OMEMO protocol but doesn't actually do any of the real OMEMO functionality.  That way we'll know what kind of API calls/hooks are needed, and once they are implemented you can build the real OMEMO plugin.  Just an idea though, if it's quicker just to build the real plugin then it wouldn't be worth spending too much time on a prototype.

**Comment by ReneVolution** [comment]
I have to admit that you are totally right on this. Plugin states should be managed by plugins.

In regards to the OMEMO plugin prototype i agree as well. If we could hack something together that would be awesome. I will try to create some kind of a flow chart tonight for the beginning. Once we're on the same page about the flow we should be able to start working on both sides.

**Comment by ReneVolution** [comment]
Ok, so i took some time to check how the flow would be going and i have to say it looks as it is not hopeless :). Most of the stuff i have to add with a plugin is some stanza modifications based on the incoming infos and what the python-omemo lib returns. So the flow would look like the following:

1) /omemo start

First we have to initiate a chat with an OMEMO state, which will be the same as with OTR/PGP etc. The plugin will create a sqlite3.db to store keys and device ID's and also create a device ID's on initialisation. After that it will announce this device id using a prof_send_iq_stanza as well as it will announce bundle information the same way. Also a session is created for the current jid.

Important is that we make sure that if the plugin sets the chat session mode to OMEMO, every other encryption mode is turned off as we'll need plaintext to encrypt with OMEMO.

2) prof_on_before_message_stanza_sent

I am currently planning to use the regular stanza profanity would send and "just" add the necessary info. 

3) prof_on_message_stanza_received

Same here. I'd convert the stanza into a plaintext one and return it. I may also return None in case it is an OMEMO message but the device ID does not match.

For the sake of completeness it would be great if we'd also keep the prof_send_raw_stanza hook.

So, it does not look to complicated to do from my point of view. Do you see any blockers?

**Comment by ReneVolution** [comment]
Oh, and the namings i suggested can be changed of course :)

**Comment by boothj5** [comment]
Added the following settings functions in master:

```
prof.settings_set_boolean(group, key, value)
prof.settings_get_boolean(group, key, default)

prof.settings_set_string(group, key, value)
prof.settings_get_string(group, key, default)

prof.settings_set_int(group, key, value)
prof.settings_get_int(group, key, default)
```

The settings are written to `~/.local/share/profanity/plugin_settings`. Examples added to [python-test.py](https://github.com/boothj5/profanity-plugins/blob/master/tests/python-test.py).

Didn't bother with the string list type, but will raise another issue if we need it.

And thanks for the other info about OMEMO, I'll look into the stanza hooks next and update #772
