### ISSUE TITLE
Plugins: Add incoming message API function

### ISSUE THREAD

**Issue by boothj5** [boothj5/profanity#776]
Allow plugins to show a new incoming message, for example:

```
prof_incoming_message(barejid, resource, message)
```

The function should do all the work of creating a chat window if needed, adding to the unread message count etc.  Also might be needed for #658

**Comment by boothj5** [comment]
Added the basic function in master, but might need a few more options, like chat states, the character to show, whether the text was encrypted etc.

**Comment by ReneVolution** [comment]
Agree with that idea. Good call. Great progress on this so far. Thanks a lot.

**Comment by boothj5** [comment]
Closing this issue for the 0.5.0 release.

Should any more arguments be required for new plugins, I'll add them as optional keyword arguments in a patch release.
