### ISSUE TITLE
Make it possible to hide join/part and status change messages

### ISSUE THREAD

**Issue by jtdaugherty** [boothj5/profanity#784]
I'd love it if I could hide status change messages and alerts about users leaving or joining chat rooms.

**Comment by boothj5** [comment]
Is `/statuses muc none` what you're looking for? See `/help stauses`

**Comment by jtdaugherty** [comment]
Oh! That does do what I want. The docs confused me because "statuses" doesn't usually mean "messages about users leaving and entering rooms." Thanks!

**Comment by imShara** [comment]
Is it gone/changed?

**Comment by paulfariello** [comment]
I think it's now handled with `/presence`.
http://www.profanity.im/reference.html#presence
