### ISSUE TITLE
Add Support for Blocking Users

### ISSUE THREAD

**Issue by 0xPoly** [boothj5/profanity#793]
Recently I've been receiving spam from another XMPP ID. It seems profanity doesn't have the functionality to block a particular user. It would be nice if it could be added.

Possibly relevant:
https://xmpp.org/extensions/xep-0191.html

Thanks!

**Comment by boothj5** [comment]
Implemented in master, see the `/help blocked`.

**Comment by 0xPoly** [comment]
Thanks, this looks like it works on my end. Will test it on the spammers if they come back :P
