### ISSUE TITLE
Can't use PGP

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#796]
Hey,

i am now trying for days (weeks) to get profanity running with PGP but for some reason it won't work.
My account data is:

23:58:23 - Account renevolution@draugr.de:
23:58:23 - enabled           : TRUE
23:58:23 - jid               : renevolution@draugr.de
23:58:23 - resource          : laptop
23:58:23 - muc service       : conference.draugr.de
23:58:23 - muc nick          : renevolution
23:58:23 - Last presence     : online
23:58:23 - Login presence    : online
23:58:23 - PGP Key ID        : 67039F265E83B964
23:58:23 - Priority          : chat:9, online:9, away:9, xa:9, dnd:9
23:58:23 - Resources:
23:58:23 -   laptop (9), online

It is the correct key as far as i can see. Also, with a Conversations client on the other side, he get's an error when trying to send encrypted messages because i did not announce my key :(

Any idea what could go wrong here?

**Comment by ReneVolution** [comment]
also when using profanity on both sides the other contact never sees .... KEY (received) but i do for him in /pgp contacts

**Comment by boothj5** [comment]
Can you attach the output of running:

```
profanity -v
```

And from within profanity:

```
/pgp libver
```

When you run:

```
/pgp keys
```

I assume you see the key associated with the account?

Also do you see your contact with a key (from the list above) when you run:

```
/pgp contacts
```

Finally, is the name associated with your key your Jabber ID, or something else?

**Comment by ReneVolution** [comment]
Sure, 

output of profanity -v:

`[] ➜ profanity -v
Profanity, version 0.5.0dev.master.6f81f2b
Copyright (C) 2012 - 2016 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled
PGP support: Enabled
C plugins: Enabled
Python plugins: Enabled`

for /pgp keys and /pgp contacts => both yes.

Output of /pgp keys:

00:12:24 -   renevolution <renevolution@draugr.de>
00:12:24 -     ID          : 67039F265E83B964
00:12:24 -     Fingerprint : [removed for this post]
00:12:24 -     Type        : PUBLIC, PRIVATE

So, the key is associated with my Jabber ID i guess.

**Comment by ReneVolution** [comment]
Additionally, from profanity i can receive encrypted messages when the other side has stored my key manually.

**Comment by boothj5** [comment]
I remember someone posting this a while ago: https://twitter.com/bscht/status/689551911238901762

Don't know if you do twitter, but maybe you could ask them what the problem was, I'll try to find out in the meantime.

**Comment by ReneVolution** [comment]
I am already in contact with him as he is "the other side" :D

**Comment by bascht** [comment]
Happy to chime in here. :D Said tweet was related to a bit of a bumpy ride, but in the end @annismckenzie and me got it to work and it is still working fine. 

So, for now: The Debug output from `the other side`:

```
$ profanity -v
Profanity, version 0.5.0dev.master.20a0313
Copyright (C) 2012 - 2016 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Enabled
OTR support: Enabled
PGP support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons: Enabled
```

```
/pgp libver
00:38:04 - Using libgpgme version 1.4.3
```

The key is listed in `/pgp keys` and in `/pgp contacts`. Will investigate further. :]

**Comment by boothj5** [comment]
Thanks, I'm just trying now with Profanity -> Conversations.

**Comment by ReneVolution** [comment]
Oh ... the output of my /pgp liver is 
00:43:06 - Using libgpgme version 1.6.0

**Comment by bascht** [comment]
@boothj5 Yip. Interestingly enough it worked from me[profanity] → @ReneVolution[conversations].

**Comment by ReneVolution** [comment]
and also from me[conversations| --> @bascht[profanity] in return.

**Comment by boothj5** [comment]
Ok so I have it working, Profanity <--> Conversations

Bob, Profanity
* Generate a key on my laptop, for `bob@server.com`, using any PGP key management app
* It appears in `/pgp keys` in profanity
* Assign that key to my account in profanity with `/account set bob@server.com pgpkeyid <keyId>`

Alice, Conversations
* Generate a key on phone with OpenKeychain app, for `alice@chat.org`
* Associate this key in Conversations to the `alice@chat.org` account

Alice and Bob
* Share their public keys with each other, I just emailed them, but key servers etc can be used.

Bob, Profanity
* Import Alices public key using the PGP application

Alice, Converations
* Import Bobs public key using OpenKeychain

Profanity now shows Alices public key in `/pgp keys`

On the next presence update from Alice or Bob, the other will associate the public key with the sender, for example profanity shows:

```
Assigned PGP public keys:
  alice@chat.org: <redacted> (received)
```

And from that point onwards encryption works both ways.

Is there anything you're doing different to the above?

**Comment by bascht** [comment]
Thanks for looking into this!

Just re-checked. We're did exactly the same. Like @ReneVolution said: It is only broken for Profanity←→Profanity. Once he switches to Conversations and I stay in Profanity, we can communicate in both directions.

I'd be happy to play Alice – so feel free to add me: bascht <at> yakshed <dot> org.

**Comment by boothj5** [comment]
I just tried and it worked for me Profanity <--> Profanity using the same process above for importing/exporting and sharing public keys.

Alice Profanity:
* `/pgp keys` shows Bob's PUBLIC key and Alice's PUBLIC/PRIVATE key
* `/account` shows `PGP Key ID` matching Alice's PUBLIC/PRIVATE key above
* `/pgp contacts` shows Bob, with id matching Bob's PUBLIC key above

Bob Profanity:
* `/pgp keys` shows Alice's PUBLIC key and Bob's PUBLIC/PRIVATE key
* `/account` shows `PGP Key ID` matching Bob's PUBLIC/PRIVATE key above
* `/pgp contacts` shows Alice, with id matching Alice's PUBLIC key above

Messages encrypted both ways after `/pgp start` at both ends.

I'm trying to figure out how it might be broken for you.

**Comment by bascht** [comment]
I'm off for today, but will also give it a try tomorrow. Like I said: profanity -> profanity works for @annismckenzie and me and it doesn't for @renevolution and me. So at least there is something to start comparing.

Anyway, thank you so much for looking into this and helping with debugging. :-)

**Comment by boothj5** [comment]
Ok no probs, let me know if you find anything interesting.

And @ReneVolution I'm also on libgpgme version 1.6.0, so we can rule that out as a potential cause.

**Comment by ReneVolution** [comment]
It is soo strange. I'm close to giving up. It does not make any sense.

**Comment by boothj5** [comment]
Two more questions:

Which key management tool are you using? And do you get prompted (outside of profanity) to enter a passphrase when you start profanity etc?

Can you attach logs (`profanity -l DEBUG`) for when you log in, send or receive messages with PGP.

**Comment by ReneVolution** [comment]
Sure,

the key management i am using is GPG Keychain on OS X Version 1.2.1 (1147) (from gpgtools)
Please find the Log here: http://pastebin.com/gqfwQewQ

**Comment by ReneVolution** [comment]
Okay, 

further debugging resulted in the following:

- Manually encrypted armor messages can be decrypted on both sides.
- For messages from the debug log we get errors complaining about corrupted CRC checksums and "invalid armor header"

**Comment by ReneVolution** [comment]
To be more specific:
[] ➜ gpg --decrypt message
zJkIrusDL4RPXYziAZpV5ul2CinqZSbYNzxgp2CtXVDbisgAbOqUmkyYwR3IRi+j\n
gpg: invalid armor header:
gpg: CRC error; 156EAF - 6A3B29
gpg: onepass_sig with unknown version 213

**Comment by boothj5** [comment]
So, trying to summarise the information so far, to narrow down what the problem might be.

Firstly the problem is only when ReneVolution is using profanity:
1. ReneVolution conversations -> bascht profanity: WORKS
2. bascht profanity -> ReneVolution conversations: WORKS
3. ReneVolution profanity -> bascht profanity: FAILS
4. ReneVolution profanity -> bascht conversations: FAILS
5. bascht profanity -> ReneVolution profanity: FAILS
6. bascht conversations -> ReneVolution profanity: FAILS

By FAIL, I assume some some kind of "Cannot decrypt" message is displayed.

Secondly, the first two comments on this issue sound like ReneVolutions presence is not being signed, or bascht has not installed ReneVolutions public key in his keychain, but a later [comment](https://github.com/boothj5/profanity/issues/796#issuecomment-212157550) suggests that bascht can see ReneVolutions public key as `received` with `/pgp contacts` and the logs also show presence being signed.

Both ReneVolutions and baschts keys are associated with their Jabber ID, not another email address for example.

The logs show no errors, e:g: `GPG: Decrypted message for recipients: renevolution@yakshed.org` is logged as if everything worked.

Finally the errors when manually decrypting messages from the logs might be related, but it could also be due to newline characters etc when pasting from the log.

The only other significant difference is the version of libgpgme at both ends, which originally I thought wouldn't be a problem, but probably worth proving.

I must admit... I'm struggling...

**Comment by boothj5** [comment]
@ReneVolution one other thing (if you haven't given up yet!), could you attach your:

```
~/.config/profanity/profrc
``` 
(removing any private information) as there's also a chance that some specific configuration has exposed a bug.

**Comment by ReneVolution** [comment]
@boothj5 Please find my profrc here: http://pastebin.com/uRcQeKs6

**Comment by ReneVolution** [comment]
Please see some minor corrections on your summary:

5. bascht profanity -> ReneVolution profanity: WORKS 
also, @bascht can't see ReneVolutions key as 'received', just as 'stored'

Everything else is correct.

**Comment by boothj5** [comment]
Corrected my comment.

Don't know if its possible but logs from @bascht might help when
1) Receiving a message from you
2) Receiving signed presence from you

**Comment by boothj5** [comment]
Something I just noticed... in the comments above your JID is: renevolution@draugr.de but in the logs its renevolution@yakshed.org, do the two have exactly the same set up and the same issues?

**Comment by ReneVolution** [comment]
Yes, both have the same issues. I just used different accounts for testing, so i don't have to bother my friend @bascht all the time.

**Comment by bascht** [comment]
I had to censor the logs quite a bit – so I hope it is still useful. In case you need the bits inbetween, I would have to filter it even more.

Here we go: https://gist.github.com/bascht/9e3aa47291311dd90662f9df965bd874

**Comment by BastiTee** [comment]
Hi, I ran into the same problem. What I can say so far:

I set up a ejabberd server on an Ubuntu 16.04 and basically run it on its default settings. I can communicate over the server with local users as well as users on other jabber servers. I also managed to setup OTR encryption. So c2s and s2s communication seems to work fine.

Regarding gpg. A gpg agent is up and running. 

```
basti@tee:~$ gpg-agent status
gpg-agent[5357]: gpg-agent running and available
```

Using gpg 1.4.20 I created a key pair to be used. 

```
basti@tee:~$ gpg --list-keys
/home/st/.gnupg/pubring.gpg
---------------------------
pub   2048R/53F4AAB0 2017-02-17 [expires: 2017-03-03]
uid                  Basti Tee <basti.tee@gmx.de>
sub   2048R/016CE2B9 2017-02-17 [expires: 2017-03-03]
```

Exporting and encyption with the CLI tools works fine.. 

```
basti@tee:~$ gpg --export -a -o gpg-public.basti.key Basti Tee
basti@tee:~$ cat gpg-public.basti.key 
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1
mQENBFimv80BCAC9J5KR3..
```

So I am basically stuck with that since I could find a way to make those keys appear in profanity. I tried putting stuff into ~/.local/share/profanity/ but with no success. 

All I got in profanty is ...

```
/pgp keys 
No keys found
/pgp libver
Using libgpgme version 1.6.0
```

**Comment by BastiTee** [comment]
I tried to run with a different client (mcabber). While I could find, that my gpg key signature can be listed by running 

```
gpg --list-secret-keys --keyid-format long 
```

it was impossible to make mcabber read that key. I got stuck with 

```
[12:46:40] GPGME error: private key not found
```

So maybe it's a backend issue afterall, i.e. some issue with libgpgme..

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  libgpgme11:amd64        1.6.0-1          amd64            GPGME - GnuPG Made Easy (library)

```

**Comment by BastiTee** [comment]
Yup. I'd say it's the backend. With hints from @bascht I tried to exchange libpgpme 1.6 with 1.8 and voila...

![screenshot from 2017-02-20 13-21-19](https://cloud.githubusercontent.com/assets/7995100/23124904/9e0f8c26-f76f-11e6-9694-800303f5c2ca.png)

**Comment by BastiTee** [comment]
Well shit. The above was tested inside a virtual box. Outside I cannot reproduce the error even though I've upgraded to 1.8.0 libgpgme. Hmm. So it's not just 1.8.0

**Comment by BastiTee** [comment]
Hehe :) Back to square one. I downgraded libpgpme back to 1.6 but kept the keys generated inside the virtual box. 
Now I can use the keys together with 1.6.0.

```
14:36:26 - Type '/help' to show complete help.
14:36:26 - 
14:36:34 - Using libgpgme version 1.6.0
14:36:38 - PGP keys:
14:36:38 -   Basti Tee <basti.tee@gmx.de>
14:36:38 -     ID          : E0EB5E2D5801CE7A
14:36:38 -     Fingerprint : 97C5 0AD0 E807 DA3C F421 6723 E0EB 5E2D 5801 CE7A
14:36:38 -     Type        : PUBLIC, PRIVATE
```

**Comment by boothj5** [comment]
Thanks for trying things out.

Just to confirm, what is the combination that causes the problem, is it the version of libgpgme plus something else?

**Comment by BastiTee** [comment]
I don't know :( As I said profanity 0.4.7 / libgpgme 1.6.0 did not work consistently. Inside the VM it did not work with 0.4.7 / 1.6.0 but it worked with 0.4.7 / 1.8.0. After I upgraded to 1.8.0 on my host machine, it did not work with my preinstalled keys. Only when I imported the keys from my VM but then it worked with 0.4.7 / 1.6.0 *and* 0.4.7 / 1.6.0. So I don't think it's a profanity issue but something related to libgpgme or even gnupg and the options used for generating the keys.

**Comment by jubalh** [comment]
@bascht @ReneVolution @BastiTee could you guys try this with latest master?

https://github.com/boothj5/profanity/commit/289b05ea5015ee38fe105839a7ad806678f38f15 might have fixed it.

**Comment by bascht** [comment]
@jubalh The fix looks really really _simple_ :D I sadly don't have anyone left to test GPG encryption anymore as most contacts have switched to OMEMO since.

**Comment by jubalh** [comment]
@bascht we can test together you want, and we find a time that suits us both :)

**Comment by jubalh** [comment]
@bascht and I tested this today. And general PGP encryption seems to work. We found another bug when doing this for which I will create another issue later on.
