### ISSUE TITLE
Current master doesn't build on OS X or segfault

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#801]
Hey there,

the latest master does not build on my OS X machine. After fixing some build warning with

`./configure --enable-notifications --enable-python-plugins --enable-c-plugins CFLAGS='-g -O0 -Wno-error=pointer-bool-conversion -Wno-error=logical-not-parentheses' CXXFLAGS='-g -O0'`

profanity starts but runs immediately into a segfault.

**Comment by boothj5** [comment]
Made a small change, if it still doesn't compile, attaching the compile errors would be useful.

Thanks.

**Comment by ReneVolution** [comment]
Yea ... first one (-Wpointer-bool-conversion)is fixed ... still get these errors now: http://pastebin.com/eCpa3Xh1.

**Comment by ReneVolution** [comment]
What i also just realised is that it opens X11 (!?!?). Since when is that needed?

**Comment by boothj5** [comment]
The remaining compile errors should be fixed.

If you get the segfault, the following contains instructions for attaching a backtrace: http://www.profanity.im/issues.html

What do you mean by opens X11?  If `libX11` is available profanity uses desktop activity to determine idle time, otherwise it falls back to using activity in profanity.  You should be able to force it to use profanity with `./configure --without-xscreensaver`

**Comment by ReneVolution** [comment]
Great … no more build errors.

After make i see:
ld: warning: directory not found for option '-L/usr/local/Cellar/libassuan/2.3.0_1/lib'
ld: warning: directory not found for option '-L/usr/local/Cellar/libgpg-error/1.20_1/lib'

and i wonder why it is looking for gpg stuff there as it is not installed via homebrew.

X11 => XQuartz 2.7.6 (xorg-server 1.14.6)

It still segfaults. I’ll recompile now and attach the backtrace.



On 27 April 2016 at 23:17:39, James Booth (notifications@github.com) wrote:

The remaining compile errors should be fixed.

If you get the segfault, the following contains instructions for attaching a backtrace: http://www.profanity.im/issues.html

What do you mean by opens X11? If libX11 is available profanity uses desktop activity to determine idle time, otherwise it falls back to using activity in profanity. You should be able to force it to use profanity with ./configure --without-xscreensaver

**Comment by ReneVolution** [comment]
Please finde the backtrace here: http://pastebin.com/sK3C0Duq

**Comment by boothj5** [comment]
It seems that the GTK tray icon functionality doesn't play nice with OSX when it has GTK installed.

I've added a commit to make it optional in the build:

```
./configure --disable-icons
```

Let me know if you still have problems after running this.

And as mentioned above, if you don't want profanity use X11 for idle time, add the following option:

```
./configure --without-xscreensaver
```

As for GPG, profanity uses the `gpgme-config` tool to determine where it's installed, if you run the following you should see where it is looking:

```
gpgme-config --libs --cflags
```

**Comment by ReneVolution** [comment]
yea ... disable-icons fixed it. Thanks a lot
