### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by moridius** [boothj5/profanity#808]
I tried to compile a debug version on a Raspberry Pi 2 with Arch Linux. Got these compile errors:

> $ make
rm -f src/gitversion.h.in
echo "#ifndef PROF_GIT_BRANCH" >> src/gitversion.h.in
echo "#define PROF_GIT_BRANCH \"master\"" >> src/gitversion.h.in
echo "#endif" >> src/gitversion.h.in
echo "#ifndef PROF_GIT_REVISION" >> src/gitversion.h.in
echo "#define PROF_GIT_REVISION \"0c84257\"" >> src/gitversion.h.in
echo "#endif" >> src/gitversion.h.in
cp src/gitversion.h.in src/gitversion.h
make  all-am
make[1]: Entering directory '/home/im/profanity'
depbase=`echo src/plugins/profapi.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/plugins/profapi.lo -MD -MP -MF $depbase.Tpo -c -o src/plugins/profapi.lo src/plugins/profapi.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -DTHEMES_PATH=\"/usr/local/share/profanity/themes\" -DICONS_PATH=\"/usr/local/share/profanity/icons\" -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0 -MT src/plugins/profapi.lo -MD -MP -MF src/plugins/.deps/profapi.Tpo -c src/plugins/profapi.c  -fPIC -DPIC -o src/plugins/.libs/profapi.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -DTHEMES_PATH=\"/usr/local/share/profanity/themes\" -DICONS_PATH=\"/usr/local/share/profanity/icons\" -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0 -MT src/plugins/profapi.lo -MD -MP -MF src/plugins/.deps/profapi.Tpo -c src/plugins/profapi.c -o src/plugins/profapi.o >/dev/null 2>&1
/bin/sh ./libtool  --tag=CC   --mode=link gcc -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -avoid-version -shared -no-undefined  -o libprofanity.la -rpath /usr/local/lib src/plugins/profapi.lo  -lglib-2.0 -lcurl -lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0    -lgio-2.0 -lotr -lgpgme -lassuan -lgpg-error -lX11 -lreadline -lncursesw -lstrophe   -ldl
libtool: link: gcc -shared  -fPIC -DPIC  src/plugins/.libs/profapi.o   -lcurl -lnotify -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lgio-2.0 -lotr -lgpgme -lassuan -lgpg-error -lX11 -lreadline -lncursesw -lstrophe -ldl  -g3 -O0   -Wl,-soname -Wl,libprofanity.so -o .libs/libprofanity.so
libtool: link: ( cd ".libs" && rm -f "libprofanity.la" && ln -s "../libprofanity.la" "libprofanity.la" )
depbase=`echo src/contact.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/contact.o -MD -MP -MF $depbase.Tpo -c -o src/contact.o src/contact.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/log.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/log.o -MD -MP -MF $depbase.Tpo -c -o src/log.o src/log.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/common.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/common.o -MD -MP -MF $depbase.Tpo -c -o src/common.o src/common.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/profanity.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/profanity.o -MD -MP -MF $depbase.Tpo -c -o src/profanity.o src/profanity.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/chat_session.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/chat_session.o -MD -MP -MF $depbase.Tpo -c -o src/chat_session.o src/chat_session.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/muc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/muc.o -MD -MP -MF $depbase.Tpo -c -o src/muc.o src/muc.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/jid.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/jid.o -MD -MP -MF $depbase.Tpo -c -o src/jid.o src/jid.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/chat_state.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/chat_state.o -MD -MP -MF $depbase.Tpo -c -o src/chat_state.o src/chat_state.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/resource.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/resource.o -MD -MP -MF $depbase.Tpo -c -o src/resource.o src/resource.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/roster_list.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/roster_list.o -MD -MP -MF $depbase.Tpo -c -o src/roster_list.o src/roster_list.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/xmpp/capabilities.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/xmpp/capabilities.o -MD -MP -MF $depbase.Tpo -c -o src/xmpp/capabilities.o src/xmpp/capabilities.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/xmpp/connection.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I./src  -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -DTHEMES_PATH="\"/usr/local/share/profanity/themes\"" -DICONS_PATH="\"/usr/local/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -Wunused -Werror -g3 -O0   -MT src/xmpp/connection.o -MD -MP -MF $depbase.Tpo -c -o src/xmpp/connection.o src/xmpp/connection.c &&\
mv -f $depbase.Tpo $depbase.Po
src/xmpp/connection.c: In function 'jabber_create_uuid':
src/xmpp/connection.c:395:12: error: implicit declaration of function 'xmpp_uuid_gen' [-Werror=implicit-function-declaration]
     return xmpp_uuid_gen(jabber_conn.ctx);
            ^~~~~~~~~~~~~
src/xmpp/connection.c:395:12: error: return makes pointer from integer without a cast [-Werror=int-conversion]
     return xmpp_uuid_gen(jabber_conn.ctx);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/xmpp/connection.c: In function 'jabber_conn_is_secured':
src/xmpp/connection.c:509:16: error: implicit declaration of function 'xmpp_conn_is_secured' [-Werror=implicit-function-declaration]
         return xmpp_conn_is_secured(jabber_conn.conn) == 0 ? FALSE : TRUE;
                ^~~~~~~~~~~~~~~~~~~~
src/xmpp/connection.c: In function '_jabber_connect':
src/xmpp/connection.c:574:9: error: implicit declaration of function 'xmpp_conn_set_flags' [-Werror=implicit-function-declaration]
         xmpp_conn_set_flags(jabber_conn.conn, XMPP_CONN_FLAG_MANDATORY_TLS);
         ^~~~~~~~~~~~~~~~~~~
src/xmpp/connection.c:574:47: error: 'XMPP_CONN_FLAG_MANDATORY_TLS' undeclared (first use in this function)
         xmpp_conn_set_flags(jabber_conn.conn, XMPP_CONN_FLAG_MANDATORY_TLS);
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/xmpp/connection.c:574:47: note: each undeclared identifier is reported only once for each function it appears in
src/xmpp/connection.c:576:47: error: 'XMPP_CONN_FLAG_DISABLE_TLS' undeclared (first use in this function)
         xmpp_conn_set_flags(jabber_conn.conn, XMPP_CONN_FLAG_DISABLE_TLS);
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:1903: recipe for target 'src/xmpp/connection.o' failed
make[1]: *** [src/xmpp/connection.o] Error 1
make[1]: Leaving directory '/home/im/profanity'
Makefile:1081: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pasis** [comment]
You need to install libstrophe or libmesode from git repository in order to build latest profanity. This issue will be gone when new versions of profanity, libstrophe and libmesode are released.

**Comment by boothj5** [comment]
Closing as per @pasis comment.
