### ISSUE TITLE
ACX_PTHREAD not defined

### ISSUE THREAD

**Issue by incertia** [boothj5/profanity#820]
bootstrap.sh should either download a copy of acx_pthread.m4 or a version should be pushed into the repository

**Comment by boothj5** [comment]
ACX_PTHREAD is part of the autoconf-archive package which is a new dependency in master.

It was renamed to AX_PTHREAD, but an alias exists for the old name, for backwards compatibility.

**Comment by incertia** [comment]
hmm okay...
configure script still only has -pthread in AM_CPPFLAGS and not LIBS in output (not /that/ big of a deal)
i also noticed when compiling that -pthread gets included twice, which doesn't affect compilers but is more of an aesthetic annoyance
closing.
