### ISSUE TITLE
Compiling on archlinux requires LDFLAGS modification

### ISSUE THREAD

**Issue by mrkiko** [boothj5/profanity#821]
I had to do:
LDFLAGS=-lpthread ./configure --prefix=/usr

Reporting this here in case it may become useful for profanity 
perfectioning or other users.

Symptoms: in my case, linking fails without adding this :(

**Comment by incertia** [comment]
install autoconf-archive
this makes it so that AX_PTHREAD and ACX_PTHREAD macro become defined and work (and will set LDFLAGS with the correct -pthread variant)

**Comment by mrkiko** [comment]
Thank you very much for the hint.
