### ISSUE TITLE
Profanity DNS threatment

### ISSUE THREAD

**Issue by mrkiko** [boothj5/profanity#822]
When connecting to jabber.calyxinstitute.org over telnet for example, it 
seems I can establish a session.
Profanity instead, will try to connect to the hidden .onion service 
address of the server even if I am not connected over tor.
Probably an entry in /etc/hosts may solve the problem, still I think it 
may be useful to report this problem.

From profanity logs:
07/07/2016 16:50:44: prof: INF: Starting Profanity (0.5.0dev.makepkg.3a3933e)...
07/07/2016 16:50:44: prof: INF: Initialising chat logs
07/07/2016 16:50:44: prof: INF: Initialising groupchat logs
07/07/2016 16:50:44: prof: INF: Loading accounts
07/07/2016 16:50:44: prof: INF: Initialising UI
07/07/2016 16:50:44: prof: INF: Initialising XMPP
07/07/2016 16:50:44: prof: INF: Loading capabilities cache
07/07/2016 16:50:44: prof: INF: Initialising commands
07/07/2016 16:50:44: prof: INF: Initialising contact list
07/07/2016 16:50:44: prof: INF: Loading TLS certificates
07/07/2016 16:50:44: prof: INF: Initialising OTR
07/07/2016 16:50:44: prof: DBG: GPG: Found gpgme version: 1.6.0
07/07/2016 16:50:44: prof: DBG: Env is GTK-ready: false
07/07/2016 16:50:44: prof: INF: Starting main event loop
07/07/2016 16:50:47: prof: DBG: Input received: /connect
07/07/2016 16:50:47: prof: INF: Connecting using account: ***
07/07/2016 16:50:47: prof: INF: Connecting as ****/****
07/07/2016 16:50:47: xmpp: DBG: sock_connect() to ****.onion:5222 returned -1
07/07/2016 16:50:47: prof: INF: Connection attempt for ****/**** failed
07/07/2016 16:50:53: prof: DBG: Input received: /quit
07/07/2016 16:50:53: prof: INF: Profanity is shutting down...

**Comment by mrkiko** [comment]
Turns out an entry in /etc/hosts isn't effective.
A smarter way probably, that worked for me was:
/account set my_account server <ipv4 addr>

Now /connect succeeds.

**Comment by pasis** [comment]
Hi,
resolving process is performed in libstrophe by simply calling `res_query(3)`. And as you see the function returns a record with an onion address. This is not a profanity or libstrophe issue. Please, check your name server configuration when you experience the problem.

**Comment by mrkiko** [comment]
Hello.
Thank you for your reply.

Actually my resolv.conf file looks like this:

domain lan
nameserver 208.67.220.220
nameserver 208.67.222.222

Where those IP address are OpenDNS servers. Am I doing something really wrong?
In case, I never noticed. Clients like "cjc" or programs like telnet / ping 
return normal IP addresses here, so I am a little bit confused regarding this 
behaviour.
Thanks again,
Enrico

**Comment by pasis** [comment]
I tried to resolve your domain and got:
```
$ nslookup -type=SRV _xmpp-client._tcp.jabber.calyxinstitute.org
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
_xmpp-client._tcp.jabber.calyxinstitute.org     service = 4 0 5222 ijeeynrc6x2uy5ob.onion.
_xmpp-client._tcp.jabber.calyxinstitute.org     service = 5 1 5222 jabber.calyxinstitute.org.
```
I think a number after `service =` means priority. And according to RFC a client must connect to the address with the lowest priority first. The thing is that libstrophe doesn't try to connect to other addresses. I'll add the feature to the todo list for the next release.

P.S. You can ping and telnet to `jabber.calyxinstitute.org` because those programs query for type `A` record. XMPP clients need to query type `SRV` record and only then resolve the result into IP address.

**Comment by mrkiko** [comment]
Thank you very much for your work and this...
Feel free to close the issue or do what's appropriate.

**Comment by pasis** [comment]
Fixed in libstrophe's master, thanks to @changeway for the patch.

**Comment by mrkiko** [comment]
Thank you very much guys.
