### ISSUE TITLE
<string.h> missing from src/plugins/c_api.c

### ISSUE THREAD

**Issue by ghenry** [boothj5/profanity#827]
Got below on 10.11.5 (15F34) so added <string.h> to c_api.c and all is well. Followed this guide:

https://github.com/louiecaulfield/profanity/wiki/Building-under-OS-X

24  * distribute linked combinations including the two.
src/plugins/c_api.c:368:18: error: implicitly declaring library function 'strndup' with type
      'char *(const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
    char *name = strndup(filename, strlen(filename)-1);
                 ^
src/plugins/c_api.c:368:18: note: include the header <string.h> or explicitly provide a declaration for 'strndup'
src/plugins/c_api.c:368:36: error: implicitly declaring library function 'strlen' with type 'unsigned long (const char *)'
      [-Werror,-Wimplicit-function-declaration]
    char *name = strndup(filename, strlen(filename)-1);
                                   ^
src/plugins/c_api.c:368:36: note: include the header <string.h> or explicitly provide a declaration for 'strlen'
2 errors generated.
make[1]: *** [src/plugins/c_api.o] Error 1
make: *** [all] Error 2

**Comment by boothj5** [comment]
Add the missing include.
