### ISSUE TITLE
Segmentation fault - Core dumped

### ISSUE THREAD

**Issue by sohom154** [boothj5/profanity#830]
HI,
I am getting a segmentation fault when ever i use the command `/form cancel` or `form submit' in a group chat.

System Information:
OS: ubuntu 16.04
Wm: i3 Wm
shell: zsh
profanity version: 0.4.7

[profanity.txt](https://github.com/boothj5/profanity/files/404887/profanity.txt)

**Comment by boothj5** [comment]
I can't currently recreate, if you're able to provide a backtrace it'll point me to the line of code where the issue is:

http://www.profanity.im/issues.html#backtrace

Thanks.

**Comment by sohom154** [comment]
make failed

`Makefile:1949: recipe for target 'src/xmpp/connection.o' failed`
`make[1]: *** [src/xmpp/connection.o] Error 1`
`make[1]: Leaving directory '/home/sohom/work_space/profanity'`
`Makefile:1103: recipe for target 'all' failed`
`make: *** [all] Error 2`

**Comment by boothj5** [comment]
Do you have the rest of the make output? somewhere in it will be the compile issue.

My guess is, if you're moving from 0.4.7 to latest code in master, you'll also need latest version of libmesode or libstrophe as there have been changes in them.

https://github.com/boothj5/libmesode

**Comment by sohom154** [comment]
http://pastebin.com/5U8x4Q6k

this is the full make output

**Comment by boothj5** [comment]
```
src/xmpp/connection.c:157:9: error: implicit declaration of function ‘xmpp_conn_set_flags’ [-Werror=implicit-function-declaration]
         xmpp_conn_set_flags(conn.xmpp_conn, XMPP_CONN_FLAG_MANDATORY_TLS);
```

Yep you need the latest libmesode/libstrophe.

**Comment by sohom154** [comment]
cant seem to compile the profanity thing ??  I compiled libmesode form your repo but the compilation of profanity still fails!!

**Comment by boothj5** [comment]
I need some information to understand why it is not compiling:

1) What commands you ran to install libmesode
2) What commands you ran to compile profanity again
3) The output from running ./configure for profanity (specifically the lines starting with `checking for libmesode...` and `checking for libstrophe...`)

**Comment by sohom154** [comment]
I can't seem to recreate the issue again..e
