### ISSUE TITLE
Multiple Profanity instances cause disconnects

### ISSUE THREAD

**Issue by nd2s** [boothj5/profanity#834]
When multiple Profanity instances that connect to the same account are launched at the same time, they alternately disconnect the other instances.

Profanity should either allow multiple instances (if allowed in the XMPP protocol), or detect the other instances and NOT try to connect to the same account again.

**Comment by boothj5** [comment]
XMPP defines each connection by its "resource". 

You cannot have two connections with the same resource, the behaviour in this case is up to the server, i.e. it may disconnect an older connection, or not allow the new connection.

Set the resource using the ``/account`` command in your different instances.
