### ISSUE TITLE
Beautiful code, layout and project

### ISSUE THREAD

**Issue by ghenry** [boothj5/profanity#835]
Not an issue, but just wanted to say that I love reading your source code, unit tests, functional tests, build env and everything in general.

This really is an outstanding project which I am learning a lot from. Looking to find any opportunities to contribute and will find one soon no doubt!

Thanks!

**Comment by boothj5** [comment]
Thanks a lot for the positive feedback.

The code has been evolving for about 5 years now, there are still a few areas that I think could do with tidying up, but I am in the habit of trying to improve readability every time I touch a piece of code.

If you'd like to make any contributions, I'd be happy to help out.

**Comment by ghenry** [comment]
It's a pleasure (also loved reading your CV). Every time I google something (today was gitignore autotools) profanity code shows up. I think I got here from libevent and libstrophe too. Just so clean and so nicely written. No broken windows as they say. I would say this is your CV (although you're Java mostly?)

Cool. I'll try when I can.
