### ISSUE TITLE
Fail to connect from IPv6 only client

### ISSUE THREAD

**Issue by Baggypants** [boothj5/profanity#837]
Hi I've been testing Profanity on Fedora on an IPv6 only machine and I can't get it to connect to my server. 

[baggypants@buildserver logs]$ rpm -qi profanity
Name        : profanity
Version     : 0.4.7
Release     : 1.fc24

[baggypants@buildserver logs]$ rpm -qi libstrophe
Name        : libstrophe
Version     : 0.8.8
Release     : 1.fc24

log:
https://paste.fedoraproject.org/412865/

There are all sorts of things that could be wrong with it. I run my own ejabberd server v 16.01. the ipv6 is attached to a HE tunnel. Having said that I've tested it on two different machines and pigeon does work under the same circumstances. Profanity does connect to the server when I turn back on IPv4 on the client machine.

Let me know what other info would be helpful.

**Comment by pasis** [comment]
IPv6 support is added to the future libstrophe-0.9 release. You need to build latest libstrophe or libmesode from sources or wait for the release.

**Comment by boothj5** [comment]
Should be fixed in 0.5.0
