### ISSUE TITLE
Segmentation fault when installing the same C plugin twice

### ISSUE THREAD

**Issue by Neo-Oli** [boothj5/profanity#850]
Just stumbled accross that by accident.
/plugins install ~/profanity-plugins/pid/pid.so
/plugins install ~/profanity-plugins/pid/pid.so
[1]    21332 segmentation fault (core dumped)  profanity

**Comment by boothj5** [comment]
I'm not currently able to recreate this issue.  If you can supply some details (OS etc) and you are able to provide a backtrace, I might be able to figure out what's happening:

http://www.profanity.im/issues.html#backtrace

**Comment by Neo-Oli** [comment]
I created a coredump with gdb, I hope this will work for you too. 


[coredump.zip](https://github.com/boothj5/profanity/files/499002/coredump.zip)

**Comment by Neo-Oli** [comment]
Also, the problem seems to only manifest on an aarch64 architecture. arm32 works. All this is on the termux platform.

**Comment by boothj5** [comment]
Are you able to provide a backtrace using gdb as per the page link above? I can't analyse the coredump without the executable that caused it.

Thanks.

**Comment by Neo-Oli** [comment]
Ah sorry, I was confused. Here's a backtrace: 
```
(gdb) bt
#0  0x0000000000000d70 in ?? ()
#1  0x0000007fb67c0fc0 in prof_init (version=0x555925beda "0.5.0",
    status=0x5559273680 "release",
    account_name=0x7fb697c760 "[MY JID]",
    fulljid=0x7fb6a8a100 "[MY JID]/mobile") at pid.c:35
#2  0x0000005559257810 in c_init_hook ()
#3  0x00000055592503fc in plugins_load ()
#4  0x000000555923dd34 in cmd_plugins ()
#5  0x0000005559239d34 in ?? ()
#6  0x0000007fb6974130 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

I then cross-compiled a version with debug-mode enabled and got the following backtrace:
```
(gdb) bt
#0  0x0000000000000d70 in ?? ()
#1  0x0000007fb6300fc0 in prof_init (version=0x5584198468 "0.5.0", status=0x5584198470 "release", account_name=0x7fb63a8820 "[MY JID]", fulljid=0x7fb63be1c0 "[MY JID]/mobile") at pid.c:35
#2  0x0000005584172988 in c_init_hook ()
#3  0x0000005584167d34 in plugins_load ()
#4  0x0000005584167c1c in plugins_install ()
#5  0x000000558414b5c8 in cmd_plugins ()
#6  0x000000558414d21c in ?? ()
#7  0x0000007fb6c3e950 in ?? ()
Backtrace stopped: not enough registers or memory available to unwind further
(gdb)
```
I censored my JID out of these backtraces.

**Comment by philipflohr** [comment]
Just tested, the current version of profanity does not try to load the plugin twice as it checks if the file already exists inside the plugin dir.

**Comment by Neo-Oli** [comment]
@philipflohr I just checked. I can also no longer reproduce this. So it seems it was fixed some time ago.

**Comment by jubalh** [comment]
Thanks guys!

@philipflohr I think your commit adb4955c34bd1cddda7482d214787a918d28171b fixed this, correct?

**Comment by philipflohr** [comment]
Seems like it did.

But there is another problem: it's possible to load the same plugin twice if the file is renamed. I don't know what happens but I think this should not be possible. Maybe profanity should do some checks on the commands added by a plugin?

**Comment by jubalh** [comment]
> Maybe profanity should do some checks on the commands added by a plugin?

That sounds like a good idea. So when installing a plugin we can make sure that there is no different plugin already installed claiming the same commands.
