### ISSUE TITLE
I can't write in profanity Pocket Chip

### ISSUE THREAD

**Issue by gurumelo** [boothj5/profanity#852]
Hi.
I installed profanity in pocket chip from repositories Debian jessie.

http://docs.getchip.com/pocketchip.html

When you exec profanity. You can't write. It's strange.

I test this in terminator, aterm, xfce4-terminal...

In irssi you can write.

**Comment by pasis** [comment]
Hi, try this: http://profanity.im/faq.html#utf8encoding

**Comment by gurumelo** [comment]
Thanks pasis.
I test
```
export LANG=en_US.UTF-8
profanity
```
But when i type, nothing.

libncursesw5 is installed. : (

**Comment by gurumelo** [comment]
Solved. Pocket Chip doesn't have installed locales
```
sudo apt-get install locales
sudo dpkg-reconfigure locales
[Ok]
en_US.UTF-8
[Space to mark]
[Enter]
None
[Enter]
profanity
```

**Comment by boothj5** [comment]
Thanks for the screenshot :)
