### ISSUE TITLE
profanity crashes on /connect

### ISSUE THREAD

**Issue by jubalh** [boothj5/profanity#860]
Summarizing here the conversation from profanitydev@conference.jabber.org:
```
profanity 0.5.0 
Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled
PGP support: Enabled
C plugins: Enabled
Python plugins: Disabled
GTK icons: Enabled
```
Crashes when trying to use `/connect`.
I open gnome-terminal or xterm start profanity. I trype `/connect` enter a JID enter a password. When I now press enter profanity dies and the shell sais it gave a return code of 127. No coredump present.

Package got installed from openSUSE repositories. Using profanity-standard binary.

**Comment by boothj5** [comment]
Some more details:

**Lubuntu 16:04**
Happened a few times but now seems to be working
From `/var/log/kern.log`:
```
Sep 18 21:12:46 ilx kernel: [19028.094171] profanity[8166]: segfault at 8 ip 00000000004428d8 sp 00007fffca72d960 error 4 in profanity[400000+69000]
```
`error 4` above suggests an `EINTR`

**Comment by jubalh** [comment]
In my case strace said `undefined symbol: xmpp_conn_set_`.
The packge clearly requires libstrophe >= 0.9.0 as a build requirement. rpm then automatically sets the runtime requirement from that.

I think since you added new API and profanity relies on that new parts, you maybe should have bumped the so version of libstrophe/libmesode?

http://www.rpm.org/max-rpm/s1-rpm-depend-auto-depend.html

I fixed the openSUSE package for now by explicitly do a runtime require on the exact version of libstrophe.

**Comment by jubalh** [comment]
Maybe the person using Ubuntu also has it working now *because* he updated libstrophe?

**Comment by jubalh** [comment]
The person Lubuntu had AFAIK the following experience:
* Had 0.4.x already installed via `apt`.
* Uninstall it
* Build and run it from source
-> It breaks (because there is still the old libstrophe on the system. So it builds but doesnt satisfy all symbols).
* Get 0.5.0 from PPA -> It works
* Remove it via `apt`
* Rebuild from source -> It works (because now libstrophe got pulled in from the repos when he installed profanity from PPA)

So I think this was the same mistake.

Debian (and derivates) have a special file to track symbols in libraries AFAIK. This means that when they build the package it gets automatically detected that they also need the new package and its automatically pulled in so there is no issue on the Debian side.

**Comment by boothj5** [comment]
@jubalh thanks for investigating and figuring out the problem.

Closing this issue, but feel free to add comments, or open another one if any other build problems occur.
