### ISSUE TITLE
Account command lists "muc service" but doesn't read disco#items

### ISSUE THREAD

**Issue by Ppjet6** [boothj5/profanity#878]
My xmpp server advertises via disco#items the jid of my MUC component but it is not read at all. Also if the disco doesn't list any item for MUC maybe it would be nice to not display any.

## Actual result

`"muc service       : conference.myserver"`

## Expected Behavior

`"muc service       : <whatever the disco says>"`

**Comment by asdil12** [comment]
`connection_jid_for_feature(STANZA_NS_MUC)` should return the MUC jid.

**Comment by asdil12** [comment]
It still might be a good idea to allow the user to overwrite the MUC jid in his account to allow him to use a foreign MUC service by default.

**Comment by boothj5** [comment]
Now uses the service discovery response. The user can still override by setting the property themselves.

Note: You'll need to clear the current setting to pick up the server feature:
```
/account clear <account> muc
```
