### ISSUE TITLE
[Plugins] Allow to disable active encryption 

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#885]
For the OMEMO plugin i am developing, it would be good to have the ability to turn off all previously activated encryption method for the active chat. Otherwise we may end up with OTR encrypted messages inside OMEMO encrypted messages /o\.

**Comment by boothj5** [comment]
Added an API call:

http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.encryption_reset

To get the barejid of the current chat recipient, the existing can be used:

http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.get_current_recipient

Tested with OTR and outgoing PGP sessions.  There is no way to stop a contact from sending PGP messages from their end.
