### ISSUE TITLE
[Plugins] Allow Plugins to set encryption protocol indicator

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#886]
Would be great if we could set the encryption protocol indicator (see the red 'unencrypted' in the screenshot) to visualise that the chat is encrypted or not.

Also, instead of prefixing the message with [*OMEMO*], it would be great if we could mark that message the same way as it works for OTR or PGP. 

![screen shot 2017-01-10 at 11 07 06](https://cloud.githubusercontent.com/assets/2199428/21802300/75fe1096-d725-11e6-8a27-99074010d71f.png)

**Comment by boothj5** [comment]
Added two API calls for setting and unsetting the encryption status in the titlebar:

http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.chat_set_titlebar_enctext
http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.chat_unset_titlebar_enctext

Unsetting it will go back to the default profanity behaviour.

I was thinking something similar for the display character, again per recipient, and for both incoming and outgoing messages.

`prof.chat_set_incoming_char(barejid, ch)`
`prof.chat_unset_incoming_char(barejid)`

`prof.chat_set_outgoing_char(barejid, ch)`
`prof.chat_unset_outgoing_char(barejid)`

Would this work for you?

**Comment by boothj5** [comment]
One other question, this is currently only for regular chat, but I'm guessing you would like something similar for chat rooms?

**Comment by ReneVolution** [comment]
Wow ... that looks great.
And you are right, at some point it would be great to have this for chat rooms as well. 
I am not there yet for sure, but if it is a low hanging fruit for you, it would be great to have it ready.
Thanks.

**Comment by boothj5** [comment]
Added the remaining functions to set the message prefix char:

[`prof.chat_set_incoming_char(barejid, ch)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.chat_set_incoming_char)
[`prof.chat_unset_incoming_char(barejid)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.chat_unset_incoming_char)
[`prof.chat_set_outgoing_char(barejid, ch)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.chat_set_outgoing_char)
[`prof.chat_unset_outgoing_char(barejid)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.chat_unset_outgoing_char)

Also added the equivalent for chat rooms:

[`prof.room_set_titlebar_enctext(roomjid, enctext)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.room_set_titlebar_enctext)
[`prof.room_unset_titlebar_enctext(roomjid)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.room_unset_titlebar_enctext)
[`prof.room_set_message_char(roomjid, ch)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.room_set_message_char)
[`prof.room_unset_message_char(roomjid)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.room_unset_message_char)

I'll close the issue, but feel free to comment if you need any changes and I'll reopen.
