### ISSUE TITLE
[Plugins] Allow Notifications in a chat history

### ISSUE THREAD

**Issue by ReneVolution** [boothj5/profanity#891]
Sometime you want to inform the user within the current chat window that e.g. a message could not be encrypted or any other informational message. ("You received a new device id from user bob@secure.it").

**Comment by boothj5** [comment]
Added calls to print to chat or room windows:

[`prof.chat_show(barejid, message)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.chat_show)
[`prof.chat_show_themed(barejid, group, key, default, ch, message)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.chat_show_themed)
[`prof.room_show(roomjid, message)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.room_show)
[`prof.room_show_themed(roomjid, group, key, default, ch, message)`](http://www.profanity.im/plugins/0.5.1/python/html/prof.html#prof.room_show_themed)
