### ISSUE TITLE
/msg tab completion intermittently doesn't work unless I'm on window 1 (Console)

### ISSUE THREAD

**Issue by asmartin** [boothj5/profanity#894]
I'm running profanity 0.4.7 on Ubuntu 16.04. I've noticed that intermittently when I am on a window chatting with a particular user (e.g. "User A"), and I try to run `/msg User<tab>` to start a conversation with a new user, the tab completion fails. If I switch back to the Console (via `/win 1`) and then execute the same command, it works. Other times, tab completion from a chat window with a particular user works just fine. Is this a bug?

**Comment by ReneVolution** [comment]
Do you have a chance to update? I am testing with the current master and could not reproduce.
Tough if you are in chat room, it only autocompletes to the users within the room.

**Comment by asmartin** [comment]
I would like to run the latest release, but the [Install Guide](http://www.profanity.im/install.html) only recommends installing from the official Ubuntu repos; there isn't a PPA or other official repository for newer versions. I could try building the new version in my own PPA, but don't have time right now.

I'll double-check that whenever I am seeing this I am not in a chat room - I cannot say for certain if I was in one or not

**Comment by asmartin** [comment]
I think this can be closed - I must have been on a chat room when I was attempting to use `/msg` and it was not working. Thanks for the clarification!
