### ISSUE TITLE
./bootstrap.sh of current git head fails with "configure.ac:87: error: possibly undefined macro: AC_MSG_ERROR"

### ISSUE THREAD

**Issue by lvml** [boothj5/profanity#897]
I can "./configure", compile and run the sources from the profanity-0.5.0.tar.gz, but trying to compile the sources from github fails already after invoking `./bootstrap.sh` with the following message: 

```
libtoolize: `build-aux/ltmain.sh' is newer: use `--force' to overwrite
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:87: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
(I also tried using newer automake/autoconf versions than provided by CentOS 7.3, but that didn't help.)

BTW: The bootstrap.sh from "libmesode" worked fine on the same system.

**Comment by boothj5** [comment]
I think the problem is that you need the `autoconf-archive` package installed, it has some extra macros used to generate the `./configure` script.

**Comment by lvml** [comment]
Thanks! - Indeed, "autoconf-archive" isn't available on CentOS, but it wasn't difficult to install it to some local directory, and then `autoreconf -i -v -f -I autoconf-archive-install-dir/share/aclocal` created a working "configure" file. Also compilation/installation worked fine afterwards.

BTW: Is https://github.com/ReneVolution/profanity-omemo-plugin the only possibility to have OMEMO support in profanity?
(I'm asking because that python-based plug-in seems to require an avalanche of dozens of dependencies, and basically all of them seem to be expected to be installed in good faith from some unsigned package off the Internet - which is kind of disturbing given the sensitive nature of cryptographic software...)

**Comment by boothj5** [comment]
The plugin is the only support for OMEMO at the moment, if you have some questions/concerns you could raise issues at the plugin maybe.
