### ISSUE TITLE
third example of alias command doesn't work

### ISSUE THREAD

**Issue by p-alik** [boothj5/profanity#899]
Hi,
  third example listed on [alias command reference](http://www.profanity.im/reference.html#alias) doesn't work in my environment. (profanity v0.4.7, Ubuntu 16.04) 
```
/alias a /away "I'm in a meeting."
Invalid usage, see '/help alias' for details.
```
Is it a new feature of v0.5?

**Comment by boothj5** [comment]
That's actually a documentation error, should be:

`/alias add a /away "I'm in a meeting."`

I'll close this issue when fixed the command help.
