### ISSUE TITLE
Screen not redrawn after PGP secret key entry

### ISSUE THREAD

**Issue by ghost** [boothj5/profanity#906]
After specifying the PGP key ID with pgp.keyid within the accounts file on startup profanity asks for the secret key passphrase. It then doesn't redraw the screen, leaving it in an odd looking state. Really the screen should be redrawn.

Using the /clear command helps, but still leaves some items on the roster looking strange.

**Comment by maxime-alves** [comment]
I found a way to fix this temporarily : 
/theme load mytheme
;D

Also it's good to say that this happens with the pinentry-curses program, because it shows itself in-screen, and doesn't pop-up another window. This is really problematic when working in a console-only session.
