### ISSUE TITLE
How can I register/create an account with profanity?

### ISSUE THREAD

**Issue by teran-mckinney** [boothj5/profanity#909]
Not seeing any such option. If I connect to a server with an unregistered user it does not prompt me to register.

Thank you!

**Comment by boothj5** [comment]
Currently account registration is not available in profanity.  Many servers don't allow it for security reasons, and instead have a web page with a captcha etc for registration.

But I can see it would be a useful feature for some users.

Closing this as there is another issue to implement in band registration #199

**Comment by teran-mckinney** [comment]
That's great, thank you!
