### ISSUE TITLE
/msg + Copy & Past 

### ISSUE THREAD

**Issue by p-alik** [boothj5/profanity#910]
It looks like `/msg ` followed by `Ctrl + V` sends a message for each line. Is the a way to send `Ctrl + V` content at once?

**Comment by boothj5** [comment]
There's an open issue for native paste detection #156 

Until it's been implemented there's a plugin which allows pasting clipboard contents as a single message:

https://github.com/boothj5/profanity/issues/156#issuecomment-199197050
