### ISSUE TITLE
wins autotidy do not work when leaving room

### ISSUE THREAD

**Issue by edoiks** [boothj5/profanity#917]
When leaving a room windows are not moved. A gap is left.

**Comment by demonking** [comment]
Which Version do you use? On 5.0 it works for me

**Comment by edoiks** [comment]
compiled from master, so 0.6.0

**Comment by boothj5** [comment]
I noticed autotidy only applies when using `/close` not with `/leave`.

Fixed in master, and the `/leave` command can also now be used in regular chat.
