### ISSUE TITLE
[Feature request] Shift-tab to go to previous autocomplete suggestion

### ISSUE THREAD

**Issue by klement** [boothj5/profanity#919]
It'd be nice to have shift-tab going backwards in the autocompletion list.

**Comment by boothj5** [comment]
Added this feature in the `shift-tab` branch, and still doing some testing. If you have a chance to try it out, let me know if it works as expected.

**Comment by klement** [comment]
Looks good, tested it out and found no issues so far..

**Comment by boothj5** [comment]
Thanks, merged to master.
