### ISSUE TITLE
Python plugin support macOS sierra

### ISSUE THREAD

**Issue by lindenlion** [boothj5/profanity#920]
I did `brew install profanity --with-terminal-notifier` but when I run profanity -v I get this:

> Profanity, version 0.5.1
> Copyright (C) 2012 - 2017 James Booth <boothj5web@gmail.com>.
> License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>
> 
> This is free software; you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Build information:
> XMPP library: libstrophe
> Desktop notification support: Enabled
> OTR support: Enabled
> PGP support: Enabled
> C plugins: Enabled
> Python plugins: Disabled
> GTK icons: Disabled

How do I enable Python plugins? I couldn't find any information on this. Do I need to uninstall profanity and rebuild with some dependency installed or something similar to `--with-..inserthere..` ?

On http://www.profanity.im/install.html#os-x it doesn't say what to do if not all features are enabled.

**Comment by boothj5** [comment]
Looking at the homebrew formula, plugins are not supported and explicitly disabled:  https://github.com/Homebrew/homebrew-core/blob/master/Formula/profanity.rb

To get it working you'd need the python-dev library and a manual install: http://www.profanity.im/install.html#manualinstall, dependencies are listed at the end.
