### ISSUE TITLE
/sendfile returns error Unsupported window for file transmission

### ISSUE THREAD

**Issue by michalwski** [boothj5/profanity#921]
I tried uploading file `/etc/hosts` as in the example and other png file. In both cases I got error:

`Unsupported window for file transmission`

I'm using profanity `0.5.1` installed from `brew`

**Comment by boothj5** [comment]
Which window are you running the command from? It only works in chat or MUC windows.

**Comment by michalwski** [comment]
Right, that was the reason. Thanks!
