### ISSUE TITLE
roster status state flood

### ISSUE THREAD

**Issue by sitano** [boothj5/profanity#923]
I have 1 contact in roster subscribed.

Every 5 seconds I've got a new message:

++ X (Y) is online

and it floods main window and subsequent chat.

Is it a bug, or how may I disable it? it totally floods all windows and chat histories

**Comment by boothj5** [comment]
You can configure presence change messages for different windows, for example:

```
/presence console none
/presence chat none
```

will stop showing the updates, in the main window (console) and chat windows.

**Comment by sitano** [comment]
Thx you! Did not get it myself 😢

**Comment by boothj5** [comment]
I've also just added a feature to search the help #924

Hopefully will make commands a bit easier to find.

**Comment by varac** [comment]
Would it be possible to redirect all buddy status updates to a seperate window ? If so, how would I do that ?
