### ISSUE TITLE
Thanks for all your work

### ISSUE THREAD

**Issue by Nomad145** [boothj5/profanity#932]
@boothj5: I don't have a bug to file, but I just wanted to say that Profanity is by far my favorite chat/XMPP client.  I use it daily both personally and professionally.

Thanks for all that you do for this project.

**Comment by boothj5** [comment]
@Nomad145 thanks for the message, glad you enjoy using it.

Also thanks for responding to queries/issues.  Whilst I will continue to maintain/develop profanity, I don't always have time respond, so help from users is much appreciated.
