### ISSUE TITLE
autoping is global and gets disabled by server which doesn't support it

### ISSUE THREAD

**Issue by klement** [boothj5/profanity#933]
I have two accounts and I want autoping enabled, otherwise profanity silently dies - everything looks fine and dandy, but in reality, the messages are not going out or coming in, because something somewhere broken.

But, one of the servers doesn't support autoping. And whenever profanity connects to that server, it changes the configuration option in the config file to autoping disabled. This disables the autoping on the next run for the first server as well. This is really not what I want. The error message that the autoping is not supported by the server @startup is fine, but changing the config file silently is not.

Changing the config file when I manually enable/disable/change feature is okay, but it shouldn't be done, when it's triggered by profanity itself and/or server.

**Comment by boothj5** [comment]
I think making this setting account specific would be a good solution.

There are other settings which should probably be account specific too, like `/carbons` for example, and anything else that depends on the server supporting certain features.  Added an issue for this #934, let me know if it wouldn't solve your problem.

**Comment by boothj5** [comment]
Closing as this is now part of the referenced issue.
