### ISSUE TITLE
Output Python version in `profanity --version`

### ISSUE THREAD

**Issue by devurandom** [boothj5/profanity#956]
`profanity --version` currently outputs something like the following:
```
Profanity, version 0.5.1
Copyright (C) 2012 - 2017 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled
PGP support: Enabled
C plugins: Enabled
Python plugins: Enabled
GTK icons: Enabled
```

It would be great if this could be enhanced to also output the version of Python Profanity was compiled against. E.g. as `Python plugins: Enabled (Python 3.4)`

Something similar might be useful for other lines in that output, e.g. libstrophe, OTR or PGP.

This would e.g. help in ReneVolution/profanity-omemo-plugin#24

**Comment by boothj5** [comment]
Added in master.  Libmesode/Libstrophe currently don't have a function to get the version, so I've left it out for now.
