### ISSUE TITLE
Compile failure on Fedora 26

### ISSUE THREAD

**Issue by mikeb01** [boothj5/profanity#960]
src/tls_openssl.c: In function ‘_x509_to_tlscert’:
src/tls_openssl.c:171:32: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  int alg_nid = OBJ_obj2nid(cert->cert_info->key->algor->algorithm);

**Comment by mikeb01** [comment]
Sorry this is a libmesode failure.

**Comment by timhughes** [comment]
@mikeb01 it needs to have an old version of openssl-devel. in Fedora there is a compat package compat-openssl10-devel. If you are using http://www.profanity.im/install-all.sh then you need to edit the ```fedora_prepare``` function. If installing from source this is what I used.

- Install the compat package

    ```sudo dnf install compat-openssl10-devel --allowerasing```

- configure, make, make install profanity
- Replace the normal openssl-devel

   ```sudo dnf install openssl-devel --allowerasing```
