### ISSUE TITLE
/close using ^D (Ctrl+D)

### ISSUE THREAD

**Issue by devurandom** [boothj5/profanity#964]
It would be nice if ^D (Ctrl+D) would issue the `/close` command.

**Comment by jubalh** [comment]
since https://github.com/boothj5/profanity/commit/ca29638f2c43f54033f5c5c99faf595a3e199bf3 (in latest 0.6.0 release) you can use inputrc.

For example you can add `Control-u: prof_win_close` to `~.config/profanity/inputrc`
