### ISSUE TITLE
Unable to locate package libcloog-isl4

### ISSUE THREAD

**Issue by RubikX** [boothj5/profanity#966]
I'm trying to install Profanity 0.5.1 for Windows 7 (64 bit) using Cygwin, however when I run 
`./install-all.sh` 
I get `Unable to locate package libcloog-isl4`

**Comment by rpresser-aleyant** [comment]
I, too, have this problem

**Comment by csuno** [comment]
same here. Win10 x64

**Comment by Disinterpreter** [comment]
Relevant now

**Comment by CardSnap** [comment]
It's available on cygwin.

**Comment by SunmerCho** [comment]
How to install it from cygwin?

**Comment by jubalh** [comment]
https://github.com/boothj5/profanity/issues/1030 is also about not being able to find a library on Windows.
I don't have Windows so can't test.

If cygwin doesnt work maybe try the Linux subsystem and install profanity from there. If you choose openSUSE you will even have the latest version.
