### ISSUE TITLE
Messages sent to me whilst offline are not seen when back online (HipChat)

### ISSUE THREAD

**Issue by strasky** [boothj5/profanity#970]
When I come back online I do not see any messages sent to me whilst I was away. I am running Profanity side-by-side with Hipchat and have to rely on HipChat to show me what I missed. Have I missed a configuration setting to enable this?

**Comment by Atavic** [comment]
Profanity supports [xep-0203](https://xmpp.org/extensions/xep-0203.html), does the jabber server you use support Delayed Delivery?

**Comment by strasky** [comment]
I found another HipChat user who wrote a helpful [wiki page](https://wiki.dequis.org/projects/hipchat/) on XMPP (last updated 2015) which states:

> XEP-0203: Delayed delivery
> 
> This is used to specify the timestamp of backlog msesages.
> 
> `<delay xmlns='urn:xmpp:delay' stamp='2013-09-09T01:50:52Z' from_jid='11111_22222@chat.hipchat.com'/>`
> 
> There's one slight difference with the standard, the "from" field is called "from_jid". This is not guaranteed to be a valid JID from the roster, however. Sometimes it is just the MUC JID.

The official [HipChat XMPP documentation](https://docs.atlassian.com/hipchat.xmpp/latest/index.html) makes no mention of delayed delivery or xep-0203, so it appears they have not fully documented their support of the various protocol extensions yet.

If the first source above is correct would the change in field name cause profanity to reject/ignore delayed messages? Could this be confirmed via logs/debugging in profanity?

If I can confirm this is the issue then I can make a request to Atlassian to conform with XEP-0203.

In addition would a profanity plugin be able to correct this protocol issue if detected for HipChat connections? Just thinking if Atlassian are slow/unwilling to prioritise the issue then this might be another option to get the functionality working.

**Comment by strasky** [comment]
Atlassian is replacing HipChat with Stride which does not support XMPP. I am going to close this issue as it's not going to be a problem in future - there will be no HipChat users left.
