### ISSUE TITLE
Wider tabs view

### ISSUE THREAD

**Issue by ari** [boothj5/profanity#972]
Tabs currently look like this:

`[1][2][3]-4-[5][ ][ ][ ][ ][ ][ ]`

But it is often hard to remember who is on which tab, so there is a lot of hunting through tabs.

I'd like to suggest a feature to allow a wider view like this:

`[1 dash] [2 Bob] [3 Aristedes] -4 Jacqueline- [5 Thomas]`

Now this isn't going to suit everyone with narrow screens. But I think it would be really helpful.

**Comment by boothj5** [comment]
See #416
