### ISSUE TITLE
Search the output from /rooms

### ISSUE THREAD

**Issue by grokkingit** [boothj5/profanity#978]
At least one of the servers I connect to has a few hundred rooms so finding anything in that list by eyeball is painful.
Is there currently a way to search for a string/substring in the list produced by running /rooms or at least arrange them alphabetically? Either one would make life a lot easier.

Thanks

**Comment by boothj5** [comment]
I've added a `filter` parameter to the `/rooms` command to only return rooms that contain the specified text (case insensitive).

New `/rooms` command examples:

```
/rooms
/rooms filter development
/rooms service conference.jabber.org
/rooms service conference.jabber.org filter "News Room"
```

It will match in the localpart of the room ID, for example `somedevelopmentroom@conference.server.org` will match the second example above, and will also match in the room name, if it has one `someroom@conference.server.org (The Development Room)`.

**Comment by boothj5** [comment]
I've added a couple of other small enhancements in master to make listing/searching rooms a bit easier.

1) Since the rooms response can take a while to be returned and processed if its a very large list, caching of the response is now enabled by default, so after the first request, subsequent text filtering should be instant.
2) Autocomplete the `service` argument based on any conference servers found in bookmarks, and previously joined rooms.

Full command help:

```
rooms
-----

Synopsis
/rooms
/rooms filter <text>
/rooms service <service>
/rooms service <service> filter <text>
/rooms cache on|off|clear

Description
List the chat rooms available at the specified conference service. If no argument is supplied, the account preference 'muc.service' is used, 'conference.<domain-part>' by default. The filter argument only shows rooms that contain the provided text, case insensitive.

Arguments
service <service> : The conference service to query.
filter <text>     : The text to filter results by.
cache on|off      : Enable or disable caching of rooms list response, enabled by default.
cache clear       : Clear the rooms response cache if enabled.

Examples
/rooms
/rooms filter development
/rooms service conference.jabber.org
/rooms service conference.jabber.org filter "News Room"
```

**Comment by boothj5** [comment]
Closed as feature added in master.
