### ISSUE TITLE
Question: Does profanity automatically free memory returned by plugins? (C API)

### ISSUE THREAD

**Issue by roobre** [boothj5/profanity#980]
Hi there!

First of all, let me congratulate you for creating such an amazing xmpp client, and thank you for all the hard work!
I'm currently writing some C plugins for profanity, and according to the docs, most hooks must return non-constant pointers to char. However, I don't see anywhere if this pointers are free()'d after use, or if the plugin is somehow responsible of freeing them. Could you clarify this somewhere?

Regards and thanks!

**Comment by boothj5** [comment]
For any hooks that return something, the memory will be free'd by profanity.

I've added an issue to the website to add this to the documentation: https://github.com/boothj5/www_profanity_im/issues/19
