### ISSUE TITLE
Configuring private storage for account when missing service requests

### ISSUE THREAD

**Issue by decentral1se** [boothj5/profanity#986]
Following from https://github.com/boothj5/profanity/issues/194#issuecomment-42746626, I saw:

> On adding a bookmark, if the server supports pubsub (from the service discovery request), always add as a pubsub bookmark, otherwise fall back to private-storage.

> Allow an option per account to always use private-storage for adding new bookmarks even if pubsub is available. This is so that if the user uses different clients, and some of them only use private-storage, then bookmarks added using profanity will still be picked up by them.

Well, so I am looking for the setting to configure private-storage since my riseup.net provider does not provide the pubsub autojoin magic. Is this implemented? If not, I really like the client and project and depending on the difficulty, I can try to get a patch in.

Thanks for all the work so far.

EDIT: I also saw https://github.com/boothj5/profanity/issues/349#issue-33249867.

**Comment by lwm** [comment]
Oh wait, I just realised the entire project is written in C. I haven't a hope!
