### ISSUE TITLE
Libotr not part of cygwinports?

### ISSUE THREAD

**Issue by CardSnap** [boothj5/profanity#988]
Cygwinports list of packages looking pretty bare to be frank. Couldn't find libotr among the list of packages. Is the cygwin install guide out of date? This probably means Profanity has zero room for otr-support on cygwin. I apologize in advance if I'm wrong.

**Comment by jubalh** [comment]
@CardSnap Sorry I'm not sure I understand the question.

On the profanity [website](http://www.profanity.im/install.html#windows) you can read:
```
Note: To make use of OTR support on Cygwin, the libotr-devel package is requirted which is not currently in the official repositories. libotr-devel can be found in the Cygwin Ports project.
```

I don't have any Windows system to try on but it seems that libotr [is](http://ftp.nchu.edu.tw/Unix/sourceware.org/cygwinports/x86/release/libotr/) in cygwinports.

I'll close this issue. Feel free to reopen if needed.
