### ISSUE TITLE
[docs] Command Reference is mentioned in man page, but empty in web.

### ISSUE THREAD

**Issue by Unip0rn** [boothj5/profanity#990]
the man page on Arch currently tells you to dig into https://www.profanity.im/reference.html
But that page contains not any information.

Further I would appreciate that very page as man page, e.g. profrc as [neo]mutt also provide.

[x] I checked this issue not to be a duplicate.
[x] I checked this page not to be on archive.org

**Comment by Unip0rn** [comment]
Sorry, missed #373 
However there the webpage is mentioned and now it is not available so I still consider this a bug?

**Comment by rjc** [comment]
The URL in the manual page is very clear - it's `HTTP`, **not** `HTTPS`. The former obviously works just fine.

**Comment by Unip0rn** [comment]
Right. that changes my report to "please support HTTPS", opening different issue on that.

**Comment by Unip0rn** [comment]
ok, I noticed that this issue already exists in #927 
Also sorry for misreading the man-page, btw.
