### ISSUE TITLE
Won't connect to anything.

### ISSUE THREAD

**Issue by coderboy14** [boothj5/profanity#996]
I'm running Profanity client on my MacBook, and tried connecting to my desktop running the server over LAN. My other client was able to connect, but when trying via profanity, it doesn't work. I even ran another server from my mac itself, with a username "a" password "1", but it still said my login was incorrect. My XAMPP/Jabber server is "Openfire" running on Centos7, and I should have the latest Profanity, I just got it today.

**Comment by pasis** [comment]
If the issue is still relevant, could you provide Profanity logs? They will tell on what step your authentication fails. Please, read [Attaching logs](http://www.profanity.im/issues.html#proflogs) carefully.

**Comment by jubalh** [comment]
@coderboy14 please reopen once you attach the log files.
