### ISSUE TITLE
Received pgp-messages not decrypt

### ISSUE THREAD

**Issue by vinegret** [boothj5/profanity#997]
I get GPGME error in logfile: 

```
22/04/2018 03:26:57: xmpp: DBG: RECV: <message id="prof_msg_50" type="chat" to="me1@example1.com/profanity" lang="en" from="me2@example2.com/profanity"><x xmlns="jabber:x:encrypted">SXENlfjxnbP+QPmWWY0r22+M0c3LH+7vcR0FJWwtx/S7RF+x/VkYKxiVXILcisdH
XE/Zx6QQx1RHwpmApBmNA4mVRTm7FSnI8bv/k5i68VkOGXtYzvfAawITfpFrNXuV
VpCDEzPmbO1fk0YFRyRK3pzhd+G6hO3VqhOk+zfVpdK60SyxPJHevXBeeiFIV0dE
jO3NV9t7Y+3TGUHbY9eQTPDJjCnzEQ82RBiI/sfu9FHzhZtDaj8HvtM7Zgmfe4Ga
E1+eD4gbszT52nExjrnYM3394ffwbCS88NE7I3+i1oUBDAMJGOpTX0UlswEH/juk
c7PMoWpWHYS+uCy3HcbIPzhhzOGBvMNi7okJ6Rue5G3kmkhyw6/90xNmPzzxhVZv
h+oW7DKNpvlZRYPam7x4EmHIZvfPpsDyKuOjI9nzvvpeJ88MgP3Ef1JyormPG/hq
Rfc9QHggbsmLeUc8+GscAdyS81qMR8HvPBKqBjJ69lKDBiOAlhmhLR/pWWADdjRY
7o/xjBMLIE/BRMVTmC9CRen0o1ZAxS1+2H17a0O0FFT476agA7kX8NC8jRK2V/el
ia7P4PsKvipqJ+RFeM6GJVKI3QPAkWCZWsCxOcBwwerPYZZhPw6whOhPeLQodzPi
vJ+9D9wO3muH+4pUEhnSPwFexFPo8CGty6tFx/5xkmBTchNP61BKhKFtmCMftjSk
J2A1CsHDS8DOof+qKTAD+lm4N18NTzkJmrHUhFp8nw==
=ls08
</x><body>This message is encrypted.</body></message>
22/04/2018 03:26:57: prof: DBG: Message stanza handler fired
22/04/2018 03:26:57: prof: ERR: GPG: Failed to encrypt message. GPGME No data
22/04/2018 03:26:57: prof: DBG: Attempting notification: me2@example2.com (win 2)
This message is encrypted.
22/04/2018 03:26:57: prof: DBG: Reinitialising libnotify
22/04/2018 03:26:57: prof: DBG: Notification sent.
```
Keys configured correctly. PGP session enabled. This behavior is seen on both sides. Versions profanity and libgpgme same on both sides. I tested with profanity 0.5, libgpgme 1.8.0 and with profanity 0.5.1, libgpgme 1.10.0.

**UPD:** pgp-messages, received from mcabber, are decoded correctly. But if sending from profanity,then mcabber received "This message is encrypted". Unlike profanity, mcabber also adds tag `<request xmlns="urn:xmpp:receipts"/>` in message after `</x>` and before `<body>`

**Comment by vinegret** [comment]
I decided to spend a little of my time for debugging this issue and sent [pull request](https://github.com/boothj5/profanity/pull/1008)

**Comment by jubalh** [comment]
Tested with two profanity instances from latest master.
Created two test gpg keys and two test accounts.

Wrote log files to two different location.

Wrote messages without pgp enabled -> worked
Enabled pgp in user1 and send -> user2 got only encrypted text.

Did a lot of various tests and can always reproduce this issue.
